In [3]:
import pandas as pd
import numpy as np

### Dagshub/Mlflow initialization ###

In [4]:
import dagshub
import mlflow
import mlflow.sklearn

dagshub.init(repo_owner='sbolk23', repo_name='House-Prices-Kaggle-Competition', mlflow=True)

Accessing as sbolk23

Initialized MLflow to track repo "sbolk23/House-Prices-Kaggle-Competition"

Repository sbolk23/House-Prices-Kaggle-Competition initialized!

In [5]:
PATH = './data'
TARGET = 'SalePrice'

In [6]:
# pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)

### Split Train/Test Data ###

In [7]:
df = pd.read_csv(PATH + '/train.csv')
# df = df.drop([523, 1298], axis=0)

In [8]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold

X = df.drop(columns=[TARGET])
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=.2, shuffle=True, random_state=1337
)

train_ids = X_train['Id']
test_ids = X_test['Id']

print(f'X_train shape {X_train.shape}')
print(f'X_test shape {X_test.shape}')

X_train shape (1168, 80)
X_test shape (292, 80)

### Data Cleaning ###

### Categorical Imputing ###

In [9]:
# we first impute all missing values in categorical and numeric features.

# These categorical columns may have 'NaN' values in them which means missing.
# data_description.txt did not mention 'Nan' was intended.

cat_impute_cols = [
    'MSZoning',
    'Street',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'Foundation',
    'ExterQual',
    'ExterCond',
    'Heating',
    'HeatingQC',
    'CentralAir',
    'Electrical',
    'KitchenQual',
    'Functional',
    'PavedDrive',
    'SaleType',
    'SaleCondition',
]

### Numeric Imputing ###

In [10]:
# We impute all numeric columns because data_description.txt did not mention any numeric feature with intended 'NaN' value.

# num_impute_cols = [
#     'LotFrontage',
#     'GarageYrBlt',
#     'MasVnrArea',
# ]

num_impute_cols = list(X_train.select_dtypes(exclude='object').columns)
num_impute_cols.remove('Id')
num_impute_cols.remove('MSSubClass')

### Categorical One-Hot-Encoded Columns ###

In [11]:
# Here we list features to be one-hot-encoded including 'NaN's because 'NaN' here does not mean missing.
# 'MasVnrType' was interesting column here.

cat_ohe_cols = [
    'MSZoning',
    'Street',
    'Alley',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'MasVnrType',
    'Foundation',
    'Heating',
    'CentralAir',
    'Electrical',
    'GarageType',
    'PavedDrive',
    'MiscFeature',
    'SaleType',
    'SaleCondition',
]

cat_ohe_missing_cols = [
    'MSZoning',
    'Street',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'Foundation',
    'Heating',
    'CentralAir',
    'Electrical',
    'PavedDrive',
    'SaleType',
    'SaleCondition'
]

cat_ohe_absent_cols = [
    'Alley',
    'MasVnrType',
    'GarageType',
    'MiscFeature'
]

### Ordinal Columns ###

In [12]:
# Some categorical columns can may be ordered, replace them with numbers.

cat_ord_cols = [
    'ExterQual',
    'ExterCond',
    'BsmtQual',
    'BsmtCond',
    'BsmtExposure',
    'BsmtFinType1',
    'BsmtFinType2',
    'HeatingQC',
    'KitchenQual',
    'Functional',
    'FireplaceQu',
    'GarageFinish',
    'GarageQual',
    'GarageCond',
    'PoolQC',
    'Fence',
]

cat_ord_missing_cols = [
    'ExterQual',
    'ExterCond',
    'HeatingQC',
    'KitchenQual',
    'Functional',
]

cat_ord_absent_cols = [
    'BsmtQual',
    'BsmtCond',
    'BsmtExposure',
    'BsmtFinType1',
    'BsmtFinType2',
    'FireplaceQu',
    'GarageFinish',
    'GarageQual',
    'GarageCond',
    'PoolQC',
    'Fence',
]

exter_qual_order        = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
exter_cond_order        = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
bsmt_qual_order         = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
bsmt_cond_order         = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
bsmt_exposure_order     = ['NA', 'No', 'Mn', 'Av', 'Gd']
bsmt_fin_type_1_order   = ['NA', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ']
bsmt_fin_type_2_order   = ['NA', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ']
heating_qc_order        = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
kitchen_qual_order      = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
functional_order        = ['Sal', 'Sev', 'Maj2', 'Maj1', 'Mod', 'Min2', 'Min1', 'Typ']
fireplace_qu_order      = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
garage_finish_order     = ['NA', 'Unf', 'RFn', 'Fin']
garage_qual_order       = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
garage_cond_order       = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
pool_qc_order           = ['NA', 'Fa', 'TA', 'Gd', 'Ex']
fence_order             = ['NA', 'MnWw', 'GdWo', 'MnPrv', 'GdPrv']

cat_ord_missing_categories = [
    exter_qual_order,
    exter_cond_order,
    heating_qc_order,
    kitchen_qual_order,
    functional_order,
]

cat_ord_absent_categories = [
    bsmt_qual_order,
    bsmt_cond_order,
    bsmt_exposure_order,
    bsmt_fin_type_1_order,
    bsmt_fin_type_2_order,
    fireplace_qu_order,
    garage_finish_order,
    garage_qual_order,
    garage_cond_order,
    pool_qc_order,
    fence_order,
]

### Numeric One-Hot-Encoded Columns ###

In [13]:
# This feature has numeric type which is misleading.

num_ohe_cols = [
    'MSSubClass',
]

### Irrelevant Columns ###

In [14]:
# This col is not informative.

irrelevant_cols = [
    'Id'
]

### Data Cleanup Pipeline ###

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

# scaling every column after preprocessing decreased accuracy.
# scaling only numeric columns is sufficient.

num_impute_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='median')),
    ('scale',   StandardScaler())
])

num_ohe_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='most_frequent')),
    ('ohe',     OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

cat_ord_missing_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='most_frequent')),
    ('ordinal', OrdinalEncoder(categories=cat_ord_missing_categories)),
])

cat_ord_absent_pipeline = Pipeline([
    ('nan_impute',  SimpleImputer(strategy='constant', missing_values=np.nan, fill_value='NA')),
    ('ordinal',     OrdinalEncoder(categories=cat_ord_absent_categories)),
])

cat_ohe_missing_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='most_frequent')),
    ('ohe',     OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
])

cat_ohe_absent_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='constant', missing_values=np.nan, fill_value='Missing')),
    ('ohe',     OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num_impute',       num_impute_pipeline,       num_impute_cols),
        ('num_ohe',          num_ohe_pipeline,          num_ohe_cols),
        ('cat_ord_absent',   cat_ord_absent_pipeline,   cat_ord_absent_cols),
        ('cat_ord_missing',  cat_ord_missing_pipeline,  cat_ord_missing_cols),
        ('cat_ohe_absent',   cat_ohe_absent_pipeline,   cat_ohe_absent_cols),
        ('cat_ohe_missing',  cat_ohe_missing_pipeline,  cat_ohe_missing_cols),
        ('drop',            'drop',                     irrelevant_cols),
    ],
    remainder='passthrough',
    verbose_feature_names_out=False,
)

preprocessor.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('num_impute',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='median')),
                                                 ('scale', StandardScaler())]),
                                 ['LotFrontage', 'LotArea', 'OverallQual',
                                  'OverallCond', 'YearBuilt', 'YearRemodAdd',
                                  'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
                                  'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF',
                                  '2ndFlrSF', 'LowQualFinSF', 'GrLivAre...
                                                                sparse_output=False))]),
                                 ['MSZoning', 'Street', 'LotShape',
                                  'LandContour', 'Utilities', 'LotConfig',
                                  'LandSlope', 'Neighborhood', 'Condition1',
                                  'Condition2', 'BldgType', 'HouseStyle',
                                  'RoofStyle', 'RoofMatl', 'Exterior1st',
                                  'Exterior2nd', 'Foundation', 'Heating',
                                  'CentralAir', 'Electrical', 'PavedDrive',
                                  'SaleType', 'SaleCondition']),
                                ('drop', 'drop', ['Id'])],
                  verbose_feature_names_out=False)

### Custom Scorer ###

In [16]:
from sklearn.metrics import make_scorer, root_mean_squared_log_error

def safe_rmsle(y_true, y_pred):
    y_pred_pos = np.maximum(y_pred, 0)
    return root_mean_squared_log_error(y_true, y_pred_pos)

safe_rmsle_scorer = make_scorer(safe_rmsle, greater_is_better=False)

### Full Pipeline (Linear Regression) ###

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.compose import TransformedTargetRegressor

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

final_model = TransformedTargetRegressor(
    regressor=pipeline,
)

param_grid = [
    {
        'regressor__preprocessor__num_impute__impute__strategy': 'mean',
        'func': np.log1p,
        'inverse_func': np.expm1
    },
    {
        'regressor__preprocessor__num_impute__impute__strategy': 'mean',
        'func': None,
        'inverse_func': None
    },
    {
        'regressor__preprocessor__num_impute__impute__strategy': 'median',
        'func': np.log1p,
        'inverse_func': np.expm1
    },
    {
        'regressor__preprocessor__num_impute__impute__strategy': 'median',
        'func': None,
        'inverse_func': None
    },
]

### MLFlow Logging (Linear Regression) ###

In [16]:
from sklearn.model_selection import KFold, cross_validate
from sklearn.base import clone

kf = KFold(n_splits=5, shuffle=True, random_state=1337)


mlflow.set_experiment('linear_regression')

for params in param_grid:
    num_imp = params['regressor__preprocessor__num_impute__impute__strategy']
    has_log = "logY" if params['func'] is not None else "rawY"

    run_name = f'LR__prep_v1__{has_log}__num_imp_{num_imp}__ord_imp__ohe'

    with mlflow.start_run(run_name=run_name):
        model = clone(final_model)
        model.set_params(**params)

        cv_results = cross_validate(
            model, X_train, y_train,
            cv=kf,
            scoring={
                'neg_root_mean_squared_log_error': safe_rmsle_scorer,
                'neg_root_mean_squared_error': 'neg_root_mean_squared_error',
                'neg_mean_absolute_error': 'neg_mean_absolute_error',
                'r2': 'r2',
            },
            return_train_score=True
        )

        print(f'Logging parameters ({run_name})')
        for key, value in params.items():
            mlflow.log_param(key, value)

        print(f'Logging preprocessing parameters ({run_name})')
        mlflow.log_param('num_impute_cols',         str(num_impute_cols))
        mlflow.log_param('num_ohe_cols',            str(num_ohe_cols))
        mlflow.log_param('cat_ord_absent_cols',     str(cat_ord_absent_cols))
        mlflow.log_param('cat_ord_missing_cols',    str(cat_ord_missing_cols))
        mlflow.log_param('cat_ohe_absent_cols',     str(cat_ohe_absent_cols))
        mlflow.log_param('cat_ohe_missing_cols',    str(cat_ohe_missing_cols))
        mlflow.log_param('irrelevant_cols',         str(irrelevant_cols))


        print(f'Logging train and validation metrics ({run_name})')

        mlflow.log_metric('mean_train_rmsle',        abs(np.array(cv_results['train_neg_root_mean_squared_log_error']).mean()))
        mlflow.log_metric('mean_validation_rmsle',   abs(np.array(cv_results['test_neg_root_mean_squared_log_error']).mean()))
        mlflow.log_metric('std_train_rmsle',         (np.array(cv_results['train_neg_root_mean_squared_log_error']).std()))
        mlflow.log_metric('std_validation_rmsle',    (np.array(cv_results['test_neg_root_mean_squared_log_error']).std()))

        mlflow.log_metric('mean_train_rmse',        abs(np.array(cv_results['train_neg_root_mean_squared_error']).mean()))
        mlflow.log_metric('mean_validation_rmse',   abs(np.array(cv_results['test_neg_root_mean_squared_error']).mean()))
        mlflow.log_metric('std_train_rmse',         (np.array(cv_results['train_neg_root_mean_squared_error']).std()))
        mlflow.log_metric('std_validation_rmse',    (np.array(cv_results['test_neg_root_mean_squared_error']).std()))

        mlflow.log_metric('mean_train_mae',         abs(np.array(cv_results['train_neg_mean_absolute_error']).mean()))
        mlflow.log_metric('mean_validation_mae',    abs(np.array(cv_results['test_neg_mean_absolute_error']).mean()))
        mlflow.log_metric('std_train_mae',          (np.array(cv_results['train_neg_mean_absolute_error']).std()))
        mlflow.log_metric('std_validation_mae',     (np.array(cv_results['test_neg_mean_absolute_error']).std()))

        mlflow.log_metric('mean_train_r2',          (np.array(cv_results['train_r2']).mean()))
        mlflow.log_metric('mean_validation_r2',     (np.array(cv_results['test_r2']).mean()))
        mlflow.log_metric('std_train_r2',           (np.array(cv_results['train_r2']).std()))
        mlflow.log_metric('std_validation_r2',      (np.array(cv_results['test_r2']).std()))


        for i in range(5):
            mlflow.log_metric(f'split{i}_train_rmsle',       abs(cv_results['train_neg_root_mean_squared_log_error'][i]))
            mlflow.log_metric(f'split{i}_validation_rmsle',  abs(cv_results['test_neg_root_mean_squared_log_error'][i]))
            mlflow.log_metric(f'split{i}_train_rmse',        abs(cv_results['train_neg_root_mean_squared_error'][i]))
            mlflow.log_metric(f'split{i}_validation_rmse',   abs(cv_results['test_neg_root_mean_squared_error'][i]))
            mlflow.log_metric(f'split{i}_train_mae',         abs(cv_results['train_neg_mean_absolute_error'][i]))
            mlflow.log_metric(f'split{i}_validation_mae',    abs(cv_results['test_neg_mean_absolute_error'][i]))
            mlflow.log_metric(f'split{i}_train_r2',          (cv_results['train_r2'][i]))
            mlflow.log_metric(f'split{i}_validation_r2',     (cv_results['test_r2'][i]))


        # Logging time metrics
        mlflow.log_metric('mean_fit_time',      np.array(cv_results['fit_time']).mean())
        mlflow.log_metric('std_fit_time',       np.array(cv_results['fit_time']).std())
        mlflow.log_metric('mean_score_time',    np.array(cv_results['score_time']).mean())
        mlflow.log_metric('std_score_time',     np.array(cv_results['score_time']).std())

        print(f'Logging final model ({run_name})')
        model.fit(X_train, y_train)

        model_info = mlflow.sklearn.log_model(
            sk_model=model,
            name='model',
        )

        mlflow.set_tag('model_type', 'LinearRegression')
        mlflow.set_tag('model_id', model_info.model_id)

Logging parameters (LR__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (LR__prep_v1__logY__num_imp_mean__ord_imp__ohe)
🏃 View run LR__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/5148738ded314a36b3e6831698c18aad
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1

KeyboardInterrupt:

### Full Pipeline (Ridge) ###

In [24]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.compose import TransformedTargetRegressor
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', Ridge())
])

final_model = TransformedTargetRegressor(
    regressor=pipeline,
)

param_grid = [
    {
        'regressor__preprocessor__num_impute__impute__strategy': ['mean', 'median'],
        'regressor__model__alpha': [.001, .01, .1,  1, 5, 10, 25, 50, 100, 1000],
        'func': [np.log1p],
        'inverse_func': [np.expm1],
    },
    {
        'regressor__preprocessor__num_impute__impute__strategy': ['mean', 'median'],
        'regressor__model__alpha': [.001, .01, .1,  1, 5, 10, 25, 50, 100, 1000],
        'func': [None],
        'inverse_func': [None],
    },

    # 'regressor__model__alpha': np.linspace(.01, 1000, 300),
    # 'regressor__model__alpha': np.logspace(np.log10(9.5), np.log10(10), 300),
]

In [25]:
from sklearn.model_selection import KFold
from sklearn.base import clone

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

grid_search_cv = GridSearchCV(
    final_model,
    param_grid,
    cv=kf,
    scoring={
        'neg_root_mean_squared_log_error': safe_rmsle_scorer,
        'neg_root_mean_squared_error': 'neg_root_mean_squared_error',
        'neg_mean_absolute_error': 'neg_mean_absolute_error',
        'r2': 'r2',
    },
    refit='neg_root_mean_squared_log_error',
    return_train_score=True,
    n_jobs=-1
)

grid_search_cv.fit(X_train, y_train)
cv_results_df = pd.DataFrame(grid_search_cv.cv_results_)

mlflow.set_experiment('linear_regression')

for i, row in cv_results_df.iterrows():
    row_dict = row.to_dict()

    print(row_dict)

    params = row_dict['params']
    alpha = row_dict['param_regressor__model__alpha']
    num_imp = row_dict['param_regressor__preprocessor__num_impute__impute__strategy']
    has_log = "logY" if row_dict['param_func'] is not None else "rawY"

    run_name = f'RIDGE__alpha_{alpha}__prep_v1__{has_log}__num_imp_{num_imp}__ord_imp__ohe'

    with mlflow.start_run(run_name=run_name):
        print(f'Logging parameters ({run_name})')
        for key, value in row_dict.items():
            if 'param_' in key:
                mlflow.log_param(key.replace('param_', ''), value)

        print(f'Logging preprocessing parameters ({run_name})')
        mlflow.log_param('num_impute_cols',         str(num_impute_cols))
        mlflow.log_param('num_ohe_cols',            str(num_ohe_cols))
        mlflow.log_param('cat_ord_absent_cols',     str(cat_ord_absent_cols))
        mlflow.log_param('cat_ord_missing_cols',    str(cat_ord_missing_cols))
        mlflow.log_param('cat_ohe_absent_cols',     str(cat_ohe_absent_cols))
        mlflow.log_param('cat_ohe_missing_cols',    str(cat_ohe_missing_cols))
        mlflow.log_param('irrelevant_cols',         str(irrelevant_cols))

        print(f'Logging train and validation metrics ({run_name})')
        for key, value in row_dict.items():
            if 'rank' in key:
                continue

            if 'neg_root_mean_squared_log_error' in key:
                mlflow.log_metric(
                    key.replace('neg_root_mean_squared_log_error', 'rmsle').replace('test', 'validation'), abs(value))

            if 'neg_root_mean_squared_error' in key:
                mlflow.log_metric(
                    key.replace('neg_root_mean_squared_error', 'rmse').replace('test', 'validation'), abs(value))

            if 'neg_mean_absolute_error' in key:
                mlflow.log_metric(
                    key.replace('neg_mean_absolute_error', 'mae').replace('test', 'validation'), abs(value))

            if 'r2' in key:
                mlflow.log_metric(key.replace('test', 'validation'), (value))


        # Logging time metrics
        mlflow.log_metric('mean_fit_time',      row_dict['mean_fit_time'])
        mlflow.log_metric('std_fit_time',       row_dict['std_fit_time'])
        mlflow.log_metric('mean_score_time',    row_dict['mean_score_time'])
        mlflow.log_metric('std_score_time',     row_dict['std_score_time'])

        model = clone(final_model)
        model.set_params(**params)

        print(f'Logging final model ({run_name})')
        model.fit(X_train, y_train)

        model_info = mlflow.sklearn.log_model(
            sk_model=model,
            name='model',
        )

        mlflow.set_tag('model_type', 'LinearRegression')
        mlflow.set_tag('model_id', model_info.model_id)

{'mean_fit_time': 0.13090081214904786, 'std_fit_time': 0.0037938894402134633, 'mean_score_time': 0.07557978630065917, 'std_score_time': 0.014778919163126203, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 0.001, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 0.001, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.1632601294549023, 'split1_test_neg_root_mean_squared_log_error': -0.14243554151911755, 'split2_test_neg_root_mean_squared_log_error': -0.20397260326353656, 'split3_test_neg_root_mean_squared_log_error': -0.17187506026362612, 'split4_test_neg_root_mean_squared_log_error': -0.18222570103291943, 'mean_test_neg_root_mean_squared_log_error': -0.1727538071068204, 'std_test_neg_root_mean_squared_log_error': 0.020368747372586794, 'rank_test_neg_root_mean_squared_log_error': 20, 'split0_train_neg_root_mean_squared_log_error': -0.0880759625748569, 'split1_train_neg_root_mean_squared_log_error': -0.08969249966946755, 'split2_train_neg_root_mean_squared_log_error': -0.09119259834112667, 'split3_train_neg_root_mean_squared_log_error': -0.09180571711366808, 'split4_train_neg_root_mean_squared_log_error': -0.08596935097916301, 'mean_train_neg_root_mean_squared_log_error': -0.08934722573565644, 'std_train_neg_root_mean_squared_log_error': 0.002125791235879408, 'split0_test_neg_root_mean_squared_error': -50462.27138096736, 'split1_test_neg_root_mean_squared_error': -27968.529394635287, 'split2_test_neg_root_mean_squared_error': -113415.4720433449, 'split3_test_neg_root_mean_squared_error': -28277.392614879747, 'split4_test_neg_root_mean_squared_error': -32752.096840029397, 'mean_test_neg_root_mean_squared_error': -50575.15245477135, 'std_test_neg_root_mean_squared_error': 32480.238052199144, 'rank_test_neg_root_mean_squared_error': 40, 'split0_train_neg_root_mean_squared_error': -17139.67076466405, 'split1_train_neg_root_mean_squared_error': -18177.251541795005, 'split2_train_neg_root_mean_squared_error': -19028.299504336926, 'split3_train_neg_root_mean_squared_error': -18072.920895190822, 'split4_train_neg_root_mean_squared_error': -16358.256701594468, 'mean_train_neg_root_mean_squared_error': -17755.279881516253, 'std_train_neg_root_mean_squared_error': 919.8025011624431, 'split0_test_neg_mean_absolute_error': -16785.55274070241, 'split1_test_neg_mean_absolute_error': -17815.641321984032, 'split2_test_neg_mean_absolute_error': -21075.47087397898, 'split3_test_neg_mean_absolute_error': -17208.014711218915, 'split4_test_neg_mean_absolute_error': -18084.929832929665, 'mean_test_neg_mean_absolute_error': -18193.9218961628, 'std_test_neg_mean_absolute_error': 1510.8816386188882, 'rank_test_neg_mean_absolute_error': 14, 'split0_train_neg_mean_absolute_error': -11290.367888851124, 'split1_train_neg_mean_absolute_error': -11219.104586945814, 'split2_train_neg_mean_absolute_error': -11841.983435414477, 'split3_train_neg_mean_absolute_error': -11662.49122339231, 'split4_train_neg_mean_absolute_error': -10661.25461362539, 'mean_train_neg_mean_absolute_error': -11335.040349645822, 'std_train_neg_mean_absolute_error': 408.32323343568544, 'split0_test_r2': 0.635155864948937, 'split1_test_r2': 0.882824844872276, 'split2_test_r2': -1.7763297094589507, 'split3_test_r2': 0.8804130660341913, 'split4_test_r2': 0.8785450174347658, 'mean_test_r2': 0.3001218167662439, 'std_test_r2': 1.0425692213198254, 'rank_test_r2': 40, 'split0_train_r2': 0.9563741535245773, 'split1_train_r2': 0.951479268011204, 'split2_train_r2': 0.9504126623550007, 'split3_train_r2': 0.9519912059575805, 'split4_train_r2': 0.9572545034435419, 'mean_train_r2': 0.9535023586583808, 'std_train_r2': 0.0027658090223757615}
Logging parameters (RIDGE__alpha_0.001__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.001__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.001__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.001__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 18:52:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.001__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/62d59250dfd44b1a87f0c626ccb37e23
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.1491565227508545, 'std_fit_time': 0.02017520726537496, 'mean_score_time': 0.0652618408203125, 'std_score_time': 0.0031590298958125112, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 0.001, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 0.001, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.16322408877151753, 'split1_test_neg_root_mean_squared_log_error': -0.14240678300978496, 'split2_test_neg_root_mean_squared_log_error': -0.20396730817409214, 'split3_test_neg_root_mean_squared_log_error': -0.1718678280139666, 'split4_test_neg_root_mean_squared_log_error': -0.18224206388519298, 'mean_test_neg_root_mean_squared_log_error': -0.17274161437091085, 'std_test_neg_root_mean_squared_log_error': 0.020380634358645927, 'rank_test_neg_root_mean_squared_log_error': 19, 'split0_train_neg_root_mean_squared_log_error': -0.08808420958446732, 'split1_train_neg_root_mean_squared_log_error': -0.08969828426585076, 'split2_train_neg_root_mean_squared_log_error': -0.09119241582955145, 'split3_train_neg_root_mean_squared_log_error': -0.0918082294666802, 'split4_train_neg_root_mean_squared_log_error': -0.0859691338714648, 'mean_train_neg_root_mean_squared_log_error': -0.08935045460360291, 'std_train_neg_root_mean_squared_log_error': 0.0021256138055387465, 'split0_test_neg_root_mean_squared_error': -50420.71348628911, 'split1_test_neg_root_mean_squared_error': -27962.6299652198, 'split2_test_neg_root_mean_squared_error': -113398.00315324705, 'split3_test_neg_root_mean_squared_error': -28277.792981240113, 'split4_test_neg_root_mean_squared_error': -32744.875859130836, 'mean_test_neg_root_mean_squared_error': -50560.80308902539, 'std_test_neg_root_mean_squared_error': 32475.069108674306, 'rank_test_neg_root_mean_squared_error': 39, 'split0_train_neg_root_mean_squared_error': -17143.095999546094, 'split1_train_neg_root_mean_squared_error': -18180.27513000007, 'split2_train_neg_root_mean_squared_error': -19028.42041802876, 'split3_train_neg_root_mean_squared_error': -18072.207438113663, 'split4_train_neg_root_mean_squared_error': -16358.56654837108, 'mean_train_neg_root_mean_squared_error': -17756.513106811934, 'std_train_neg_root_mean_squared_error': 919.5129688245166, 'split0_test_neg_mean_absolute_error': -16778.17843853987, 'split1_test_neg_mean_absolute_error': -17807.682303563495, 'split2_test_neg_mean_absolute_error': -21071.672730124505, 'split3_test_neg_mean_absolute_error': -17207.849655812428, 'split4_test_neg_mean_absolute_error': -18085.11341739308, 'mean_test_neg_mean_absolute_error': -18190.099309086676, 'std_test_neg_mean_absolute_error': 1511.2289773851412, 'rank_test_neg_mean_absolute_error': 13, 'split0_train_neg_mean_absolute_error': -11291.042083355456, 'split1_train_neg_mean_absolute_error': -11219.661498439978, 'split2_train_neg_mean_absolute_error': -11842.116537814487, 'split3_train_neg_mean_absolute_error': -11662.920992426734, 'split4_train_neg_mean_absolute_error': -10660.854513505483, 'mean_train_neg_mean_absolute_error': -11335.319125108428, 'std_train_neg_mean_absolute_error': 408.51101731377605, 'split0_test_r2': 0.6357565478105702, 'split1_test_r2': 0.8828742714003859, 'split2_test_r2': -1.775474523431491, 'split3_test_r2': 0.8804096796594222, 'split4_test_r2': 0.8785985668263043, 'mean_test_r2': 0.30043290845303827, 'std_test_r2': 1.0422782866200888, 'rank_test_r2': 39, 'split0_train_r2': 0.9563567151846851, 'split1_train_r2': 0.9514631248760178, 'split2_train_r2': 0.9504120321560581, 'split3_train_r2': 0.9519949963285995, 'split4_train_r2': 0.9572528841169843, 'mean_train_r2': 0.9534959505324689, 'std_train_r2': 0.002763849510296564}
Logging parameters (RIDGE__alpha_0.001__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.001__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.001__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.001__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 18:54:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.001__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/05275345d087416aabab5b9ec48beb4a
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.18865504264831542, 'std_fit_time': 0.059688689266513585, 'mean_score_time': 0.0638033390045166, 'std_score_time': 0.004218630098340344, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 0.01, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 0.01, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.16189534183126453, 'split1_test_neg_root_mean_squared_log_error': -0.14201933793507412, 'split2_test_neg_root_mean_squared_log_error': -0.2039238349596577, 'split3_test_neg_root_mean_squared_log_error': -0.1682488280750081, 'split4_test_neg_root_mean_squared_log_error': -0.1792827386599148, 'mean_test_neg_root_mean_squared_log_error': -0.17107401629218386, 'std_test_neg_root_mean_squared_log_error': 0.02041028072885575, 'rank_test_neg_root_mean_squared_log_error': 18, 'split0_train_neg_root_mean_squared_log_error': -0.08809421708665602, 'split1_train_neg_root_mean_squared_log_error': -0.08970365683486343, 'split2_train_neg_root_mean_squared_log_error': -0.09119720621154219, 'split3_train_neg_root_mean_squared_log_error': -0.09182859084375912, 'split4_train_neg_root_mean_squared_log_error': -0.08599119693612427, 'mean_train_neg_root_mean_squared_log_error': -0.08936297358258902, 'std_train_neg_root_mean_squared_log_error': 0.002123128055190923, 'split0_test_neg_root_mean_squared_error': -50186.07972204522, 'split1_test_neg_root_mean_squared_error': -28287.547232717174, 'split2_test_neg_root_mean_squared_error': -113378.1180870224, 'split3_test_neg_root_mean_squared_error': -27824.65867069442, 'split4_test_neg_root_mean_squared_error': -32509.470133785442, 'mean_test_neg_root_mean_squared_error': -50437.17476925293, 'std_test_neg_root_mean_squared_error': 32511.41298764111, 'rank_test_neg_root_mean_squared_error': 38, 'split0_train_neg_root_mean_squared_error': -17152.49061055354, 'split1_train_neg_root_mean_squared_error': -18187.93096814648, 'split2_train_neg_root_mean_squared_error': -19029.729864851375, 'split3_train_neg_root_mean_squared_error': -18079.779235767226, 'split4_train_neg_root_mean_squared_error': -16378.784966297348, 'mean_train_neg_root_mean_squared_error': -17765.743129123195, 'std_train_neg_root_mean_squared_error': 913.7018455440863, 'split0_test_neg_mean_absolute_error': -16776.424341100603, 'split1_test_neg_mean_absolute_error': -17869.221886287785, 'split2_test_neg_mean_absolute_error': -21074.866680324038, 'split3_test_neg_mean_absolute_error': -16969.38159551771, 'split4_test_neg_mean_absolute_error': -18018.086593139265, 'mean_test_neg_mean_absolute_error': -18141.59621927388, 'std_test_neg_mean_absolute_error': 1544.75236745505, 'rank_test_neg_mean_absolute_error': 12, 'split0_train_neg_mean_absolute_error': -11311.779225860613, 'split1_train_neg_mean_absolute_error': -11241.68242611914, 'split2_train_neg_mean_absolute_error': -11842.742321560321, 'split3_train_neg_mean_absolute_error': -11689.37597380928, 'split4_train_neg_mean_absolute_error': -10692.419710781325, 'mean_train_neg_mean_absolute_error': -11355.599931626135, 'std_train_neg_mean_absolute_error': 400.85399138357855, 'split0_test_r2': 0.6391386879130041, 'split1_test_r2': 0.8801365266091254, 'split2_test_r2': -1.7745012143049577, 'split3_test_r2': 0.8842116943915411, 'split4_test_r2': 0.8803378231043717, 'mean_test_r2': 0.3018647035426169, 'std_test_r2': 1.0424208971899063, 'rank_test_r2': 38, 'split0_train_r2': 0.9563088680479178, 'split1_train_r2': 0.9514222378490542, 'split2_train_r2': 0.9504052070975727, 'split3_train_r2': 0.9519547621379796, 'split4_train_r2': 0.9571471519728365, 'mean_train_r2': 0.9534476454210722, 'std_train_r2': 0.002737164625262571}
Logging parameters (RIDGE__alpha_0.01__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.01__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.01__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.01__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 18:56:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.01__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/3afe1d1424ec4074a3e922f65f251a8b
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.15325140953063965, 'std_fit_time': 0.014920430989801182, 'mean_score_time': 0.06822094917297364, 'std_score_time': 0.008676509294259154, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 0.01, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 0.01, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.16185984311897422, 'split1_test_neg_root_mean_squared_log_error': -0.141990991316786, 'split2_test_neg_root_mean_squared_log_error': -0.20391862138688352, 'split3_test_neg_root_mean_squared_log_error': -0.16823859781443873, 'split4_test_neg_root_mean_squared_log_error': -0.17929721262028173, 'mean_test_neg_root_mean_squared_log_error': -0.17106105325147286, 'std_test_neg_root_mean_squared_log_error': 0.02042131792223284, 'rank_test_neg_root_mean_squared_log_error': 17, 'split0_train_neg_root_mean_squared_log_error': -0.0881024632109744, 'split1_train_neg_root_mean_squared_log_error': -0.089709425871321, 'split2_train_neg_root_mean_squared_log_error': -0.09119702373703291, 'split3_train_neg_root_mean_squared_log_error': -0.0918311395386299, 'split4_train_neg_root_mean_squared_log_error': -0.08599099966390189, 'mean_train_neg_root_mean_squared_log_error': -0.08936621040437202, 'std_train_neg_root_mean_squared_log_error': 0.0021229533421213216, 'split0_test_neg_root_mean_squared_error': -50145.96284396947, 'split1_test_neg_root_mean_squared_error': -28281.29137244331, 'split2_test_neg_root_mean_squared_error': -113360.54353576445, 'split3_test_neg_root_mean_squared_error': -27824.588220717305, 'split4_test_neg_root_mean_squared_error': -32501.539288613443, 'mean_test_neg_root_mean_squared_error': -50422.785052301595, 'std_test_neg_root_mean_squared_error': 32506.40972360518, 'rank_test_neg_root_mean_squared_error': 37, 'split0_train_neg_root_mean_squared_error': -17155.68661105021, 'split1_train_neg_root_mean_squared_error': -18190.974446609613, 'split2_train_neg_root_mean_squared_error': -19029.797494605995, 'split3_train_neg_root_mean_squared_error': -18079.071538700446, 'split4_train_neg_root_mean_squared_error': -16378.90247065153, 'mean_train_neg_root_mean_squared_error': -17766.88651232356, 'std_train_neg_root_mean_squared_error': 913.489927161029, 'split0_test_neg_mean_absolute_error': -16769.53851822858, 'split1_test_neg_mean_absolute_error': -17860.971198499825, 'split2_test_neg_mean_absolute_error': -21071.16930051536, 'split3_test_neg_mean_absolute_error': -16970.99128994919, 'split4_test_neg_mean_absolute_error': -18018.366211960278, 'mean_test_neg_mean_absolute_error': -18138.207303830648, 'std_test_neg_mean_absolute_error': 1544.6122676671469, 'rank_test_neg_mean_absolute_error': 11, 'split0_train_neg_mean_absolute_error': -11312.513198122673, 'split1_train_neg_mean_absolute_error': -11242.2609920984, 'split2_train_neg_mean_absolute_error': -11842.873875149528, 'split3_train_neg_mean_absolute_error': -11690.1178707206, 'split4_train_neg_mean_absolute_error': -10691.809861596374, 'mean_train_neg_mean_absolute_error': -11355.915159537515, 'std_train_neg_mean_absolute_error': 401.1625829154687, 'split0_test_r2': 0.6397153754447251, 'split1_test_r2': 0.8801895369475489, 'split2_test_r2': -1.77364113944257, 'split3_test_r2': 0.8842122807256451, 'split4_test_r2': 0.8803962003362786, 'mean_test_r2': 0.3021744508023255, 'std_test_r2': 1.0421280254766814, 'rank_test_r2': 37, 'split0_train_r2': 0.9562925847113732, 'split1_train_r2': 0.9514059789636417, 'split2_train_r2': 0.9504048545870896, 'split3_train_r2': 0.9519585233352823, 'split4_train_r2': 0.9571465371025265, 'mean_train_r2': 0.9534416957399827, 'std_train_r2': 0.002735681443891379}
Logging parameters (RIDGE__alpha_0.01__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.01__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.01__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.01__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 18:59:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.01__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/8268fc0c041f4e749aed90ee2d651460
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.14698076248168945, 'std_fit_time': 0.016025722091092365, 'mean_score_time': 0.06505169868469238, 'std_score_time': 0.00451722587448201, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 0.1, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 0.1, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.15414664488790156, 'split1_test_neg_root_mean_squared_log_error': -0.13962400407603107, 'split2_test_neg_root_mean_squared_log_error': -0.20355874523332385, 'split3_test_neg_root_mean_squared_log_error': -0.15301586979002332, 'split4_test_neg_root_mean_squared_log_error': -0.16653716892133874, 'mean_test_neg_root_mean_squared_log_error': -0.1633764865817237, 'std_test_neg_root_mean_squared_log_error': 0.02182345805034924, 'rank_test_neg_root_mean_squared_log_error': 16, 'split0_train_neg_root_mean_squared_log_error': -0.08906939811165898, 'split1_train_neg_root_mean_squared_log_error': -0.09039066497716365, 'split2_train_neg_root_mean_squared_log_error': -0.09136986922207989, 'split3_train_neg_root_mean_squared_log_error': -0.09251888510375618, 'split4_train_neg_root_mean_squared_log_error': -0.08700030318921352, 'mean_train_neg_root_mean_squared_log_error': -0.09006982412077444, 'std_train_neg_root_mean_squared_log_error': 0.0019085998411362, 'split0_test_neg_root_mean_squared_error': -47837.698295125076, 'split1_test_neg_root_mean_squared_error': -30846.31510592948, 'split2_test_neg_root_mean_squared_error': -113339.84484489063, 'split3_test_neg_root_mean_squared_error': -26322.23198275799, 'split4_test_neg_root_mean_squared_error': -31768.76563054471, 'mean_test_neg_root_mean_squared_error': -50022.971171849575, 'std_test_neg_root_mean_squared_error': 32485.341633412827, 'rank_test_neg_root_mean_squared_error': 36, 'split0_train_neg_root_mean_squared_error': -17499.526871097067, 'split1_train_neg_root_mean_squared_error': -18401.60223772178, 'split2_train_neg_root_mean_squared_error': -19079.92173947771, 'split3_train_neg_root_mean_squared_error': -18344.123790819474, 'split4_train_neg_root_mean_squared_error': -16873.18791890181, 'mean_train_neg_root_mean_squared_error': -18039.672511603567, 'std_train_neg_root_mean_squared_error': 769.187335065486, 'split0_test_neg_mean_absolute_error': -16732.106171980286, 'split1_test_neg_mean_absolute_error': -18226.326635230722, 'split2_test_neg_mean_absolute_error': -21057.734073246374, 'split3_test_neg_mean_absolute_error': -16289.326382792624, 'split4_test_neg_mean_absolute_error': -17905.72969810574, 'mean_test_neg_mean_absolute_error': -18042.244592271152, 'std_test_neg_mean_absolute_error': 1669.4241075403838, 'rank_test_neg_mean_absolute_error': 10, 'split0_train_neg_mean_absolute_error': -11537.328705031689, 'split1_train_neg_mean_absolute_error': -11441.898427479447, 'split2_train_neg_mean_absolute_error': -11867.673395391103, 'split3_train_neg_mean_absolute_error': -11937.52119686676, 'split4_train_neg_mean_absolute_error': -11030.948891728534, 'mean_train_neg_mean_absolute_error': -11563.074123299506, 'std_train_neg_mean_absolute_error': 326.03526353924724, 'split0_test_r2': 0.6721204499173439, 'split1_test_r2': 0.8574711254848822, 'split2_test_r2': -1.7726283443837554, 'split3_test_r2': 0.8963783669440872, 'split4_test_r2': 0.8857285341142986, 'mean_test_r2': 0.30781402641537137, 'std_test_r2': 1.0434055506972824, 'rank_test_r2': 36, 'split0_train_r2': 0.9545230290774585, 'split1_train_r2': 0.9502741532022493, 'split2_train_r2': 0.9501432445354171, 'split3_train_r2': 0.9505395519323891, 'split4_train_r2': 0.9545210305545822, 'mean_train_r2': 0.9520002018604192, 'std_train_r2': 0.0020630204633911237}
Logging parameters (RIDGE__alpha_0.1__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.1__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.1__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.1__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:01:55 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.1__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/c42e82e5a8b74cedb89079ea5aac08cf
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.13544697761535646, 'std_fit_time': 0.004736642013512237, 'mean_score_time': 0.06265821456909179, 'std_score_time': 0.005311117298353541, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 0.1, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 0.1, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.15411433845362313, 'split1_test_neg_root_mean_squared_log_error': -0.1395976830048343, 'split2_test_neg_root_mean_squared_log_error': -0.20355326111723535, 'split3_test_neg_root_mean_squared_log_error': -0.15300443164047814, 'split4_test_neg_root_mean_squared_log_error': -0.16654341447532253, 'mean_test_neg_root_mean_squared_log_error': -0.16336262573829868, 'std_test_neg_root_mean_squared_log_error': 0.021831170811228016, 'rank_test_neg_root_mean_squared_log_error': 15, 'split0_train_neg_root_mean_squared_log_error': -0.0890774621894478, 'split1_train_neg_root_mean_squared_log_error': -0.09039569831774594, 'split2_train_neg_root_mean_squared_log_error': -0.09136974336272712, 'split3_train_neg_root_mean_squared_log_error': -0.09252142632028341, 'split4_train_neg_root_mean_squared_log_error': -0.08700106732463198, 'mean_train_neg_root_mean_squared_log_error': -0.09007307950296725, 'std_train_neg_root_mean_squared_log_error': 0.001908315218277037, 'split0_test_neg_root_mean_squared_error': -47808.468559604735, 'split1_test_neg_root_mean_squared_error': -30837.580560967977, 'split2_test_neg_root_mean_squared_error': -113320.0861755293, 'split3_test_neg_root_mean_squared_error': -26321.934505442354, 'split4_test_neg_root_mean_squared_error': -31757.345417328303, 'mean_test_neg_root_mean_squared_error': -50009.08304377454, 'std_test_neg_root_mean_squared_error': 32480.39181219002, 'rank_test_neg_root_mean_squared_error': 35, 'split0_train_neg_root_mean_squared_error': -17501.098497493145, 'split1_train_neg_root_mean_squared_error': -18404.72495249597, 'split2_train_neg_root_mean_squared_error': -19079.619355423594, 'split3_train_neg_root_mean_squared_error': -18343.337694949034, 'split4_train_neg_root_mean_squared_error': -16872.210931657726, 'mean_train_neg_root_mean_squared_error': -18040.198286403895, 'std_train_neg_root_mean_squared_error': 769.4143738295928, 'split0_test_neg_mean_absolute_error': -16727.282346310123, 'split1_test_neg_mean_absolute_error': -18219.419810085878, 'split2_test_neg_mean_absolute_error': -21054.698618192306, 'split3_test_neg_mean_absolute_error': -16289.364619970876, 'split4_test_neg_mean_absolute_error': -17900.64556853252, 'mean_test_neg_mean_absolute_error': -18038.282192618342, 'std_test_neg_mean_absolute_error': 1669.0090474385836, 'rank_test_neg_mean_absolute_error': 9, 'split0_train_neg_mean_absolute_error': -11537.205816680098, 'split1_train_neg_mean_absolute_error': -11442.832514876522, 'split2_train_neg_mean_absolute_error': -11867.939481533756, 'split3_train_neg_mean_absolute_error': -11938.056390137335, 'split4_train_neg_mean_absolute_error': -11030.943564551531, 'mean_train_neg_mean_absolute_error': -11563.395553555849, 'std_train_neg_mean_absolute_error': 326.1423663813151, 'split0_test_r2': 0.672521008678393, 'split1_test_r2': 0.8575518319550043, 'split2_test_r2': -1.771661717482829, 'split3_test_r2': 0.896380709063941, 'split4_test_r2': 0.88581067579768, 'mean_test_r2': 0.3081205016024378, 'std_test_r2': 1.0430659235348283, 'rank_test_r2': 35, 'split0_train_r2': 0.9545148601689026, 'split1_train_r2': 0.9502572750185163, 'split2_train_r2': 0.9501448248111211, 'split3_train_r2': 0.9505437908724822, 'split4_train_r2': 0.9545262970266774, 'mean_train_r2': 0.9519974095795399, 'std_train_r2': 0.002064266220734453}
Logging parameters (RIDGE__alpha_0.1__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.1__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.1__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.1__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 19:04:23 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.1__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/a0504ac6635646a78fe2f6050ac13965
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.14615073204040527, 'std_fit_time': 0.01456139368710773, 'mean_score_time': 0.08857164382934571, 'std_score_time': 0.011144870347472097, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 1.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 1, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.13975303365688083, 'split1_test_neg_root_mean_squared_log_error': -0.135561202716664, 'split2_test_neg_root_mean_squared_log_error': -0.20149619530053753, 'split3_test_neg_root_mean_squared_log_error': -0.12521344356744285, 'split4_test_neg_root_mean_squared_log_error': -0.14700069562289822, 'mean_test_neg_root_mean_squared_log_error': -0.1498049141728847, 'std_test_neg_root_mean_squared_log_error': 0.026789984064155496, 'rank_test_neg_root_mean_squared_log_error': 12, 'split0_train_neg_root_mean_squared_log_error': -0.09823419854553064, 'split1_train_neg_root_mean_squared_log_error': -0.0981149039301816, 'split2_train_neg_root_mean_squared_log_error': -0.0935924604874642, 'split3_train_neg_root_mean_squared_log_error': -0.10068320757638748, 'split4_train_neg_root_mean_squared_log_error': -0.09672561799211957, 'mean_train_neg_root_mean_squared_log_error': -0.09747007770633669, 'std_train_neg_root_mean_squared_log_error': 0.0023200870949104404, 'split0_test_neg_root_mean_squared_error': -41045.03797968736, 'split1_test_neg_root_mean_squared_error': -34755.87833074683, 'split2_test_neg_root_mean_squared_error': -110665.425442486, 'split3_test_neg_root_mean_squared_error': -24233.370882242052, 'split4_test_neg_root_mean_squared_error': -31428.01702791734, 'mean_test_neg_root_mean_squared_error': -48425.54593261592, 'std_test_neg_root_mean_squared_error': 31588.95893797696, 'rank_test_neg_root_mean_squared_error': 28, 'split0_train_neg_root_mean_squared_error': -20459.70047652882, 'split1_train_neg_root_mean_squared_error': -20444.65821163361, 'split2_train_neg_root_mean_squared_error': -19796.192542114266, 'split3_train_neg_root_mean_squared_error': -21144.57478928158, 'split4_train_neg_root_mean_squared_error': -20402.37255640989, 'mean_train_neg_root_mean_squared_error': -20449.499715193633, 'std_train_neg_root_mean_squared_error': 427.1505790231095, 'split0_test_neg_mean_absolute_error': -16327.149896701392, 'split1_test_neg_mean_absolute_error': -18265.321544707644, 'split2_test_neg_mean_absolute_error': -20744.964451253938, 'split3_test_neg_mean_absolute_error': -15014.259818893168, 'split4_test_neg_mean_absolute_error': -19066.244869111903, 'mean_test_neg_mean_absolute_error': -17883.588116133607, 'std_test_neg_mean_absolute_error': 2019.2779276413019, 'rank_test_neg_mean_absolute_error': 6, 'split0_train_neg_mean_absolute_error': -12739.337670898052, 'split1_train_neg_mean_absolute_error': -12538.145022500326, 'split2_train_neg_mean_absolute_error': -12114.704333341582, 'split3_train_neg_mean_absolute_error': -13237.773569037176, 'split4_train_neg_mean_absolute_error': -12499.84211769197, 'mean_train_neg_mean_absolute_error': -12625.960542693821, 'std_train_neg_mean_absolute_error': 366.6523930690416, 'split0_test_r2': 0.758623434624853, 'split1_test_r2': 0.8190524068825097, 'split2_test_r2': -1.6433236828660847, 'split3_test_r2': 0.9121720661948927, 'split4_test_r2': 0.8881667163886783, 'mean_test_r2': 0.34693818824496975, 'std_test_r2': 0.9965878335183497, 'rank_test_r2': 26, 'split0_train_r2': 0.9378362136665143, 'split1_train_r2': 0.9386194721577582, 'split2_train_r2': 0.946329681468928, 'split3_train_r2': 0.9342853780882715, 'split4_train_r2': 0.9335067323599833, 'mean_train_r2': 0.9381154955482909, 'std_train_r2': 0.004554455818527988}
Logging parameters (RIDGE__alpha_1.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_1.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_1.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_1.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:06:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_1.0__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/15fe6867a2cf4829895813971fcdcb1b
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.1949138641357422, 'std_fit_time': 0.028691863651752, 'mean_score_time': 0.11437206268310547, 'std_score_time': 0.01876244703099714, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 1.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 1, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.1397414527705354, 'split1_test_neg_root_mean_squared_log_error': -0.13554783784735142, 'split2_test_neg_root_mean_squared_log_error': -0.20148671163540519, 'split3_test_neg_root_mean_squared_log_error': -0.12520025184917016, 'split4_test_neg_root_mean_squared_log_error': -0.14700918853452, 'mean_test_neg_root_mean_squared_log_error': -0.14979708852739643, 'std_test_neg_root_mean_squared_log_error': 0.026790859834693755, 'rank_test_neg_root_mean_squared_log_error': 11, 'split0_train_neg_root_mean_squared_log_error': -0.09824014834536768, 'split1_train_neg_root_mean_squared_log_error': -0.09811578062859437, 'split2_train_neg_root_mean_squared_log_error': -0.09359368850195728, 'split3_train_neg_root_mean_squared_log_error': -0.10068441876037365, 'split4_train_neg_root_mean_squared_log_error': -0.09672852752783856, 'mean_train_neg_root_mean_squared_log_error': -0.0974725127528263, 'std_train_neg_root_mean_squared_log_error': 0.002320266784159959, 'split0_test_neg_root_mean_squared_error': -41042.150397584504, 'split1_test_neg_root_mean_squared_error': -34746.99491255538, 'split2_test_neg_root_mean_squared_error': -110635.726203538, 'split3_test_neg_root_mean_squared_error': -24238.616946431273, 'split4_test_neg_root_mean_squared_error': -31429.110651835403, 'mean_test_neg_root_mean_squared_error': -48418.51982238891, 'std_test_neg_root_mean_squared_error': 31577.238372540178, 'rank_test_neg_root_mean_squared_error': 27, 'split0_train_neg_root_mean_squared_error': -20458.276866896776, 'split1_train_neg_root_mean_squared_error': -20447.90310095515, 'split2_train_neg_root_mean_squared_error': -19795.08645253071, 'split3_train_neg_root_mean_squared_error': -21143.319259013955, 'split4_train_neg_root_mean_squared_error': -20399.71681887432, 'mean_train_neg_root_mean_squared_error': -20448.860499654184, 'std_train_neg_root_mean_squared_error': 427.1295258088877, 'split0_test_neg_mean_absolute_error': -16322.837996094417, 'split1_test_neg_mean_absolute_error': -18265.381182463716, 'split2_test_neg_mean_absolute_error': -20742.461718812967, 'split3_test_neg_mean_absolute_error': -15015.016969903068, 'split4_test_neg_mean_absolute_error': -19068.831780899804, 'mean_test_neg_mean_absolute_error': -17882.905929634795, 'std_test_neg_mean_absolute_error': 2019.3249266900882, 'rank_test_neg_mean_absolute_error': 5, 'split0_train_neg_mean_absolute_error': -12739.070860009366, 'split1_train_neg_mean_absolute_error': -12537.808358942157, 'split2_train_neg_mean_absolute_error': -12114.790185834603, 'split3_train_neg_mean_absolute_error': -13236.69847650283, 'split4_train_neg_mean_absolute_error': -12501.223967252641, 'mean_train_neg_mean_absolute_error': -12625.918369708319, 'std_train_neg_mean_absolute_error': 366.17479794990743, 'split0_test_r2': 0.7586573958619334, 'split1_test_r2': 0.819144893551925, 'split2_test_r2': -1.641905097662589, 'split3_test_r2': 0.9121340359222986, 'split4_test_r2': 0.8881589331625442, 'mean_test_r2': 0.34723803216722243, 'std_test_r2': 0.9960276387516669, 'rank_test_r2': 25, 'split0_train_r2': 0.9378448642219053, 'split1_train_r2': 0.9385999864981565, 'split2_train_r2': 0.9463356788365223, 'split3_train_r2': 0.9342931819101126, 'split4_train_r2': 0.9335240418344715, 'mean_train_r2': 0.9381195506602337, 'std_train_r2': 0.004551281855093726}
Logging parameters (RIDGE__alpha_1.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_1.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_1.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_1.0__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 19:09:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_1.0__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/437e3d7c6d254979bd829a33d03e9db9
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.2307511806488037, 'std_fit_time': 0.018815469791669443, 'mean_score_time': 0.15867671966552735, 'std_score_time': 0.04576200498854819, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 5.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 5, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.13507056844103543, 'split1_test_neg_root_mean_squared_log_error': -0.13378480246669527, 'split2_test_neg_root_mean_squared_log_error': -0.20177894119572573, 'split3_test_neg_root_mean_squared_log_error': -0.11631396501694187, 'split4_test_neg_root_mean_squared_log_error': -0.1404241437953152, 'mean_test_neg_root_mean_squared_log_error': -0.1454744841831427, 'std_test_neg_root_mean_squared_log_error': 0.029294790721074663, 'rank_test_neg_root_mean_squared_log_error': 3, 'split0_train_neg_root_mean_squared_log_error': -0.1076276003829712, 'split1_train_neg_root_mean_squared_log_error': -0.10781023925249246, 'split2_train_neg_root_mean_squared_log_error': -0.09869834930012882, 'split3_train_neg_root_mean_squared_log_error': -0.11074092958527895, 'split4_train_neg_root_mean_squared_log_error': -0.10694764048419592, 'mean_train_neg_root_mean_squared_log_error': -0.10636495180101346, 'std_train_neg_root_mean_squared_log_error': 0.0040484228740433545, 'split0_test_neg_root_mean_squared_error': -39409.53408618256, 'split1_test_neg_root_mean_squared_error': -33735.77174760087, 'split2_test_neg_root_mean_squared_error': -110201.71839462526, 'split3_test_neg_root_mean_squared_error': -24180.272191459502, 'split4_test_neg_root_mean_squared_error': -31252.408556467748, 'mean_test_neg_root_mean_squared_error': -47755.940995267185, 'std_test_neg_root_mean_squared_error': 31603.422319555015, 'rank_test_neg_root_mean_squared_error': 23, 'split0_train_neg_root_mean_squared_error': -23387.215416401927, 'split1_train_neg_root_mean_squared_error': -23183.933774551475, 'split2_train_neg_root_mean_squared_error': -21724.85162084626, 'split3_train_neg_root_mean_squared_error': -24355.78166054649, 'split4_train_neg_root_mean_squared_error': -23596.59242803581, 'mean_train_neg_root_mean_squared_error': -23249.67498007639, 'std_train_neg_root_mean_squared_error': 859.3194119606055, 'split0_test_neg_mean_absolute_error': -15975.466710983728, 'split1_test_neg_mean_absolute_error': -17538.45036340664, 'split2_test_neg_mean_absolute_error': -20906.124827251806, 'split3_test_neg_mean_absolute_error': -14972.780140488656, 'split4_test_neg_mean_absolute_error': -19231.653637307198, 'mean_test_neg_mean_absolute_error': -17724.895135887607, 'std_test_neg_mean_absolute_error': 2147.5540480166865, 'rank_test_neg_mean_absolute_error': 1, 'split0_train_neg_mean_absolute_error': -13661.804522786779, 'split1_train_neg_mean_absolute_error': -13674.022083902993, 'split2_train_neg_mean_absolute_error': -12636.902772433225, 'split3_train_neg_mean_absolute_error': -14259.355435716818, 'split4_train_neg_mean_absolute_error': -13574.226417473166, 'mean_train_neg_mean_absolute_error': -13561.262246462595, 'std_train_neg_mean_absolute_error': 522.4492584182719, 'split0_test_r2': 0.7774762446421348, 'split1_test_r2': 0.8295183761155404, 'split2_test_r2': -1.6212181370356156, 'split3_test_r2': 0.9125565309959224, 'split4_test_r2': 0.8894129932055187, 'mean_test_r2': 0.35754920158470016, 'std_test_r2': 0.990507549908254, 'rank_test_r2': 24, 'split0_train_r2': 0.9187738352156672, 'split1_train_r2': 0.9210694434871638, 'split2_train_r2': 0.9353625116849009, 'split3_train_r2': 0.9128096851962187, 'split4_train_r2': 0.9110563575530227, 'mean_train_r2': 0.9198143666273946, 'std_train_r2': 0.0086043131413381}
Logging parameters (RIDGE__alpha_5.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_5.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_5.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_5.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:11:47 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_5.0__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/7471be00a52c4e46a88323c2a0a15f79
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.4254473686218262, 'std_fit_time': 0.13026818454061923, 'mean_score_time': 0.22289867401123048, 'std_score_time': 0.048077630747777246, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 5.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 5, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.13506839469386123, 'split1_test_neg_root_mean_squared_log_error': -0.13378657911515518, 'split2_test_neg_root_mean_squared_log_error': -0.20176649063507907, 'split3_test_neg_root_mean_squared_log_error': -0.11631551156986748, 'split4_test_neg_root_mean_squared_log_error': -0.14044922033661789, 'mean_test_neg_root_mean_squared_log_error': -0.1454772392701162, 'std_test_neg_root_mean_squared_log_error': 0.029288846806791384, 'rank_test_neg_root_mean_squared_log_error': 4, 'split0_train_neg_root_mean_squared_log_error': -0.1076321964922866, 'split1_train_neg_root_mean_squared_log_error': -0.10780603798446685, 'split2_train_neg_root_mean_squared_log_error': -0.09870027084840147, 'split3_train_neg_root_mean_squared_log_error': -0.11073676082710564, 'split4_train_neg_root_mean_squared_log_error': -0.10694466060146537, 'mean_train_neg_root_mean_squared_log_error': -0.10636398535074518, 'std_train_neg_root_mean_squared_log_error': 0.004046696044549062, 'split0_test_neg_root_mean_squared_error': -39415.45166729697, 'split1_test_neg_root_mean_squared_error': -33728.59680321461, 'split2_test_neg_root_mean_squared_error': -110169.60247159225, 'split3_test_neg_root_mean_squared_error': -24189.2785958295, 'split4_test_neg_root_mean_squared_error': -31281.25806458741, 'mean_test_neg_root_mean_squared_error': -47756.83752050415, 'std_test_neg_root_mean_squared_error': 31586.69984816494, 'rank_test_neg_root_mean_squared_error': 24, 'split0_train_neg_root_mean_squared_error': -23385.82367242175, 'split1_train_neg_root_mean_squared_error': -23186.539579707463, 'split2_train_neg_root_mean_squared_error': -21723.544971278337, 'split3_train_neg_root_mean_squared_error': -24352.909829894583, 'split4_train_neg_root_mean_squared_error': -23591.610169582396, 'mean_train_neg_root_mean_squared_error': -23248.085644576902, 'std_train_neg_root_mean_squared_error': 858.5603679066801, 'split0_test_neg_mean_absolute_error': -15969.67396914771, 'split1_test_neg_mean_absolute_error': -17541.93991087101, 'split2_test_neg_mean_absolute_error': -20902.970260230664, 'split3_test_neg_mean_absolute_error': -14975.679700824878, 'split4_test_neg_mean_absolute_error': -19249.062776099297, 'mean_test_neg_mean_absolute_error': -17727.86532343471, 'std_test_neg_mean_absolute_error': 2149.216780517316, 'rank_test_neg_mean_absolute_error': 2, 'split0_train_neg_mean_absolute_error': -13662.162455134236, 'split1_train_neg_mean_absolute_error': -13673.406992720245, 'split2_train_neg_mean_absolute_error': -12637.717315830056, 'split3_train_neg_mean_absolute_error': -14257.266759887387, 'split4_train_neg_mean_absolute_error': -13576.527855681226, 'mean_train_neg_mean_absolute_error': -13561.416275850632, 'std_train_neg_mean_absolute_error': 521.6028638777725, 'split0_test_r2': 0.7774094130357385, 'split1_test_r2': 0.8295908846743691, 'split2_test_r2': -1.6196905642440482, 'split3_test_r2': 0.9124913788831271, 'split4_test_r2': 0.8892087303381733, 'mean_test_r2': 0.357801968537472, 'std_test_r2': 0.9898692231311956, 'rank_test_r2': 23, 'split0_train_r2': 0.9187835022632609, 'split1_train_r2': 0.9210516993707508, 'split2_train_r2': 0.9353702867443358, 'split3_train_r2': 0.9128302454935476, 'split4_train_r2': 0.9110939132664422, 'mean_train_r2': 0.9198259294276674, 'std_train_r2': 0.008595393076302214}
Logging parameters (RIDGE__alpha_5.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_5.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_5.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_5.0__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 19:14:15 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_5.0__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/22c1013f629c4246abc2892782a37c3a
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 1.0906627178192139, 'std_fit_time': 0.3952394949315228, 'mean_score_time': 0.3171504020690918, 'std_score_time': 0.14157829845592956, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 10.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 10, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.13462582653145944, 'split1_test_neg_root_mean_squared_log_error': -0.13420319865249666, 'split2_test_neg_root_mean_squared_log_error': -0.20283840946187548, 'split3_test_neg_root_mean_squared_log_error': -0.11516209106209342, 'split4_test_neg_root_mean_squared_log_error': -0.13893080627467863, 'mean_test_neg_root_mean_squared_log_error': -0.14515206639652073, 'std_test_neg_root_mean_squared_log_error': 0.0299883187421033, 'rank_test_neg_root_mean_squared_log_error': 1, 'split0_train_neg_root_mean_squared_log_error': -0.11187806536414407, 'split1_train_neg_root_mean_squared_log_error': -0.11215583526674922, 'split2_train_neg_root_mean_squared_log_error': -0.10178930176582592, 'split3_train_neg_root_mean_squared_log_error': -0.11528308959377025, 'split4_train_neg_root_mean_squared_log_error': -0.11145828683928523, 'mean_train_neg_root_mean_squared_log_error': -0.11051291576595494, 'std_train_neg_root_mean_squared_log_error': 0.004567549538836705, 'split0_test_neg_root_mean_squared_error': -39494.90639267139, 'split1_test_neg_root_mean_squared_error': -33308.510411465366, 'split2_test_neg_root_mean_squared_error': -111501.85701347367, 'split3_test_neg_root_mean_squared_error': -24411.198479630166, 'split4_test_neg_root_mean_squared_error': -31286.26596016438, 'mean_test_neg_root_mean_squared_error': -48000.54765148099, 'std_test_neg_root_mean_squared_error': 32113.681785124696, 'rank_test_neg_root_mean_squared_error': 25, 'split0_train_neg_root_mean_squared_error': -24713.877863260586, 'split1_train_neg_root_mean_squared_error': -24532.60184283468, 'split2_train_neg_root_mean_squared_error': -22994.205197371477, 'split3_train_neg_root_mean_squared_error': -25850.02540184981, 'split4_train_neg_root_mean_squared_error': -24998.91651012385, 'mean_train_neg_root_mean_squared_error': -24617.92536308808, 'std_train_neg_root_mean_squared_error': 929.1048295632551, 'split0_test_neg_mean_absolute_error': -15985.569721414842, 'split1_test_neg_mean_absolute_error': -17333.297927635587, 'split2_test_neg_mean_absolute_error': -21189.655610862475, 'split3_test_neg_mean_absolute_error': -15224.235998458169, 'split4_test_neg_mean_absolute_error': -19129.918299399684, 'mean_test_neg_mean_absolute_error': -17772.535511554153, 'std_test_neg_mean_absolute_error': 2163.293997797631, 'rank_test_neg_mean_absolute_error': 3, 'split0_train_neg_mean_absolute_error': -14041.526682335785, 'split1_train_neg_mean_absolute_error': -14167.040801533567, 'split2_train_neg_mean_absolute_error': -12954.731083716588, 'split3_train_neg_mean_absolute_error': -14671.635092081528, 'split4_train_neg_mean_absolute_error': -14015.639713298011, 'mean_train_neg_mean_absolute_error': -13970.114674593095, 'std_train_neg_mean_absolute_error': 560.1940442819998, 'split0_test_r2': 0.7765111003670259, 'split1_test_r2': 0.8338093079330189, 'split2_test_r2': -1.6834322318538626, 'split3_test_r2': 0.9108783514391674, 'split4_test_r2': 0.8891732537905026, 'mean_test_r2': 0.3453879563351704, 'std_test_r2': 1.0154817354047707, 'rank_test_r2': 28, 'split0_train_r2': 0.9092971970355042, 'split1_train_r2': 0.9116191588432944, 'split2_train_r2': 0.9275884840417111, 'split3_train_r2': 0.9017831390412694, 'split4_train_r2': 0.9001705449090299, 'mean_train_r2': 0.9100917047741618, 'std_train_r2': 0.009762820502546772}
Logging parameters (RIDGE__alpha_10.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_10.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_10.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_10.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:16:43 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_10.0__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/bc012f35d6024637af2cbb79c8f89f3a
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.5495861530303955, 'std_fit_time': 0.17346610140948412, 'mean_score_time': 0.251497745513916, 'std_score_time': 0.07477487889264735, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 10.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 10, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.13462830549536567, 'split1_test_neg_root_mean_squared_log_error': -0.13420640763507885, 'split2_test_neg_root_mean_squared_log_error': -0.20282568937861958, 'split3_test_neg_root_mean_squared_log_error': -0.11516477623643824, 'split4_test_neg_root_mean_squared_log_error': -0.13896796155730542, 'mean_test_neg_root_mean_squared_log_error': -0.14515862806056154, 'std_test_neg_root_mean_squared_log_error': 0.0299809415650613, 'rank_test_neg_root_mean_squared_log_error': 2, 'split0_train_neg_root_mean_squared_log_error': -0.11188125353544487, 'split1_train_neg_root_mean_squared_log_error': -0.11214998832952149, 'split2_train_neg_root_mean_squared_log_error': -0.10179088855146927, 'split3_train_neg_root_mean_squared_log_error': -0.11527664578972849, 'split4_train_neg_root_mean_squared_log_error': -0.11145249518741128, 'mean_train_neg_root_mean_squared_log_error': -0.11051025427871508, 'std_train_neg_root_mean_squared_log_error': 0.0045651289438761265, 'split0_test_neg_root_mean_squared_error': -39503.655979232375, 'split1_test_neg_root_mean_squared_error': -33301.31164414704, 'split2_test_neg_root_mean_squared_error': -111471.09788187621, 'split3_test_neg_root_mean_squared_error': -24419.056312306682, 'split4_test_neg_root_mean_squared_error': -31328.20589761938, 'mean_test_neg_root_mean_squared_error': -48004.66554303634, 'std_test_neg_root_mean_squared_error': 32096.196292988705, 'rank_test_neg_root_mean_squared_error': 26, 'split0_train_neg_root_mean_squared_error': -24712.6028471868, 'split1_train_neg_root_mean_squared_error': -24535.231909157555, 'split2_train_neg_root_mean_squared_error': -22993.038499098035, 'split3_train_neg_root_mean_squared_error': -25846.858059350856, 'split4_train_neg_root_mean_squared_error': -24992.829426775796, 'mean_train_neg_root_mean_squared_error': -24616.112148313805, 'std_train_neg_root_mean_squared_error': 928.1025314327935, 'split0_test_neg_mean_absolute_error': -15984.695442517861, 'split1_test_neg_mean_absolute_error': -17332.74600277665, 'split2_test_neg_mean_absolute_error': -21186.68501014418, 'split3_test_neg_mean_absolute_error': -15227.472662000113, 'split4_test_neg_mean_absolute_error': -19151.303634255237, 'mean_test_neg_mean_absolute_error': -17776.580550338807, 'std_test_neg_mean_absolute_error': 2164.4615199105733, 'rank_test_neg_mean_absolute_error': 4, 'split0_train_neg_mean_absolute_error': -14041.817726638536, 'split1_train_neg_mean_absolute_error': -14166.949147265537, 'split2_train_neg_mean_absolute_error': -12955.48617821476, 'split3_train_neg_mean_absolute_error': -14670.578181984554, 'split4_train_neg_mean_absolute_error': -14016.820998936446, 'mean_train_neg_mean_absolute_error': -13970.330446607966, 'std_train_neg_mean_absolute_error': 559.6760663278053, 'split0_test_r2': 0.7764120672383458, 'split1_test_r2': 0.8338811357527547, 'split2_test_r2': -1.6819519217939294, 'split3_test_r2': 0.9108209666520416, 'split4_test_r2': 0.8888759231835898, 'mean_test_r2': 0.3456076342065605, 'std_test_r2': 1.0148505081974466, 'rank_test_r2': 27, 'split0_train_r2': 0.9093065557083247, 'split1_train_r2': 0.9116002077401542, 'split2_train_r2': 0.9275958320014822, 'split3_train_r2': 0.9018072061262837, 'split4_train_r2': 0.9002191547142983, 'mean_train_r2': 0.9101057912581088, 'std_train_r2': 0.009750750541679011}
Logging parameters (RIDGE__alpha_10.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_10.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_10.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_10.0__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 19:19:11 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_10.0__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/d3608e4e28634387b8fd75f8159ddc19
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.7084620475769043, 'std_fit_time': 0.38399018050128003, 'mean_score_time': 0.22264671325683594, 'std_score_time': 0.03406771017418128, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 25.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 25, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.13497732080718675, 'split1_test_neg_root_mean_squared_log_error': -0.13530186117345, 'split2_test_neg_root_mean_squared_log_error': -0.20466028156695, 'split3_test_neg_root_mean_squared_log_error': -0.11553751516902973, 'split4_test_neg_root_mean_squared_log_error': -0.1378640536229536, 'mean_test_neg_root_mean_squared_log_error': -0.145668206467914, 'std_test_neg_root_mean_squared_log_error': 0.03056332585057217, 'rank_test_neg_root_mean_squared_log_error': 5, 'split0_train_neg_root_mean_squared_log_error': -0.11788720544818623, 'split1_train_neg_root_mean_squared_log_error': -0.11820264642986486, 'split2_train_neg_root_mean_squared_log_error': -0.10653589144747115, 'split3_train_neg_root_mean_squared_log_error': -0.12164351530718288, 'split4_train_neg_root_mean_squared_log_error': -0.1178090503966878, 'mean_train_neg_root_mean_squared_log_error': -0.11641566180587859, 'std_train_neg_root_mean_squared_log_error': 0.005142773591527095, 'split0_test_neg_root_mean_squared_error': -40033.91712833465, 'split1_test_neg_root_mean_squared_error': -33164.11663695277, 'split2_test_neg_root_mean_squared_error': -113606.04283165881, 'split3_test_neg_root_mean_squared_error': -25004.82082800493, 'split4_test_neg_root_mean_squared_error': -31472.684654362318, 'mean_test_neg_root_mean_squared_error': -48656.31641586269, 'std_test_neg_root_mean_squared_error': 32825.269013390534, 'rank_test_neg_root_mean_squared_error': 29, 'split0_train_neg_root_mean_squared_error': -26815.36255261715, 'split1_train_neg_root_mean_squared_error': -26625.565962284934, 'split2_train_neg_root_mean_squared_error': -24976.858562656394, 'split3_train_neg_root_mean_squared_error': -28168.276102558644, 'split4_train_neg_root_mean_squared_error': -27089.99274652115, 'mean_train_neg_root_mean_squared_error': -26735.211185327662, 'std_train_neg_root_mean_squared_error': 1028.5713660636795, 'split0_test_neg_mean_absolute_error': -16291.62981537468, 'split1_test_neg_mean_absolute_error': -17180.86867033728, 'split2_test_neg_mean_absolute_error': -21639.733698555625, 'split3_test_neg_mean_absolute_error': -15718.415881761124, 'split4_test_neg_mean_absolute_error': -19045.616687973386, 'mean_test_neg_mean_absolute_error': -17975.25295080042, 'std_test_neg_mean_absolute_error': 2150.955345138576, 'rank_test_neg_mean_absolute_error': 7, 'split0_train_neg_mean_absolute_error': -14615.176437954404, 'split1_train_neg_mean_absolute_error': -14895.646685155081, 'split2_train_neg_mean_absolute_error': -13462.263505847586, 'split3_train_neg_mean_absolute_error': -15261.762735629009, 'split4_train_neg_mean_absolute_error': -14722.46381562597, 'mean_train_neg_mean_absolute_error': -14591.46263604241, 'std_train_neg_mean_absolute_error': 605.7465622397764, 'split0_test_r2': 0.770369299197856, 'split1_test_r2': 0.8352470718701768, 'split2_test_r2': -1.7856676215034533, 'split3_test_r2': 0.9064911961366231, 'split4_test_r2': 0.8878486004107724, 'mean_test_r2': 0.322857709222395, 'std_test_r2': 1.0553228232728609, 'rank_test_r2': 30, 'split0_train_r2': 0.8932159809761336, 'split1_train_r2': 0.8958957149604773, 'split2_train_r2': 0.9145629069083685, 'split3_train_r2': 0.8833768844107198, 'split4_train_r2': 0.88277125764883, 'mean_train_r2': 0.8939645489809059, 'std_train_r2': 0.011540974978759657}
Logging parameters (RIDGE__alpha_25.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_25.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_25.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_25.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:21:40 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_25.0__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/232a83225a6f4c8ca4e4d2cc085e9c41
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.6990710258483886, 'std_fit_time': 0.21701581229054817, 'mean_score_time': 0.312988805770874, 'std_score_time': 0.07765882306918268, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 25.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 25, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.13498632686730977, 'split1_test_neg_root_mean_squared_log_error': -0.13530316163744724, 'split2_test_neg_root_mean_squared_log_error': -0.20464827640262287, 'split3_test_neg_root_mean_squared_log_error': -0.11553504899678577, 'split4_test_neg_root_mean_squared_log_error': -0.13791912407360263, 'mean_test_neg_root_mean_squared_log_error': -0.14567838759555365, 'std_test_neg_root_mean_squared_log_error': 0.03055565510506812, 'rank_test_neg_root_mean_squared_log_error': 6, 'split0_train_neg_root_mean_squared_log_error': -0.11788775706163568, 'split1_train_neg_root_mean_squared_log_error': -0.11819607490974475, 'split2_train_neg_root_mean_squared_log_error': -0.10653681443701943, 'split3_train_neg_root_mean_squared_log_error': -0.12163627940243509, 'split4_train_neg_root_mean_squared_log_error': -0.11780011060477161, 'mean_train_neg_root_mean_squared_log_error': -0.11641140728312131, 'std_train_neg_root_mean_squared_log_error': 0.005140039234501398, 'split0_test_neg_root_mean_squared_error': -40045.30578740037, 'split1_test_neg_root_mean_squared_error': -33156.43646145465, 'split2_test_neg_root_mean_squared_error': -113578.5713203554, 'split3_test_neg_root_mean_squared_error': -25009.52394635965, 'split4_test_neg_root_mean_squared_error': -31530.869062329, 'mean_test_neg_root_mean_squared_error': -48664.14131557981, 'std_test_neg_root_mean_squared_error': 32807.76249468287, 'rank_test_neg_root_mean_squared_error': 30, 'split0_train_neg_root_mean_squared_error': -26814.15489618997, 'split1_train_neg_root_mean_squared_error': -26628.89733512047, 'split2_train_neg_root_mean_squared_error': -24976.301242999834, 'split3_train_neg_root_mean_squared_error': -28165.85264807964, 'split4_train_neg_root_mean_squared_error': -27082.43633244131, 'mean_train_neg_root_mean_squared_error': -26733.528490966244, 'std_train_neg_root_mean_squared_error': 1027.480906867073, 'split0_test_neg_mean_absolute_error': -16296.292929549283, 'split1_test_neg_mean_absolute_error': -17177.950180205393, 'split2_test_neg_mean_absolute_error': -21637.291370908133, 'split3_test_neg_mean_absolute_error': -15721.20745809459, 'split4_test_neg_mean_absolute_error': -19072.128361517964, 'mean_test_neg_mean_absolute_error': -17980.974060055072, 'std_test_neg_mean_absolute_error': 2151.6884972352223, 'rank_test_neg_mean_absolute_error': 8, 'split0_train_neg_mean_absolute_error': -14614.949655586279, 'split1_train_neg_mean_absolute_error': -14895.61399960865, 'split2_train_neg_mean_absolute_error': -13462.876766852656, 'split3_train_neg_mean_absolute_error': -15261.014761140632, 'split4_train_neg_mean_absolute_error': -14725.775280828388, 'mean_train_neg_mean_absolute_error': -14592.046092803319, 'std_train_neg_mean_absolute_error': 605.4921946392107, 'split0_test_r2': 0.7702386321071538, 'split1_test_r2': 0.8353233702925007, 'split2_test_r2': -1.7843205585293043, 'split3_test_r2': 0.9064560169738645, 'split4_test_r2': 0.8874335424162151, 'mean_test_r2': 0.323026200652086, 'std_test_r2': 1.0547325452750906, 'rank_test_r2': 29, 'split0_train_r2': 0.8932255990077942, 'split1_train_r2': 0.8958696624150356, 'split2_train_r2': 0.9145667196568792, 'split3_train_r2': 0.8833969508608459, 'split4_train_r2': 0.8828366475056758, 'mean_train_r2': 0.8939791158892462, 'std_train_r2': 0.011525000660451415}
Logging parameters (RIDGE__alpha_25.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_25.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_25.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_25.0__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 19:24:07 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_25.0__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/93992e1764db4289b506c55ce1efa26b
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.9849287986755371, 'std_fit_time': 0.4282217723059137, 'mean_score_time': 0.6139196872711181, 'std_score_time': 0.16419185462575633, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 50.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 50, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.13568363394807972, 'split1_test_neg_root_mean_squared_log_error': -0.13661086707213588, 'split2_test_neg_root_mean_squared_log_error': -0.20620725473509255, 'split3_test_neg_root_mean_squared_log_error': -0.11719063853979227, 'split4_test_neg_root_mean_squared_log_error': -0.13781419166069206, 'mean_test_neg_root_mean_squared_log_error': -0.14670131719115848, 'std_test_neg_root_mean_squared_log_error': 0.030705127536912638, 'rank_test_neg_root_mean_squared_log_error': 7, 'split0_train_neg_root_mean_squared_log_error': -0.1228103648076828, 'split1_train_neg_root_mean_squared_log_error': -0.1232738407572416, 'split2_train_neg_root_mean_squared_log_error': -0.11061007654700682, 'split3_train_neg_root_mean_squared_log_error': -0.1267925375936507, 'split4_train_neg_root_mean_squared_log_error': -0.12302522611188435, 'mean_train_neg_root_mean_squared_log_error': -0.12130240916349326, 'std_train_neg_root_mean_squared_log_error': 0.005542491460571474, 'split0_test_neg_root_mean_squared_error': -40602.2564570863, 'split1_test_neg_root_mean_squared_error': -33316.71506723618, 'split2_test_neg_root_mean_squared_error': -114640.66228749127, 'split3_test_neg_root_mean_squared_error': -25676.15388372663, 'split4_test_neg_root_mean_squared_error': -31806.08254200938, 'mean_test_neg_root_mean_squared_error': -49208.37404750996, 'std_test_neg_root_mean_squared_error': 33059.339270241624, 'rank_test_neg_root_mean_squared_error': 31, 'split0_train_neg_root_mean_squared_error': -28813.10060222228, 'split1_train_neg_root_mean_squared_error': -28508.413585179824, 'split2_train_neg_root_mean_squared_error': -26551.510427461963, 'split3_train_neg_root_mean_squared_error': -30256.25479422264, 'split4_train_neg_root_mean_squared_error': -28904.025468873773, 'mean_train_neg_root_mean_squared_error': -28606.660975592094, 'std_train_neg_root_mean_squared_error': 1190.4200143625267, 'split0_test_neg_mean_absolute_error': -16653.36484983636, 'split1_test_neg_mean_absolute_error': -17131.840027442704, 'split2_test_neg_mean_absolute_error': -22060.309048404717, 'split3_test_neg_mean_absolute_error': -16194.211440047267, 'split4_test_neg_mean_absolute_error': -19134.282392286907, 'mean_test_neg_mean_absolute_error': -18234.80155160359, 'std_test_neg_mean_absolute_error': 2159.863308623727, 'rank_test_neg_mean_absolute_error': 15, 'split0_train_neg_mean_absolute_error': -15128.929073154477, 'split1_train_neg_mean_absolute_error': -15586.448471961196, 'split2_train_neg_mean_absolute_error': -13983.738341852253, 'split3_train_neg_mean_absolute_error': -15838.673779100318, 'split4_train_neg_mean_absolute_error': -15377.894063853624, 'mean_train_neg_mean_absolute_error': -15183.136745984375, 'std_train_neg_mean_absolute_error': 643.7102712538915, 'split0_test_r2': 0.7638031401122014, 'split1_test_r2': 0.8337274246341705, 'split2_test_r2': -1.8366372641884143, 'split3_test_r2': 0.9014027169972655, 'split4_test_r2': 0.8854599204254705, 'mean_test_r2': 0.3095511875961387, 'std_test_r2': 1.0741684724303653, 'rank_test_r2': 34, 'split0_train_r2': 0.8767125394278078, 'split1_train_r2': 0.880651487336187, 'split2_train_r2': 0.9034506625660502, 'split3_train_r2': 0.8654466735163253, 'split4_train_r2': 0.8665455711956614, 'mean_train_r2': 0.8785613868084065, 'std_train_r2': 0.013737818852830935}
Logging parameters (RIDGE__alpha_50.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_50.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_50.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_50.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:26:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_50.0__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/cee56ff1a83a4525b71d33c6385bd8e0
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 1.0125177383422852, 'std_fit_time': 0.48743744042194326, 'mean_score_time': 0.26726880073547366, 'std_score_time': 0.13546243198332386, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 50.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 50, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.13569588341621844, 'split1_test_neg_root_mean_squared_log_error': -0.13660877094840224, 'split2_test_neg_root_mean_squared_log_error': -0.206196190315845, 'split3_test_neg_root_mean_squared_log_error': -0.1171831864577294, 'split4_test_neg_root_mean_squared_log_error': -0.13787900210715612, 'mean_test_neg_root_mean_squared_log_error': -0.14671260664907024, 'std_test_neg_root_mean_squared_log_error': 0.030697790274015604, 'rank_test_neg_root_mean_squared_log_error': 8, 'split0_train_neg_root_mean_squared_log_error': -0.122809088312666, 'split1_train_neg_root_mean_squared_log_error': -0.12326759388270297, 'split2_train_neg_root_mean_squared_log_error': -0.11061041360243808, 'split3_train_neg_root_mean_squared_log_error': -0.12678632626055755, 'split4_train_neg_root_mean_squared_log_error': -0.1230140140102287, 'mean_train_neg_root_mean_squared_log_error': -0.12129748721371866, 'std_train_neg_root_mean_squared_log_error': 0.0055399209176248245, 'split0_test_neg_root_mean_squared_error': -40614.123800825684, 'split1_test_neg_root_mean_squared_error': -33308.51152993063, 'split2_test_neg_root_mean_squared_error': -114616.33360807147, 'split3_test_neg_root_mean_squared_error': -25678.462262246492, 'split4_test_neg_root_mean_squared_error': -31872.68538810558, 'mean_test_neg_root_mean_squared_error': -49218.02331783597, 'std_test_neg_root_mean_squared_error': 33042.54930731768, 'rank_test_neg_root_mean_squared_error': 32, 'split0_train_neg_root_mean_squared_error': -28811.947401815454, 'split1_train_neg_root_mean_squared_error': -28512.35375869722, 'split2_train_neg_root_mean_squared_error': -26551.749975570532, 'split3_train_neg_root_mean_squared_error': -30255.049209309214, 'split4_train_neg_root_mean_squared_error': -28895.372839586395, 'mean_train_neg_root_mean_squared_error': -28605.294636995764, 'std_train_neg_root_mean_squared_error': 1189.472535287969, 'split0_test_neg_mean_absolute_error': -16658.43213489769, 'split1_test_neg_mean_absolute_error': -17125.976496649313, 'split2_test_neg_mean_absolute_error': -22058.25810290414, 'split3_test_neg_mean_absolute_error': -16196.448982503633, 'split4_test_neg_mean_absolute_error': -19159.07007568124, 'mean_test_neg_mean_absolute_error': -18239.637158527206, 'std_test_neg_mean_absolute_error': 2160.661478584215, 'rank_test_neg_mean_absolute_error': 16, 'split0_train_neg_mean_absolute_error': -15127.572086469538, 'split1_train_neg_mean_absolute_error': -15587.10201531374, 'split2_train_neg_mean_absolute_error': -13984.048887880042, 'split3_train_neg_mean_absolute_error': -15837.847737591526, 'split4_train_neg_mean_absolute_error': -15380.86460405567, 'mean_train_neg_mean_absolute_error': -15183.487066262105, 'std_train_neg_mean_absolute_error': 643.7125502010628, 'split0_test_r2': 0.7636650473454543, 'split1_test_r2': 0.8338092967719963, 'split2_test_r2': -1.835433427529801, 'split3_test_r2': 0.9013849877000932, 'split4_test_r2': 0.8849797177702283, 'mean_test_r2': 0.30968112441159423, 'std_test_r2': 1.0736303011415023, 'rank_test_r2': 33, 'split0_train_r2': 0.8767224080154672, 'split1_train_r2': 0.8806184945255111, 'split2_train_r2': 0.9034489204191724, 'split3_train_r2': 0.8654573960746696, 'split4_train_r2': 0.8666254603351032, 'mean_train_r2': 0.8785745358739847, 'std_train_r2': 0.013719933774067473}
Logging parameters (RIDGE__alpha_50.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_50.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_50.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_50.0__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 19:29:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_50.0__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/770058dd784a4f87a7f06a377d36fdae
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.5341654777526855, 'std_fit_time': 0.16234691599902326, 'mean_score_time': 0.3684493064880371, 'std_score_time': 0.19335939166382957, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 100.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 100, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.1369405863065534, 'split1_test_neg_root_mean_squared_log_error': -0.13869891543169643, 'split2_test_neg_root_mean_squared_log_error': -0.20756284842449904, 'split3_test_neg_root_mean_squared_log_error': -0.11997346623130935, 'split4_test_neg_root_mean_squared_log_error': -0.13858997356412883, 'mean_test_neg_root_mean_squared_log_error': -0.1483531579916374, 'std_test_neg_root_mean_squared_log_error': 0.030430134102910036, 'rank_test_neg_root_mean_squared_log_error': 9, 'split0_train_neg_root_mean_squared_log_error': -0.12832904223947697, 'split1_train_neg_root_mean_squared_log_error': -0.12894106315325607, 'split2_train_neg_root_mean_squared_log_error': -0.11515085921852153, 'split3_train_neg_root_mean_squared_log_error': -0.1323389999572488, 'split4_train_neg_root_mean_squared_log_error': -0.12872313416993234, 'mean_train_neg_root_mean_squared_log_error': -0.12669661974768714, 'std_train_neg_root_mean_squared_log_error': 0.0059489516844930335, 'split0_test_neg_root_mean_squared_error': -41130.22952695101, 'split1_test_neg_root_mean_squared_error': -33599.977012608855, 'split2_test_neg_root_mean_squared_error': -113961.61023251225, 'split3_test_neg_root_mean_squared_error': -26534.001462860022, 'split4_test_neg_root_mean_squared_error': -32391.341286338306, 'mean_test_neg_root_mean_squared_error': -49523.43190425409, 'std_test_neg_root_mean_squared_error': 32552.430106083328, 'rank_test_neg_root_mean_squared_error': 33, 'split0_train_neg_root_mean_squared_error': -31222.484586880102, 'split1_train_neg_root_mean_squared_error': -30632.968693087743, 'split2_train_neg_root_mean_squared_error': -28024.990164503422, 'split3_train_neg_root_mean_squared_error': -32606.52972090696, 'split4_train_neg_root_mean_squared_error': -30905.745048042012, 'mean_train_neg_root_mean_squared_error': -30678.54364268405, 'std_train_neg_root_mean_squared_error': 1490.506335765541, 'split0_test_neg_mean_absolute_error': -17046.2863986468, 'split1_test_neg_mean_absolute_error': -17256.38163780669, 'split2_test_neg_mean_absolute_error': -22460.12916146771, 'split3_test_neg_mean_absolute_error': -16650.440241449047, 'split4_test_neg_mean_absolute_error': -19300.138546336162, 'mean_test_neg_mean_absolute_error': -18542.67519714128, 'std_test_neg_mean_absolute_error': 2163.075586870666, 'rank_test_neg_mean_absolute_error': 17, 'split0_train_neg_mean_absolute_error': -15775.78228792313, 'split1_train_neg_mean_absolute_error': -16380.756345000158, 'split2_train_neg_mean_absolute_error': -14655.89200590518, 'split3_train_neg_mean_absolute_error': -16513.577012989594, 'split4_train_neg_mean_absolute_error': -16112.702917473902, 'mean_train_neg_mean_absolute_error': -15887.742113858392, 'std_train_neg_mean_absolute_error': 665.631941440613, 'split0_test_r2': 0.7576204104231363, 'split1_test_r2': 0.8308880743623789, 'split2_test_r2': -1.8031322317819312, 'split3_test_r2': 0.8947043317271187, 'split4_test_r2': 0.8812058700442611, 'mean_test_r2': 0.31225729095499277, 'std_test_r2': 1.0587866708206342, 'rank_test_r2': 32, 'split0_train_r2': 0.8552315795711047, 'split1_train_r2': 0.8622000424156001, 'split2_train_r2': 0.8924372809501473, 'split3_train_r2': 0.8437308460187438, 'split4_train_r2': 0.8474210002123919, 'mean_train_r2': 0.8602041498335975, 'std_train_r2': 0.017334724898916704}
Logging parameters (RIDGE__alpha_100.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_100.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_100.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_100.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:31:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_100.0__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/2cd89efc287a4707a3b4e89997436590
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.6142099380493165, 'std_fit_time': 0.23785958523025652, 'mean_score_time': 0.2707845687866211, 'std_score_time': 0.16034389821138192, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 100.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 100, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.1369543991815835, 'split1_test_neg_root_mean_squared_log_error': -0.1386923915373095, 'split2_test_neg_root_mean_squared_log_error': -0.20755284349773895, 'split3_test_neg_root_mean_squared_log_error': -0.11996467771597047, 'split4_test_neg_root_mean_squared_log_error': -0.13865544688577483, 'mean_test_neg_root_mean_squared_log_error': -0.14836395176367545, 'std_test_neg_root_mean_squared_log_error': 0.03042306922532079, 'rank_test_neg_root_mean_squared_log_error': 10, 'split0_train_neg_root_mean_squared_log_error': -0.12832644654131736, 'split1_train_neg_root_mean_squared_log_error': -0.12893526461527594, 'split2_train_neg_root_mean_squared_log_error': -0.11515055449591076, 'split3_train_neg_root_mean_squared_log_error': -0.1323343318287528, 'split4_train_neg_root_mean_squared_log_error': -0.12870975616194177, 'mean_train_neg_root_mean_squared_log_error': -0.12669127072863973, 'std_train_neg_root_mean_squared_log_error': 0.005946694236129218, 'split0_test_neg_root_mean_squared_error': -41141.78565088912, 'split1_test_neg_root_mean_squared_error': -33591.07958563928, 'split2_test_neg_root_mean_squared_error': -113940.49822658344, 'split3_test_neg_root_mean_squared_error': -26534.851761182825, 'split4_test_neg_root_mean_squared_error': -32459.419503307847, 'mean_test_neg_root_mean_squared_error': -49533.5269455205, 'std_test_neg_root_mean_squared_error': 32537.071486417346, 'rank_test_neg_root_mean_squared_error': 34, 'split0_train_neg_root_mean_squared_error': -31221.037224802865, 'split1_train_neg_root_mean_squared_error': -30636.952202805416, 'split2_train_neg_root_mean_squared_error': -28026.247838642354, 'split3_train_neg_root_mean_squared_error': -32606.609808449106, 'split4_train_neg_root_mean_squared_error': -30896.251288473875, 'mean_train_neg_root_mean_squared_error': -30677.41967263472, 'std_train_neg_root_mean_squared_error': 1489.6665136001695, 'split0_test_neg_mean_absolute_error': -17052.07860719866, 'split1_test_neg_mean_absolute_error': -17247.77919315378, 'split2_test_neg_mean_absolute_error': -22459.236422175425, 'split3_test_neg_mean_absolute_error': -16652.16471563779, 'split4_test_neg_mean_absolute_error': -19322.916041386463, 'mean_test_neg_mean_absolute_error': -18546.834995910423, 'std_test_neg_mean_absolute_error': 2164.292254784752, 'rank_test_neg_mean_absolute_error': 18, 'split0_train_neg_mean_absolute_error': -15773.963699538786, 'split1_train_neg_mean_absolute_error': -16382.627241938342, 'split2_train_neg_mean_absolute_error': -14656.46249197315, 'split3_train_neg_mean_absolute_error': -16513.621760542595, 'split4_train_neg_mean_absolute_error': -16115.439894736945, 'mean_train_neg_mean_absolute_error': -15888.423017745965, 'std_train_neg_mean_absolute_error': 665.9542954632392, 'split0_test_r2': 0.7574841912920761, 'split1_test_r2': 0.8309776257205204, 'split2_test_r2': -1.8020937371083003, 'split3_test_r2': 0.8946975830906704, 'split4_test_r2': 0.8807059962551331, 'mean_test_r2': 0.31235433185001993, 'std_test_r2': 1.0583145681441937, 'rank_test_r2': 31, 'split0_train_r2': 0.8552450011464791, 'split1_train_r2': 0.8621642010861564, 'split2_train_r2': 0.8924276265749119, 'split3_train_r2': 0.843730078367115, 'split4_train_r2': 0.847514725560299, 'mean_train_r2': 0.8602163265469922, 'std_train_r2': 0.01731590706616573}
Logging parameters (RIDGE__alpha_100.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_100.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_100.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_100.0__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 19:33:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_100.0__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/963a083966f04d15a54be6088f97dc5e
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.45552473068237304, 'std_fit_time': 0.14010338938001918, 'mean_score_time': 0.1668344497680664, 'std_score_time': 0.01917535076695063, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 1000.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 1000, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.15411786693636062, 'split1_test_neg_root_mean_squared_log_error': -0.15645265297091457, 'split2_test_neg_root_mean_squared_log_error': -0.20485934165377864, 'split3_test_neg_root_mean_squared_log_error': -0.13876455362397996, 'split4_test_neg_root_mean_squared_log_error': -0.15486015060747163, 'mean_test_neg_root_mean_squared_log_error': -0.1618109131585011, 'std_test_neg_root_mean_squared_log_error': 0.022452211009885398, 'rank_test_neg_root_mean_squared_log_error': 13, 'split0_train_neg_root_mean_squared_log_error': -0.15434051606433055, 'split1_train_neg_root_mean_squared_log_error': -0.15481121722614305, 'split2_train_neg_root_mean_squared_log_error': -0.13961534453792002, 'split3_train_neg_root_mean_squared_log_error': -0.15753661812384057, 'split4_train_neg_root_mean_squared_log_error': -0.15513051734144453, 'mean_train_neg_root_mean_squared_log_error': -0.15228684265873577, 'std_train_neg_root_mean_squared_log_error': 0.006431229029887711, 'split0_test_neg_root_mean_squared_error': -41124.79622017811, 'split1_test_neg_root_mean_squared_error': -36594.676074596726, 'split2_test_neg_root_mean_squared_error': -82733.273255912, 'split3_test_neg_root_mean_squared_error': -32775.4158136805, 'split4_test_neg_root_mean_squared_error': -38437.58995265082, 'mean_test_neg_root_mean_squared_error': -46333.15026340364, 'std_test_neg_root_mean_squared_error': 18401.553310877443, 'rank_test_neg_root_mean_squared_error': 21, 'split0_train_neg_root_mean_squared_error': -39714.21101491897, 'split1_train_neg_root_mean_squared_error': -38708.642569821684, 'split2_train_neg_root_mean_squared_error': -33348.09761081031, 'split3_train_neg_root_mean_squared_error': -40349.19347703833, 'split4_train_neg_root_mean_squared_error': -38370.78661838252, 'mean_train_neg_root_mean_squared_error': -38098.186258194364, 'std_train_neg_root_mean_squared_error': 2477.4535126383967, 'split0_test_neg_mean_absolute_error': -19995.088696384453, 'split1_test_neg_mean_absolute_error': -19955.827510576295, 'split2_test_neg_mean_absolute_error': -22602.370993230536, 'split3_test_neg_mean_absolute_error': -19431.249529615136, 'split4_test_neg_mean_absolute_error': -21654.84914185523, 'mean_test_neg_mean_absolute_error': -20727.87717433233, 'std_test_neg_mean_absolute_error': 1198.9401145532404, 'rank_test_neg_mean_absolute_error': 25, 'split0_train_neg_mean_absolute_error': -19389.13445720371, 'split1_train_neg_mean_absolute_error': -20088.82482217447, 'split2_train_neg_mean_absolute_error': -18476.21135068802, 'split3_train_neg_mean_absolute_error': -20061.159382697944, 'split4_train_neg_mean_absolute_error': -19823.238338148243, 'mean_train_neg_mean_absolute_error': -19567.71367018248, 'std_train_neg_mean_absolute_error': 600.6007340387173, 'split0_test_r2': 0.7576844429217635, 'split1_test_r2': 0.7993994641585953, 'split2_test_r2': -0.47736173180229224, 'split3_test_r2': 0.8393423433283764, 'split4_test_r2': 0.8327179214720584, 'mean_test_r2': 0.5503564880157003, 'std_test_r2': 0.5146752039630106, 'rank_test_r2': 21, 'split0_train_r2': 0.7657763232280447, 'split1_train_r2': 0.7799675201950345, 'split2_train_r2': 0.8476954203141531, 'split3_train_r2': 0.7607048933141476, 'split4_train_r2': 0.7648106058440374, 'mean_train_r2': 0.7837909525790835, 'std_train_r2': 0.03260719612883012}
Logging parameters (RIDGE__alpha_1000.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_1000.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_1000.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_1000.0__prep_v1__logY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:36:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_1000.0__prep_v1__logY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/10c435bb5dc64e8e9edd47daab9467f5
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.3784176349639893, 'std_fit_time': 0.021715671807392506, 'mean_score_time': 0.1467358112335205, 'std_score_time': 0.008059383781529537, 'param_func': <ufunc 'log1p'>, 'param_inverse_func': <ufunc 'expm1'>, 'param_regressor__model__alpha': 1000.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': <ufunc 'log1p'>, 'inverse_func': <ufunc 'expm1'>, 'regressor__model__alpha': 1000, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.1541468461801157, 'split1_test_neg_root_mean_squared_log_error': -0.1564405686146743, 'split2_test_neg_root_mean_squared_log_error': -0.20486571246681742, 'split3_test_neg_root_mean_squared_log_error': -0.13877501922958, 'split4_test_neg_root_mean_squared_log_error': -0.1548813833290539, 'mean_test_neg_root_mean_squared_log_error': -0.16182190596404827, 'std_test_neg_root_mean_squared_log_error': 0.02244978599096578, 'rank_test_neg_root_mean_squared_log_error': 14, 'split0_train_neg_root_mean_squared_log_error': -0.154339901820176, 'split1_train_neg_root_mean_squared_log_error': -0.1548150811136015, 'split2_train_neg_root_mean_squared_log_error': -0.13961734829907782, 'split3_train_neg_root_mean_squared_log_error': -0.1575363222365978, 'split4_train_neg_root_mean_squared_log_error': -0.15512759675806936, 'mean_train_neg_root_mean_squared_log_error': -0.1522872500455045, 'std_train_neg_root_mean_squared_log_error': 0.006430397309589688, 'split0_test_neg_root_mean_squared_error': -41143.95799838063, 'split1_test_neg_root_mean_squared_error': -36583.58463762086, 'split2_test_neg_root_mean_squared_error': -82726.30390341765, 'split3_test_neg_root_mean_squared_error': -32778.09488252135, 'split4_test_neg_root_mean_squared_error': -38469.78734708957, 'mean_test_neg_root_mean_squared_error': -46340.34575380602, 'std_test_neg_root_mean_squared_error': 18395.73386401055, 'rank_test_neg_root_mean_squared_error': 22, 'split0_train_neg_root_mean_squared_error': -39709.12523974656, 'split1_train_neg_root_mean_squared_error': -38712.4587332179, 'split2_train_neg_root_mean_squared_error': -33352.552381872585, 'split3_train_neg_root_mean_squared_error': -40351.375643059495, 'split4_train_neg_root_mean_squared_error': -38366.66004009128, 'mean_train_neg_root_mean_squared_error': -38098.43440759757, 'std_train_neg_root_mean_squared_error': 2475.5781640535265, 'split0_test_neg_mean_absolute_error': -20001.57221057591, 'split1_test_neg_mean_absolute_error': -19955.882750916884, 'split2_test_neg_mean_absolute_error': -22604.59937176925, 'split3_test_neg_mean_absolute_error': -19433.619621485283, 'split4_test_neg_mean_absolute_error': -21656.652709708105, 'mean_test_neg_mean_absolute_error': -20730.465332891086, 'std_test_neg_mean_absolute_error': 1198.6053238580903, 'rank_test_neg_mean_absolute_error': 26, 'split0_train_neg_mean_absolute_error': -19386.317304490065, 'split1_train_neg_mean_absolute_error': -20089.91176702994, 'split2_train_neg_mean_absolute_error': -18474.008588829332, 'split3_train_neg_mean_absolute_error': -20059.7974217101, 'split4_train_neg_mean_absolute_error': -19826.149084731835, 'mean_train_neg_mean_absolute_error': -19567.236833358256, 'std_train_neg_mean_absolute_error': 601.78408818433, 'split0_test_r2': 0.7574585802249321, 'split1_test_r2': 0.7995210452879169, 'split2_test_r2': -0.47711283989717845, 'split3_test_r2': 0.8393160778789617, 'split4_test_r2': 0.8324375551487269, 'mean_test_r2': 0.5503240837286718, 'std_test_r2': 0.514535682097657, 'rank_test_r2': 22, 'split0_train_r2': 0.7658363084402379, 'split1_train_r2': 0.7799241334353673, 'split2_train_r2': 0.8476547266974249, 'split3_train_r2': 0.760679009487178, 'split4_train_r2': 0.7648611899131272, 'mean_train_r2': 0.783791073594667, 'std_train_r2': 0.032583434469315886}
Logging parameters (RIDGE__alpha_1000.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_1000.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_1000.0__prep_v1__logY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_1000.0__prep_v1__logY__num_imp_median__ord_imp__ohe)

2026/04/10 19:38:55 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_1000.0__prep_v1__logY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/845d35cddef2430685f8c1c75a2cb068
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.465131950378418, 'std_fit_time': 0.15204105284612374, 'mean_score_time': 0.22462244033813478, 'std_score_time': 0.08080400155953238, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 0.001, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 0.001, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.7443561809410717, 'split1_test_neg_root_mean_squared_log_error': -0.7772505956012311, 'split2_test_neg_root_mean_squared_log_error': -0.20473630958826466, 'split3_test_neg_root_mean_squared_log_error': -1.1158908865730566, 'split4_test_neg_root_mean_squared_log_error': -0.29982518973280264, 'mean_test_neg_root_mean_squared_log_error': -0.6284118324872853, 'std_test_neg_root_mean_squared_log_error': 0.33487371590390347, 'rank_test_neg_root_mean_squared_log_error': 40, 'split0_train_neg_root_mean_squared_log_error': -0.12243402206330435, 'split1_train_neg_root_mean_squared_log_error': -0.3785938661708795, 'split2_train_neg_root_mean_squared_log_error': -0.16259734966460032, 'split3_train_neg_root_mean_squared_log_error': -0.14371607991152935, 'split4_train_neg_root_mean_squared_log_error': -0.3783538822640426, 'mean_train_neg_root_mean_squared_log_error': -0.23713904001487124, 'std_train_neg_root_mean_squared_log_error': 0.1160970746679695, 'split0_test_neg_root_mean_squared_error': -38264.32800078025, 'split1_test_neg_root_mean_squared_error': -35420.52080020355, 'split2_test_neg_root_mean_squared_error': -52660.575028593965, 'split3_test_neg_root_mean_squared_error': -36649.873896716774, 'split4_test_neg_root_mean_squared_error': -47343.0827094021, 'mean_test_neg_root_mean_squared_error': -42067.676087139334, 'std_test_neg_root_mean_squared_error': 6753.401123334547, 'rank_test_neg_root_mean_squared_error': 19, 'split0_train_neg_root_mean_squared_error': -21369.565713274853, 'split1_train_neg_root_mean_squared_error': -22192.133186609375, 'split2_train_neg_root_mean_squared_error': -23462.343170214517, 'split3_train_neg_root_mean_squared_error': -22494.876941286762, 'split4_train_neg_root_mean_squared_error': -20155.963350544633, 'mean_train_neg_root_mean_squared_error': -21934.976472386024, 'std_train_neg_root_mean_squared_error': 1113.2873981666598, 'split0_test_neg_mean_absolute_error': -21563.61007111444, 'split1_test_neg_mean_absolute_error': -22735.537119416367, 'split2_test_neg_mean_absolute_error': -21848.558363672633, 'split3_test_neg_mean_absolute_error': -23001.63799085352, 'split4_test_neg_mean_absolute_error': -23635.820239604815, 'mean_test_neg_mean_absolute_error': -22557.032756932353, 'std_test_neg_mean_absolute_error': 759.2291686742695, 'rank_test_neg_mean_absolute_error': 40, 'split0_train_neg_mean_absolute_error': -14787.169468803148, 'split1_train_neg_mean_absolute_error': -14601.429775941018, 'split2_train_neg_mean_absolute_error': -15692.897937660877, 'split3_train_neg_mean_absolute_error': -15204.80349606538, 'split4_train_neg_mean_absolute_error': -14021.470349586261, 'mean_train_neg_mean_absolute_error': -14861.554205611337, 'std_train_neg_mean_absolute_error': 563.5408005372021, 'split0_test_r2': 0.7902210241487757, 'split1_test_r2': 0.8120656530347374, 'split2_test_r2': 0.4014538725531871, 'split3_test_r2': 0.799113858533076, 'split4_test_r2': 0.7462242127535463, 'mean_test_r2': 0.7098157242046644, 'std_test_r2': 0.15576060258726165, 'rank_test_r2': 19, 'split0_train_r2': 0.9321842906977812, 'split1_train_r2': 0.9276782360622134, 'split2_train_r2': 0.9246100249194399, 'split3_train_r2': 0.9256242522832052, 'split4_train_r2': 0.9351031752431441, 'mean_train_r2': 0.9290399958411568, 'std_train_r2': 0.003994873482917099}
Logging parameters (RIDGE__alpha_0.001__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.001__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.001__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.001__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:41:23 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.001__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/5844e2c73c164031889ac6364f385533
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.37008962631225584, 'std_fit_time': 0.03556645284638281, 'mean_score_time': 0.2221613883972168, 'std_score_time': 0.0727984401393628, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 0.001, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 0.001, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.7444552813763469, 'split1_test_neg_root_mean_squared_log_error': -0.7770786923944978, 'split2_test_neg_root_mean_squared_log_error': -0.20466913766787223, 'split3_test_neg_root_mean_squared_log_error': -1.1159637551040946, 'split4_test_neg_root_mean_squared_log_error': -0.29981116783054435, 'mean_test_neg_root_mean_squared_log_error': -0.6283956068746711, 'std_test_neg_root_mean_squared_log_error': 0.33490627388014216, 'rank_test_neg_root_mean_squared_log_error': 39, 'split0_train_neg_root_mean_squared_log_error': -0.12241114390426255, 'split1_train_neg_root_mean_squared_log_error': -0.37860564828278853, 'split2_train_neg_root_mean_squared_log_error': -0.16282297247066246, 'split3_train_neg_root_mean_squared_log_error': -0.1438230132906269, 'split4_train_neg_root_mean_squared_log_error': -0.3783481830383399, 'mean_train_neg_root_mean_squared_log_error': -0.2372021921973361, 'std_train_neg_root_mean_squared_log_error': 0.11605692764506731, 'split0_test_neg_root_mean_squared_error': -38338.32036133056, 'split1_test_neg_root_mean_squared_error': -35360.32961641253, 'split2_test_neg_root_mean_squared_error': -52665.627438795025, 'split3_test_neg_root_mean_squared_error': -36657.711077080334, 'split4_test_neg_root_mean_squared_error': -47330.552148206094, 'mean_test_neg_root_mean_squared_error': -42070.508128364905, 'std_test_neg_root_mean_squared_error': 6755.423145917352, 'rank_test_neg_root_mean_squared_error': 20, 'split0_train_neg_root_mean_squared_error': -21344.06743538195, 'split1_train_neg_root_mean_squared_error': -22201.59566761761, 'split2_train_neg_root_mean_squared_error': -23462.311721012215, 'split3_train_neg_root_mean_squared_error': -22490.032614203177, 'split4_train_neg_root_mean_squared_error': -20155.606128114916, 'mean_train_neg_root_mean_squared_error': -21930.722713265975, 'std_train_neg_root_mean_squared_error': 1115.9899567005268, 'split0_test_neg_mean_absolute_error': -21617.992150517544, 'split1_test_neg_mean_absolute_error': -22674.529990573294, 'split2_test_neg_mean_absolute_error': -21835.128174932903, 'split3_test_neg_mean_absolute_error': -22999.113307013842, 'split4_test_neg_mean_absolute_error': -23626.620033206018, 'mean_test_neg_mean_absolute_error': -22550.676731248725, 'std_test_neg_mean_absolute_error': 742.4283460288111, 'rank_test_neg_mean_absolute_error': 39, 'split0_train_neg_mean_absolute_error': -14762.638334980722, 'split1_train_neg_mean_absolute_error': -14601.6132871211, 'split2_train_neg_mean_absolute_error': -15685.358768220993, 'split3_train_neg_mean_absolute_error': -15191.415327179453, 'split4_train_neg_mean_absolute_error': -14015.635421598397, 'mean_train_neg_mean_absolute_error': -14851.332227820134, 'std_train_neg_mean_absolute_error': 562.1160187119619, 'split0_test_r2': 0.7894089336173358, 'split1_test_r2': 0.8127038355998718, 'split2_test_r2': 0.4013390144974589, 'split3_test_r2': 0.7990279346764294, 'split4_test_r2': 0.7463585315187018, 'mean_test_r2': 0.7097676499819595, 'std_test_r2': 0.15580314925627173, 'rank_test_r2': 20, 'split0_train_r2': 0.932346030265996, 'split1_train_r2': 0.9276165485074199, 'split2_train_r2': 0.9246102270265331, 'split3_train_r2': 0.9256562828343545, 'split4_train_r2': 0.9351054755446069, 'mean_train_r2': 0.9290669128357821, 'std_train_r2': 0.004020319708767632}
Logging parameters (RIDGE__alpha_0.001__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.001__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.001__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.001__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 19:43:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.001__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/97497e1408b44dcc8e3d62b6148023e1
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.5237399578094483, 'std_fit_time': 0.17439338974512483, 'mean_score_time': 0.2642500877380371, 'std_score_time': 0.11565156973446868, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 0.01, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 0.01, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.7438941660352987, 'split1_test_neg_root_mean_squared_log_error': -0.7757116755131495, 'split2_test_neg_root_mean_squared_log_error': -0.20440078931122888, 'split3_test_neg_root_mean_squared_log_error': -0.8192549713762146, 'split4_test_neg_root_mean_squared_log_error': -0.2754206284999923, 'mean_test_neg_root_mean_squared_log_error': -0.5637364461471768, 'std_test_neg_root_mean_squared_log_error': 0.26643128330380156, 'rank_test_neg_root_mean_squared_log_error': 38, 'split0_train_neg_root_mean_squared_log_error': -0.1223895464507583, 'split1_train_neg_root_mean_squared_log_error': -0.21438070037956825, 'split2_train_neg_root_mean_squared_log_error': -0.15871963601165964, 'split3_train_neg_root_mean_squared_log_error': -0.14258413087967123, 'split4_train_neg_root_mean_squared_log_error': -0.1939787291877821, 'mean_train_neg_root_mean_squared_log_error': -0.16641054858188792, 'std_train_neg_root_mean_squared_log_error': 0.033543514993882244, 'split0_test_neg_root_mean_squared_error': -38167.39636456906, 'split1_test_neg_root_mean_squared_error': -35532.28501745695, 'split2_test_neg_root_mean_squared_error': -52643.75308254826, 'split3_test_neg_root_mean_squared_error': -36156.36395894406, 'split4_test_neg_root_mean_squared_error': -46826.5889162037, 'mean_test_neg_root_mean_squared_error': -41865.277467944405, 'std_test_neg_root_mean_squared_error': 6740.370306550181, 'rank_test_neg_root_mean_squared_error': 17, 'split0_train_neg_root_mean_squared_error': -21372.98420030954, 'split1_train_neg_root_mean_squared_error': -22194.5149501758, 'split2_train_neg_root_mean_squared_error': -23462.850452155377, 'split3_train_neg_root_mean_squared_error': -22498.286024065932, 'split4_train_neg_root_mean_squared_error': -20161.560402624447, 'mean_train_neg_root_mean_squared_error': -21938.03920586622, 'std_train_neg_root_mean_squared_error': 1111.7436520352994, 'split0_test_neg_mean_absolute_error': -21576.714741696127, 'split1_test_neg_mean_absolute_error': -22700.607328330563, 'split2_test_neg_mean_absolute_error': -21815.87884048375, 'split3_test_neg_mean_absolute_error': -22810.37887649838, 'split4_test_neg_mean_absolute_error': -23486.2558303932, 'mean_test_neg_mean_absolute_error': -22477.967123480405, 'std_test_neg_mean_absolute_error': 696.7537730075622, 'rank_test_neg_mean_absolute_error': 38, 'split0_train_neg_mean_absolute_error': -14788.048052361844, 'split1_train_neg_mean_absolute_error': -14614.202074857234, 'split2_train_neg_mean_absolute_error': -15700.608185406487, 'split3_train_neg_mean_absolute_error': -15215.434992288017, 'split4_train_neg_mean_absolute_error': -14031.853290308703, 'mean_train_neg_mean_absolute_error': -14870.029319044459, 'std_train_neg_mean_absolute_error': 562.8274859064055, 'split0_test_r2': 0.7912825069968346, 'split1_test_r2': 0.8108777838139775, 'split2_test_r2': 0.4018362118070551, 'split3_test_r2': 0.8044875100685269, 'split4_test_r2': 0.7517311899741955, 'mean_test_r2': 0.7120430405321179, 'std_test_r2': 0.15645868800860452, 'rank_test_r2': 17, 'split0_train_r2': 0.9321625920195031, 'split1_train_r2': 0.9276627114089974, 'split2_train_r2': 0.9246067648540627, 'split3_train_r2': 0.9256017073904915, 'split4_train_r2': 0.9350671282099224, 'mean_train_r2': 0.9290201807765953, 'std_train_r2': 0.003986157176070864}
Logging parameters (RIDGE__alpha_0.01__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.01__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.01__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.01__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:46:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.01__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/65ea53f64c5d42418d0db9b92e560a0e
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.45736308097839357, 'std_fit_time': 0.20973672914960345, 'mean_score_time': 0.19335999488830566, 'std_score_time': 0.07004406120593859, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 0.01, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 0.01, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.7439924851018995, 'split1_test_neg_root_mean_squared_log_error': -0.7755479621819092, 'split2_test_neg_root_mean_squared_log_error': -0.2043357828381239, 'split3_test_neg_root_mean_squared_log_error': -0.8182968735638779, 'split4_test_neg_root_mean_squared_log_error': -0.2754132007696895, 'mean_test_neg_root_mean_squared_log_error': -0.5635172608911001, 'std_test_neg_root_mean_squared_log_error': 0.266254111522156, 'rank_test_neg_root_mean_squared_log_error': 37, 'split0_train_neg_root_mean_squared_log_error': -0.12236967258777562, 'split1_train_neg_root_mean_squared_log_error': -0.22029612816474198, 'split2_train_neg_root_mean_squared_log_error': -0.1589061708071, 'split3_train_neg_root_mean_squared_log_error': -0.14268138332373564, 'split4_train_neg_root_mean_squared_log_error': -0.1951204529072364, 'mean_train_neg_root_mean_squared_log_error': -0.16787476155811792, 'std_train_neg_root_mean_squared_log_error': 0.03542931673943534, 'split0_test_neg_root_mean_squared_error': -38242.34486693586, 'split1_test_neg_root_mean_squared_error': -35472.37678299712, 'split2_test_neg_root_mean_squared_error': -52648.829273197596, 'split3_test_neg_root_mean_squared_error': -36163.677695639366, 'split4_test_neg_root_mean_squared_error': -46814.85769731332, 'mean_test_neg_root_mean_squared_error': -41868.41726321665, 'std_test_neg_root_mean_squared_error': 6742.200597053845, 'rank_test_neg_root_mean_squared_error': 18, 'split0_train_neg_root_mean_squared_error': -21347.49010746411, 'split1_train_neg_root_mean_squared_error': -22203.97527364729, 'split2_train_neg_root_mean_squared_error': -23462.817523937705, 'split3_train_neg_root_mean_squared_error': -22493.444515982454, 'split4_train_neg_root_mean_squared_error': -20161.204109700895, 'mean_train_neg_root_mean_squared_error': -21933.78630614649, 'std_train_neg_root_mean_squared_error': 1114.4457573808902, 'split0_test_neg_mean_absolute_error': -21630.908884552722, 'split1_test_neg_mean_absolute_error': -22639.84540841, 'split2_test_neg_mean_absolute_error': -21802.443281628293, 'split3_test_neg_mean_absolute_error': -22808.346713929874, 'split4_test_neg_mean_absolute_error': -23477.658014717163, 'mean_test_neg_mean_absolute_error': -22471.84046064761, 'std_test_neg_mean_absolute_error': 679.4688472619799, 'rank_test_neg_mean_absolute_error': 37, 'split0_train_neg_mean_absolute_error': -14763.239645003534, 'split1_train_neg_mean_absolute_error': -14614.596437237382, 'split2_train_neg_mean_absolute_error': -15693.041159240522, 'split3_train_neg_mean_absolute_error': -15202.140633596302, 'split4_train_neg_mean_absolute_error': -14026.437103711196, 'mean_train_neg_mean_absolute_error': -14859.890995757789, 'std_train_neg_mean_absolute_error': 561.3252717848814, 'split0_test_r2': 0.7904619939943806, 'split1_test_r2': 0.8115149748510249, 'split2_test_r2': 0.4017208499780366, 'split3_test_r2': 0.8044084052394588, 'split4_test_r2': 0.7518555693490487, 'mean_test_r2': 0.7119923586823899, 'std_test_r2': 0.15649948570817387, 'rank_test_r2': 18, 'split0_train_r2': 0.9323243309418081, 'split1_train_r2': 0.9276010313048808, 'split2_train_r2': 0.9246069764705601, 'split3_train_r2': 0.9256337241564045, 'split4_train_r2': 0.9350694231630751, 'mean_train_r2': 0.9290470972073457, 'std_train_r2': 0.004011622245519792}
Logging parameters (RIDGE__alpha_0.01__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.01__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.01__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.01__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 19:48:47 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.01__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/b3fc6ddbedc84675b5f8acad78247529
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.48247833251953126, 'std_fit_time': 0.18903209201888305, 'mean_score_time': 0.275023365020752, 'std_score_time': 0.10671919676104309, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 0.1, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 0.1, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.7424291236772422, 'split1_test_neg_root_mean_squared_log_error': -0.7677853652196396, 'split2_test_neg_root_mean_squared_log_error': -0.20194211498013553, 'split3_test_neg_root_mean_squared_log_error': -0.7672337011764603, 'split4_test_neg_root_mean_squared_log_error': -0.2058687049712831, 'mean_test_neg_root_mean_squared_log_error': -0.5370518020049522, 'std_test_neg_root_mean_squared_log_error': 0.2721699007075966, 'rank_test_neg_root_mean_squared_log_error': 36, 'split0_train_neg_root_mean_squared_log_error': -0.12269494980546285, 'split1_train_neg_root_mean_squared_log_error': -0.14516768462524357, 'split2_train_neg_root_mean_squared_log_error': -0.14529483198654256, 'split3_train_neg_root_mean_squared_log_error': -0.13586407238163922, 'split4_train_neg_root_mean_squared_log_error': -0.1423171953174516, 'mean_train_neg_root_mean_squared_log_error': -0.13826774682326795, 'std_train_neg_root_mean_squared_log_error': 0.008505019205730123, 'split0_test_neg_root_mean_squared_error': -37562.338763500375, 'split1_test_neg_root_mean_squared_error': -36436.162312811946, 'split2_test_neg_root_mean_squared_error': -52506.966891251046, 'split3_test_neg_root_mean_squared_error': -33050.1066561601, 'split4_test_neg_root_mean_squared_error': -43736.564277296064, 'mean_test_neg_root_mean_squared_error': -40658.42778020391, 'std_test_neg_root_mean_squared_error': 6858.026634007755, 'rank_test_neg_root_mean_squared_error': 15, 'split0_train_neg_root_mean_squared_error': -21575.931062378786, 'split1_train_neg_root_mean_squared_error': -22341.646906962425, 'split2_train_neg_root_mean_squared_error': -23489.108393279486, 'split3_train_neg_root_mean_squared_error': -22690.137471148155, 'split4_train_neg_root_mean_squared_error': -20467.34560378751, 'mean_train_neg_root_mean_squared_error': -22112.833887511275, 'std_train_neg_root_mean_squared_error': 1027.196444336262, 'split0_test_neg_mean_absolute_error': -21644.178372624257, 'split1_test_neg_mean_absolute_error': -22580.950099176727, 'split2_test_neg_mean_absolute_error': -21607.27729872229, 'split3_test_neg_mean_absolute_error': -21597.279611582195, 'split4_test_neg_mean_absolute_error': -22838.560972475465, 'mean_test_neg_mean_absolute_error': -22053.649270916187, 'std_test_neg_mean_absolute_error': 542.0922731044645, 'rank_test_neg_mean_absolute_error': 34, 'split0_train_neg_mean_absolute_error': -14877.51979670524, 'split1_train_neg_mean_absolute_error': -14766.625696457986, 'split2_train_neg_mean_absolute_error': -15763.105258729596, 'split3_train_neg_mean_absolute_error': -15410.43760487605, 'split4_train_neg_mean_absolute_error': -14294.282794360644, 'mean_train_neg_mean_absolute_error': -15022.3942302259, 'std_train_neg_mean_absolute_error': 512.9878937652163, 'split0_test_r2': 0.7978475403760703, 'split1_test_r2': 0.801133545771062, 'split2_test_r2': 0.40494063513986256, 'split3_test_r2': 0.8366381140909012, 'split4_test_r2': 0.7834159625855337, 'mean_test_r2': 0.7247951595926858, 'std_test_r2': 0.1608827904841269, 'rank_test_r2': 15, 'split0_train_r2': 0.9308681772599388, 'split1_train_r2': 0.9267004552326468, 'split2_train_r2': 0.9244379210141636, 'split3_train_r2': 0.9243274523183633, 'split4_train_r2': 0.9330825513637667, 'mean_train_r2': 0.9278833114377758, 'std_train_r2': 0.003517257961383403}
Logging parameters (RIDGE__alpha_0.1__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.1__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.1__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.1__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:51:15 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.1__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/eff35b6208fd47ea814cb8367989cc0c
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.45373950004577634, 'std_fit_time': 0.11239500271460845, 'mean_score_time': 0.22994375228881836, 'std_score_time': 0.07139767400019235, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 0.1, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 0.1, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.7425168564760177, 'split1_test_neg_root_mean_squared_log_error': -0.7676638949268364, 'split2_test_neg_root_mean_squared_log_error': -0.20189110867036794, 'split3_test_neg_root_mean_squared_log_error': -0.7672759825227842, 'split4_test_neg_root_mean_squared_log_error': -0.2058642342672838, 'mean_test_neg_root_mean_squared_log_error': -0.537042415372658, 'std_test_neg_root_mean_squared_log_error': 0.27218335520221826, 'rank_test_neg_root_mean_squared_log_error': 35, 'split0_train_neg_root_mean_squared_log_error': -0.12269336278459071, 'split1_train_neg_root_mean_squared_log_error': -0.1453578353240963, 'split2_train_neg_root_mean_squared_log_error': -0.1453855910293124, 'split3_train_neg_root_mean_squared_log_error': -0.1359090384245647, 'split4_train_neg_root_mean_squared_log_error': -0.14232229547263864, 'mean_train_neg_root_mean_squared_log_error': -0.13833362460704055, 'std_train_neg_root_mean_squared_log_error': 0.008549569228020276, 'split0_test_neg_root_mean_squared_error': -37642.77710987425, 'split1_test_neg_root_mean_squared_error': -36378.623912379015, 'split2_test_neg_root_mean_squared_error': -52511.947124187405, 'split3_test_neg_root_mean_squared_error': -33053.2294150926, 'split4_test_neg_root_mean_squared_error': -43730.81548980936, 'mean_test_neg_root_mean_squared_error': -40663.478610268525, 'std_test_neg_root_mean_squared_error': 6858.502340994049, 'rank_test_neg_root_mean_squared_error': 16, 'split0_train_neg_root_mean_squared_error': -21550.70397648575, 'split1_train_neg_root_mean_squared_error': -22351.028873124334, 'split2_train_neg_root_mean_squared_error': -23489.012854414876, 'split3_train_neg_root_mean_squared_error': -22685.622674911476, 'split4_train_neg_root_mean_squared_error': -20467.098906949937, 'mean_train_neg_root_mean_squared_error': -22108.693457177273, 'std_train_neg_root_mean_squared_error': 1029.8582759182445, 'split0_test_neg_mean_absolute_error': -21695.080004391522, 'split1_test_neg_mean_absolute_error': -22523.21378377418, 'split2_test_neg_mean_absolute_error': -21594.548180001533, 'split3_test_neg_mean_absolute_error': -21602.479145744404, 'split4_test_neg_mean_absolute_error': -22833.44021703003, 'mean_test_neg_mean_absolute_error': -22049.752266188334, 'std_test_neg_mean_absolute_error': 523.7153865545724, 'rank_test_neg_mean_absolute_error': 33, 'split0_train_neg_mean_absolute_error': -14849.895348716382, 'split1_train_neg_mean_absolute_error': -14767.89293398821, 'split2_train_neg_mean_absolute_error': -15754.845424884657, 'split3_train_neg_mean_absolute_error': -15397.666131944257, 'split4_train_neg_mean_absolute_error': -14290.271440182722, 'mean_train_neg_mean_absolute_error': -15012.114255943245, 'std_train_neg_mean_absolute_error': 511.3347078048585, 'split0_test_r2': 0.7969808094396176, 'split1_test_r2': 0.8017611323353422, 'split2_test_r2': 0.4048277482234186, 'split3_test_r2': 0.8366072419430929, 'split4_test_r2': 0.7834728949850597, 'mean_test_r2': 0.7247299653853061, 'std_test_r2': 0.16090908643161533, 'rank_test_r2': 16, 'split0_train_r2': 0.9310297438561167, 'split1_train_r2': 0.9266388806993293, 'split2_train_r2': 0.9244385356905855, 'split3_train_r2': 0.9243575633870345, 'split4_train_r2': 0.9330841644917012, 'mean_train_r2': 0.9279097776249534, 'std_train_r2': 0.0035437661967155773}
Logging parameters (RIDGE__alpha_0.1__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_0.1__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_0.1__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_0.1__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 19:53:43 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_0.1__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/414a0d5dd6b942699291bd02fcf6b20b
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.410765552520752, 'std_fit_time': 0.09079437757502322, 'mean_score_time': 0.17729487419128417, 'std_score_time': 0.06588771194523431, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 1.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 1, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.19891464159397157, 'split1_test_neg_root_mean_squared_log_error': -0.7586909921475335, 'split2_test_neg_root_mean_squared_log_error': -0.19675425001739907, 'split3_test_neg_root_mean_squared_log_error': -0.20245765437996927, 'split4_test_neg_root_mean_squared_log_error': -0.16899337924617094, 'mean_test_neg_root_mean_squared_log_error': -0.30516218347700885, 'std_test_neg_root_mean_squared_log_error': 0.22707679935650726, 'rank_test_neg_root_mean_squared_log_error': 34, 'split0_train_neg_root_mean_squared_log_error': -0.12954226694448828, 'split1_train_neg_root_mean_squared_log_error': -0.1366322173059659, 'split2_train_neg_root_mean_squared_log_error': -0.13637876996069245, 'split3_train_neg_root_mean_squared_log_error': -0.1379559087207203, 'split4_train_neg_root_mean_squared_log_error': -0.13559519451546884, 'mean_train_neg_root_mean_squared_log_error': -0.13522087148946715, 'std_train_neg_root_mean_squared_log_error': 0.0029393782283266994, 'split0_test_neg_root_mean_squared_error': -36398.55979457909, 'split1_test_neg_root_mean_squared_error': -37972.27170647888, 'split2_test_neg_root_mean_squared_error': -51617.85526605068, 'split3_test_neg_root_mean_squared_error': -29079.539811763745, 'split4_test_neg_root_mean_squared_error': -38469.63810235292, 'mean_test_neg_root_mean_squared_error': -38707.57293624506, 'std_test_neg_root_mean_squared_error': 7284.273941216954, 'rank_test_neg_root_mean_squared_error': 11, 'split0_train_neg_root_mean_squared_error': -23740.086204895117, 'split1_train_neg_root_mean_squared_error': -24051.51867719733, 'split2_train_neg_root_mean_squared_error': -23952.227571387673, 'split3_train_neg_root_mean_squared_error': -24922.804319627805, 'split4_train_neg_root_mean_squared_error': -23329.781752961542, 'mean_train_neg_root_mean_squared_error': -23999.283705213893, 'std_train_neg_root_mean_squared_error': 524.070473413155, 'split0_test_neg_mean_absolute_error': -21945.44475908394, 'split1_test_neg_mean_absolute_error': -22104.78265871845, 'split2_test_neg_mean_absolute_error': -21121.224737148827, 'split3_test_neg_mean_absolute_error': -20031.278885795324, 'split4_test_neg_mean_absolute_error': -22683.362199325587, 'mean_test_neg_mean_absolute_error': -21577.218648014426, 'std_test_neg_mean_absolute_error': 920.3616686419879, 'rank_test_neg_mean_absolute_error': 31, 'split0_train_neg_mean_absolute_error': -15782.06634651103, 'split1_train_neg_mean_absolute_error': -15903.014919514875, 'split2_train_neg_mean_absolute_error': -16090.345850204543, 'split3_train_neg_mean_absolute_error': -16702.273009577, 'split4_train_neg_mean_absolute_error': -16047.681016677881, 'mean_train_neg_mean_absolute_error': -16105.076228497066, 'std_train_neg_mean_absolute_error': 317.9054407099293, 'split0_test_r2': 0.8101799080161447, 'split1_test_r2': 0.7840120941192803, 'split2_test_r2': 0.4249225448610161, 'split3_test_r2': 0.87353217002826, 'split4_test_r2': 0.8324388552736388, 'mean_test_r2': 0.745017114459668, 'std_test_r2': 0.16271816853936572, 'rank_test_r2': 13, 'split0_train_r2': 0.9163042319093052, 'split1_train_r2': 0.9150514602260105, 'split2_train_r2': 0.9214289326338675, 'split3_train_r2': 0.908702703632968, 'split4_train_r2': 0.9130563876416206, 'mean_train_r2': 0.9149087432087543, 'std_train_r2': 0.004157566003398014}
Logging parameters (RIDGE__alpha_1.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_1.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_1.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_1.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 19:56:11 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_1.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/912d7b6af7fb4e11be1aa4d4917cda78
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.40976848602294924, 'std_fit_time': 0.1294855267442441, 'mean_score_time': 0.20759663581848145, 'std_score_time': 0.11547839258635363, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 1.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 1, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.19875804569317773, 'split1_test_neg_root_mean_squared_log_error': -0.7586482470380119, 'split2_test_neg_root_mean_squared_log_error': -0.19673797700967074, 'split3_test_neg_root_mean_squared_log_error': -0.20245940859718384, 'split4_test_neg_root_mean_squared_log_error': -0.16904067635554537, 'mean_test_neg_root_mean_squared_log_error': -0.30512887093871793, 'std_test_neg_root_mean_squared_log_error': 0.22707011166159902, 'rank_test_neg_root_mean_squared_log_error': 33, 'split0_train_neg_root_mean_squared_log_error': -0.12954936622030166, 'split1_train_neg_root_mean_squared_log_error': -0.1366389474923286, 'split2_train_neg_root_mean_squared_log_error': -0.13641820546777994, 'split3_train_neg_root_mean_squared_log_error': -0.13797207498129857, 'split4_train_neg_root_mean_squared_log_error': -0.135535363947399, 'mean_train_neg_root_mean_squared_log_error': -0.13522279162182155, 'std_train_neg_root_mean_squared_log_error': 0.002942058053428105, 'split0_test_neg_root_mean_squared_error': -36489.453375388446, 'split1_test_neg_root_mean_squared_error': -37923.17178326935, 'split2_test_neg_root_mean_squared_error': -51622.08382645668, 'split3_test_neg_root_mean_squared_error': -29077.248669885394, 'split4_test_neg_root_mean_squared_error': -38482.92144333663, 'mean_test_neg_root_mean_squared_error': -38718.9758196673, 'std_test_neg_root_mean_squared_error': 7281.66045250929, 'rank_test_neg_root_mean_squared_error': 12, 'split0_train_neg_root_mean_squared_error': -23718.291017723455, 'split1_train_neg_root_mean_squared_error': -24060.74168810074, 'split2_train_neg_root_mean_squared_error': -23952.214250685633, 'split3_train_neg_root_mean_squared_error': -24921.00039880143, 'split4_train_neg_root_mean_squared_error': -23329.62623576558, 'mean_train_neg_root_mean_squared_error': -23996.374718215367, 'std_train_neg_root_mean_squared_error': 525.9106361792423, 'split0_test_neg_mean_absolute_error': -22005.623370494057, 'split1_test_neg_mean_absolute_error': -22059.238805986024, 'split2_test_neg_mean_absolute_error': -21107.707518629948, 'split3_test_neg_mean_absolute_error': -20041.034312225234, 'split4_test_neg_mean_absolute_error': -22688.298869749164, 'mean_test_neg_mean_absolute_error': -21580.380575416886, 'std_test_neg_mean_absolute_error': 919.8506751945562, 'rank_test_neg_mean_absolute_error': 32, 'split0_train_neg_mean_absolute_error': -15753.835345457293, 'split1_train_neg_mean_absolute_error': -15907.253524929914, 'split2_train_neg_mean_absolute_error': -16082.365609322584, 'split3_train_neg_mean_absolute_error': -16690.666787181977, 'split4_train_neg_mean_absolute_error': -16048.216620373685, 'mean_train_neg_mean_absolute_error': -16096.467577453092, 'std_train_neg_mean_absolute_error': 318.9979703011701, 'split0_test_r2': 0.8092306962680119, 'split1_test_r2': 0.784570297921312, 'split2_test_r2': 0.4248283197387315, 'split3_test_r2': 0.8735520977388521, 'split4_test_r2': 0.8323231195296169, 'mean_test_r2': 0.744900906239305, 'std_test_r2': 0.16269739739870154, 'rank_test_r2': 14, 'split0_train_r2': 0.9164578394029661, 'split1_train_r2': 0.9149862974777063, 'split2_train_r2': 0.9214290200262809, 'split3_train_r2': 0.9087159194117324, 'split4_train_r2': 0.9130575467764875, 'mean_train_r2': 0.9149293246190346, 'std_train_r2': 0.004164026904338682}
Logging parameters (RIDGE__alpha_1.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_1.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_1.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_1.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 19:58:39 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_1.0__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/c7e4d7f76b584d1c9c2c1d15407d6586
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.3553011894226074, 'std_fit_time': 0.0651193500482718, 'mean_score_time': 0.19851784706115722, 'std_score_time': 0.02974081514820893, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 5.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 5, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.20041721981848012, 'split1_test_neg_root_mean_squared_log_error': -0.7574885360858697, 'split2_test_neg_root_mean_squared_log_error': -0.19256233921781543, 'split3_test_neg_root_mean_squared_log_error': -0.16100986732655112, 'split4_test_neg_root_mean_squared_log_error': -0.16589584704980864, 'mean_test_neg_root_mean_squared_log_error': -0.295474761899705, 'std_test_neg_root_mean_squared_log_error': 0.2314973579256447, 'rank_test_neg_root_mean_squared_log_error': 31, 'split0_train_neg_root_mean_squared_log_error': -0.13784423233389245, 'split1_train_neg_root_mean_squared_log_error': -0.14340698352833045, 'split2_train_neg_root_mean_squared_log_error': -0.13589222258365705, 'split3_train_neg_root_mean_squared_log_error': -0.14990787925407922, 'split4_train_neg_root_mean_squared_log_error': -0.14245741435030856, 'mean_train_neg_root_mean_squared_log_error': -0.14190174641005354, 'std_train_neg_root_mean_squared_log_error': 0.0048836557179335474, 'split0_test_neg_root_mean_squared_error': -36236.40990232119, 'split1_test_neg_root_mean_squared_error': -37629.212904971835, 'split2_test_neg_root_mean_squared_error': -50591.91514005915, 'split3_test_neg_root_mean_squared_error': -28561.035042620348, 'split4_test_neg_root_mean_squared_error': -37019.65542394431, 'mean_test_neg_root_mean_squared_error': -38007.64568278337, 'std_test_neg_root_mean_squared_error': 7097.30797794541, 'rank_test_neg_root_mean_squared_error': 5, 'split0_train_neg_root_mean_squared_error': -25946.24356312932, 'split1_train_neg_root_mean_squared_error': -26194.946229267855, 'split2_train_neg_root_mean_squared_error': -25175.38197926721, 'split3_train_neg_root_mean_squared_error': -27379.82119901198, 'split4_train_neg_root_mean_squared_error': -25891.447176041936, 'mean_train_neg_root_mean_squared_error': -26117.56802934366, 'std_train_neg_root_mean_squared_error': 716.5846378679105, 'split0_test_neg_mean_absolute_error': -22006.219496633417, 'split1_test_neg_mean_absolute_error': -21800.69098206259, 'split2_test_neg_mean_absolute_error': -20643.447881571876, 'split3_test_neg_mean_absolute_error': -19618.765959543838, 'split4_test_neg_mean_absolute_error': -22009.514929104444, 'mean_test_neg_mean_absolute_error': -21215.727849783238, 'std_test_neg_mean_absolute_error': 946.0389503668721, 'rank_test_neg_mean_absolute_error': 29, 'split0_train_neg_mean_absolute_error': -16612.94309194894, 'split1_train_neg_mean_absolute_error': -16882.587372655984, 'split2_train_neg_mean_absolute_error': -16476.35017963566, 'split3_train_neg_mean_absolute_error': -17633.46385167626, 'split4_train_neg_mean_absolute_error': -17088.023564073847, 'mean_train_neg_mean_absolute_error': -16938.67361199814, 'std_train_neg_mean_absolute_error': 406.94664991457745, 'split0_test_r2': 0.8118673785719022, 'split1_test_r2': 0.7878971311640839, 'split2_test_r2': 0.44755547901226755, 'split3_test_r2': 0.8780019491901473, 'split4_test_r2': 0.8448321076081968, 'mean_test_r2': 0.7540308091093195, 'std_test_r2': 0.15622601824077612, 'rank_test_r2': 7, 'split0_train_r2': 0.9000258092843911, 'split1_train_r2': 0.8992358763022061, 'split2_train_r2': 0.9131993511082175, 'split3_train_r2': 0.8898142792496301, 'split4_train_r2': 0.892914916550184, 'mean_train_r2': 0.8990380464989258, 'std_train_r2': 0.008051434193072955}
Logging parameters (RIDGE__alpha_5.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_5.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_5.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_5.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 20:01:12 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_5.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/9a3bea18dfee4f3f83c83535c358336f
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.4575532913208008, 'std_fit_time': 0.13437334423381397, 'mean_score_time': 0.21383004188537597, 'std_score_time': 0.076382277454564, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 5.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 5, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.20040585976927433, 'split1_test_neg_root_mean_squared_log_error': -0.7574631316485414, 'split2_test_neg_root_mean_squared_log_error': -0.19257448990171439, 'split3_test_neg_root_mean_squared_log_error': -0.1610526159146026, 'split4_test_neg_root_mean_squared_log_error': -0.16594957717100822, 'mean_test_neg_root_mean_squared_log_error': -0.2954891348810282, 'std_test_neg_root_mean_squared_log_error': 0.23147609020806606, 'rank_test_neg_root_mean_squared_log_error': 32, 'split0_train_neg_root_mean_squared_log_error': -0.13783245544766165, 'split1_train_neg_root_mean_squared_log_error': -0.1433722717863129, 'split2_train_neg_root_mean_squared_log_error': -0.13590319469191398, 'split3_train_neg_root_mean_squared_log_error': -0.14991690317492792, 'split4_train_neg_root_mean_squared_log_error': -0.1423995237353229, 'mean_train_neg_root_mean_squared_log_error': -0.14188486976722786, 'std_train_neg_root_mean_squared_log_error': 0.0048824848726795, 'split0_test_neg_root_mean_squared_error': -36330.16413878421, 'split1_test_neg_root_mean_squared_error': -37584.5976936131, 'split2_test_neg_root_mean_squared_error': -50599.004396035954, 'split3_test_neg_root_mean_squared_error': -28561.41249689184, 'split4_test_neg_root_mean_squared_error': -37042.02545061331, 'mean_test_neg_root_mean_squared_error': -38023.440835187685, 'std_test_neg_root_mean_squared_error': 7095.036639485632, 'rank_test_neg_root_mean_squared_error': 7, 'split0_train_neg_root_mean_squared_error': -25928.10279300621, 'split1_train_neg_root_mean_squared_error': -26203.849557596746, 'split2_train_neg_root_mean_squared_error': -25175.902183554816, 'split3_train_neg_root_mean_squared_error': -27379.450262306742, 'split4_train_neg_root_mean_squared_error': -25890.617581546005, 'mean_train_neg_root_mean_squared_error': -26115.584475602103, 'std_train_neg_root_mean_squared_error': 717.4830654753513, 'split0_test_neg_mean_absolute_error': -22051.0845890358, 'split1_test_neg_mean_absolute_error': -21755.163427098047, 'split2_test_neg_mean_absolute_error': -20630.999927183064, 'split3_test_neg_mean_absolute_error': -19629.016743079042, 'split4_test_neg_mean_absolute_error': -22013.595311968595, 'mean_test_neg_mean_absolute_error': -21215.97199967291, 'std_test_neg_mean_absolute_error': 947.0969002866243, 'rank_test_neg_mean_absolute_error': 30, 'split0_train_neg_mean_absolute_error': -16592.862024535734, 'split1_train_neg_mean_absolute_error': -16882.007818288104, 'split2_train_neg_mean_absolute_error': -16468.521934623135, 'split3_train_neg_mean_absolute_error': -17621.439569252303, 'split4_train_neg_mean_absolute_error': -17089.400258163772, 'mean_train_neg_mean_absolute_error': -16930.84632097261, 'std_train_neg_mean_absolute_error': 408.0247070372405, 'split0_test_r2': 0.8108926104883771, 'split1_test_r2': 0.7883997940509395, 'split2_test_r2': 0.4474006441929842, 'split3_test_r2': 0.8779987245878451, 'split4_test_r2': 0.844644523007396, 'mean_test_r2': 0.7538672592655085, 'std_test_r2': 0.1562147912909299, 'rank_test_r2': 9, 'split0_train_r2': 0.9001655578225131, 'split1_train_r2': 0.8991673677790918, 'split2_train_r2': 0.913195763910512, 'split3_train_r2': 0.8898172647805479, 'split4_train_r2': 0.8929217787214635, 'mean_train_r2': 0.8990535466028258, 'std_train_r2': 0.008051823567890009}
Logging parameters (RIDGE__alpha_5.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_5.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_5.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_5.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 20:03:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_5.0__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/3f1e0c6a9aca4d398eae5333d2f63a42
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.514431095123291, 'std_fit_time': 0.13630971215622803, 'mean_score_time': 0.19095249176025392, 'std_score_time': 0.050825537237442, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 10.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 10, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.20212941737093287, 'split1_test_neg_root_mean_squared_log_error': -0.24931296366923886, 'split2_test_neg_root_mean_squared_log_error': -0.19005624829745296, 'split3_test_neg_root_mean_squared_log_error': -0.15338931245796966, 'split4_test_neg_root_mean_squared_log_error': -0.1654563114200563, 'mean_test_neg_root_mean_squared_log_error': -0.19206885064313012, 'std_test_neg_root_mean_squared_log_error': 0.03342600175117939, 'rank_test_neg_root_mean_squared_log_error': 23, 'split0_train_neg_root_mean_squared_log_error': -0.14159203825452163, 'split1_train_neg_root_mean_squared_log_error': -0.14505973492529367, 'split2_train_neg_root_mean_squared_log_error': -0.1361548089967256, 'split3_train_neg_root_mean_squared_log_error': -0.1545015186165806, 'split4_train_neg_root_mean_squared_log_error': -0.1448489316084656, 'mean_train_neg_root_mean_squared_log_error': -0.1444314064803174, 'std_train_neg_root_mean_squared_log_error': 0.00597562314962002, 'split0_test_neg_root_mean_squared_error': -36280.0531293678, 'split1_test_neg_root_mean_squared_error': -37463.893575762726, 'split2_test_neg_root_mean_squared_error': -50321.83663277966, 'split3_test_neg_root_mean_squared_error': -28467.854656008716, 'split4_test_neg_root_mean_squared_error': -36719.23950651426, 'mean_test_neg_root_mean_squared_error': -37850.575500086634, 'std_test_neg_root_mean_squared_error': 7035.108943514571, 'rank_test_neg_root_mean_squared_error': 1, 'split0_train_neg_root_mean_squared_error': -26884.630315359584, 'split1_train_neg_root_mean_squared_error': -27148.813451925504, 'split2_train_neg_root_mean_squared_error': -25949.855796115255, 'split3_train_neg_root_mean_squared_error': -28419.38131765225, 'split4_train_neg_root_mean_squared_error': -26947.19916234401, 'mean_train_neg_root_mean_squared_error': -27069.97600867932, 'std_train_neg_root_mean_squared_error': 791.35409280103, 'split0_test_neg_mean_absolute_error': -21589.003085607957, 'split1_test_neg_mean_absolute_error': -21585.911445483976, 'split2_test_neg_mean_absolute_error': -20464.36559492255, 'split3_test_neg_mean_absolute_error': -19342.91174971688, 'split4_test_neg_mean_absolute_error': -21633.88256486273, 'mean_test_neg_mean_absolute_error': -20923.21488811882, 'std_test_neg_mean_absolute_error': 905.0292681386375, 'rank_test_neg_mean_absolute_error': 27, 'split0_train_neg_mean_absolute_error': -16873.136893604536, 'split1_train_neg_mean_absolute_error': -17199.509387830745, 'split2_train_neg_mean_absolute_error': -16691.76046674, 'split3_train_neg_mean_absolute_error': -17857.03407830933, 'split4_train_neg_mean_absolute_error': -17363.45993450549, 'mean_train_neg_mean_absolute_error': -17196.98015219802, 'std_train_neg_mean_absolute_error': 405.83604744668236, 'split0_test_r2': 0.8114139308248896, 'split1_test_r2': 0.7897567330564019, 'split2_test_r2': 0.45343804501128937, 'split3_test_r2': 0.8787966880191871, 'split4_test_r2': 0.8473402759501683, 'mean_test_r2': 0.7561491345723873, 'std_test_r2': 0.1543864752860356, 'rank_test_r2': 3, 'split0_train_r2': 0.8926635928879346, 'split1_train_r2': 0.8917637800620632, 'split2_train_r2': 0.907776684365253, 'split3_train_r2': 0.8812883504112764, 'split4_train_r2': 0.8840038452519906, 'mean_train_r2': 0.8914992505957036, 'std_train_r2': 0.009239308445733544}
Logging parameters (RIDGE__alpha_10.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_10.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_10.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_10.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 20:06:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_10.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/8ae48e81cdea432b8542ff1af1c1b877
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.5870846748352051, 'std_fit_time': 0.17786973429645486, 'mean_score_time': 0.17647809982299806, 'std_score_time': 0.06352156651905685, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 10.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 10, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.20216758423544284, 'split1_test_neg_root_mean_squared_log_error': -0.25128934488877636, 'split2_test_neg_root_mean_squared_log_error': -0.1900754284840454, 'split3_test_neg_root_mean_squared_log_error': -0.15343953750887165, 'split4_test_neg_root_mean_squared_log_error': -0.16553119568236233, 'mean_test_neg_root_mean_squared_log_error': -0.1925006181598997, 'std_test_neg_root_mean_squared_log_error': 0.03408390804725926, 'rank_test_neg_root_mean_squared_log_error': 24, 'split0_train_neg_root_mean_squared_log_error': -0.14155967378058432, 'split1_train_neg_root_mean_squared_log_error': -0.14503314459106942, 'split2_train_neg_root_mean_squared_log_error': -0.13614691288606018, 'split3_train_neg_root_mean_squared_log_error': -0.15450381938342736, 'split4_train_neg_root_mean_squared_log_error': -0.14479687461054408, 'mean_train_neg_root_mean_squared_log_error': -0.1444080850503371, 'std_train_neg_root_mean_squared_log_error': 0.005980403343678457, 'split0_test_neg_root_mean_squared_error': -36374.78222447633, 'split1_test_neg_root_mean_squared_error': -37418.89994216467, 'split2_test_neg_root_mean_squared_error': -50331.57347523596, 'split3_test_neg_root_mean_squared_error': -28469.268125691786, 'split4_test_neg_root_mean_squared_error': -36745.685766688206, 'mean_test_neg_root_mean_squared_error': -37868.04190685139, 'std_test_neg_root_mean_squared_error': 7033.744437130814, 'rank_test_neg_root_mean_squared_error': 3, 'split0_train_neg_root_mean_squared_error': -26867.44764899497, 'split1_train_neg_root_mean_squared_error': -27158.35716486983, 'split2_train_neg_root_mean_squared_error': -25950.357800371643, 'split3_train_neg_root_mean_squared_error': -28419.604054326122, 'split4_train_neg_root_mean_squared_error': -26946.485636137062, 'mean_train_neg_root_mean_squared_error': -27068.450460939923, 'std_train_neg_root_mean_squared_error': 792.3519413553051, 'split0_test_neg_mean_absolute_error': -21633.219147542954, 'split1_test_neg_mean_absolute_error': -21535.50662862151, 'split2_test_neg_mean_absolute_error': -20449.351387871764, 'split3_test_neg_mean_absolute_error': -19355.797918984026, 'split4_test_neg_mean_absolute_error': -21642.528158797224, 'mean_test_neg_mean_absolute_error': -20923.280648363496, 'std_test_neg_mean_absolute_error': 903.0793271510911, 'rank_test_neg_mean_absolute_error': 28, 'split0_train_neg_mean_absolute_error': -16849.62000496049, 'split1_train_neg_mean_absolute_error': -17198.065610319914, 'split2_train_neg_mean_absolute_error': -16683.312665368576, 'split3_train_neg_mean_absolute_error': -17843.793718091594, 'split4_train_neg_mean_absolute_error': -17365.982236889406, 'mean_train_neg_mean_absolute_error': -17188.154847125996, 'std_train_neg_mean_absolute_error': 407.689735151577, 'split0_test_r2': 0.8104278291617832, 'split1_test_r2': 0.7902614284943567, 'split2_test_r2': 0.4532265144764549, 'split3_test_r2': 0.8787846518849497, 'split4_test_r2': 0.8471202968483591, 'mean_test_r2': 0.7559641441731808, 'std_test_r2': 0.15439364651037574, 'rank_test_r2': 4, 'split0_train_r2': 0.8928007520210384, 'split1_train_r2': 0.891687669407891, 'split2_train_r2': 0.9077731161801227, 'split3_train_r2': 0.8812864896007753, 'split4_train_r2': 0.884009988020302, 'mean_train_r2': 0.891511603046026, 'std_train_r2': 0.009240745498241696}
Logging parameters (RIDGE__alpha_10.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_10.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_10.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_10.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 20:08:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_10.0__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/683f404711cb45b69748ae03072c1866
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.32910728454589844, 'std_fit_time': 0.06183527203924866, 'mean_score_time': 0.17743782997131347, 'std_score_time': 0.050303912591361494, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 25.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 25, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.1995712651953901, 'split1_test_neg_root_mean_squared_log_error': -0.19121380456530926, 'split2_test_neg_root_mean_squared_log_error': -0.18720646621623216, 'split3_test_neg_root_mean_squared_log_error': -0.1454221613581368, 'split4_test_neg_root_mean_squared_log_error': -0.17936334977683688, 'mean_test_neg_root_mean_squared_log_error': -0.18055540942238105, 'std_test_neg_root_mean_squared_log_error': 0.018736097993018546, 'rank_test_neg_root_mean_squared_log_error': 21, 'split0_train_neg_root_mean_squared_log_error': -0.14965986378429708, 'split1_train_neg_root_mean_squared_log_error': -0.14804792772582182, 'split2_train_neg_root_mean_squared_log_error': -0.1391880902782405, 'split3_train_neg_root_mean_squared_log_error': -0.16436881289525335, 'split4_train_neg_root_mean_squared_log_error': -0.1474086217435862, 'mean_train_neg_root_mean_squared_log_error': -0.14973466328543977, 'std_train_neg_root_mean_squared_log_error': 0.008168839306369914, 'split0_test_neg_root_mean_squared_error': -36351.59957552014, 'split1_test_neg_root_mean_squared_error': -37390.154859400514, 'split2_test_neg_root_mean_squared_error': -50225.32458507386, 'split3_test_neg_root_mean_squared_error': -28554.554751696574, 'split4_test_neg_root_mean_squared_error': -36737.383243493925, 'mean_test_neg_root_mean_squared_error': -37851.803403036996, 'std_test_neg_root_mean_squared_error': 6974.934008592486, 'rank_test_neg_root_mean_squared_error': 2, 'split0_train_neg_root_mean_squared_error': -28251.551687620304, 'split1_train_neg_root_mean_squared_error': -28568.007588548473, 'split2_train_neg_root_mean_squared_error': -27146.790579861292, 'split3_train_neg_root_mean_squared_error': -29914.20246659692, 'split4_train_neg_root_mean_squared_error': -28477.207626556345, 'mean_train_neg_root_mean_squared_error': -28471.551989836666, 'std_train_neg_root_mean_squared_error': 882.4929453747915, 'split0_test_neg_mean_absolute_error': -21099.29002201698, 'split1_test_neg_mean_absolute_error': -20959.790421173922, 'split2_test_neg_mean_absolute_error': -20253.81226758524, 'split3_test_neg_mean_absolute_error': -18948.11225742196, 'split4_test_neg_mean_absolute_error': -21335.069429827276, 'mean_test_neg_mean_absolute_error': -20519.214879605075, 'std_test_neg_mean_absolute_error': 864.2933092057069, 'rank_test_neg_mean_absolute_error': 24, 'split0_train_neg_mean_absolute_error': -17216.640813788246, 'split1_train_neg_mean_absolute_error': -17635.693912422645, 'split2_train_neg_mean_absolute_error': -17014.707170771824, 'split3_train_neg_mean_absolute_error': -18139.337292135526, 'split4_train_neg_mean_absolute_error': -17729.983541598267, 'mean_train_neg_mean_absolute_error': -17547.272546143304, 'std_train_neg_mean_absolute_error': 396.1528823084226, 'split0_test_r2': 0.8106693912749307, 'split1_test_r2': 0.7905835457610185, 'split2_test_r2': 0.45553253252100656, 'split3_test_r2': 0.87805730384879, 'split4_test_r2': 0.8471893740126565, 'mean_test_r2': 0.7564064294836804, 'std_test_r2': 0.15341324872646814, 'rank_test_r2': 1, 'split0_train_r2': 0.8814712981249597, 'split1_train_r2': 0.8801519934176589, 'split2_train_r2': 0.8990728941653742, 'split3_train_r2': 0.8684717751033086, 'split4_train_r2': 0.8704578407608055, 'mean_train_r2': 0.8799251603144214, 'std_train_r2': 0.010861748287796385}
Logging parameters (RIDGE__alpha_25.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_25.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_25.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_25.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 20:10:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_25.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/92d8ebc38cb3478ca3895e7cf097f484
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.33578786849975584, 'std_fit_time': 0.03482845454214345, 'mean_score_time': 0.14497294425964355, 'std_score_time': 0.008369528602470436, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 25.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 25, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.1995954319780571, 'split1_test_neg_root_mean_squared_log_error': -0.19153239344711043, 'split2_test_neg_root_mean_squared_log_error': -0.18723051315933148, 'split3_test_neg_root_mean_squared_log_error': -0.14545039638196575, 'split4_test_neg_root_mean_squared_log_error': -0.17957172704945654, 'mean_test_neg_root_mean_squared_log_error': -0.18067609240318427, 'std_test_neg_root_mean_squared_log_error': 0.01876608854699412, 'rank_test_neg_root_mean_squared_log_error': 22, 'split0_train_neg_root_mean_squared_log_error': -0.1495743933299412, 'split1_train_neg_root_mean_squared_log_error': -0.14807515030005658, 'split2_train_neg_root_mean_squared_log_error': -0.13915074305922678, 'split3_train_neg_root_mean_squared_log_error': -0.16442965593312564, 'split4_train_neg_root_mean_squared_log_error': -0.14736877420610883, 'mean_train_neg_root_mean_squared_log_error': -0.1497197433656918, 'std_train_neg_root_mean_squared_log_error': 0.00820168475611376, 'split0_test_neg_root_mean_squared_error': -36444.824595510436, 'split1_test_neg_root_mean_squared_error': -37344.32857486509, 'split2_test_neg_root_mean_squared_error': -50238.97611154021, 'split3_test_neg_root_mean_squared_error': -28556.737208363662, 'split4_test_neg_root_mean_squared_error': -36769.71703858802, 'mean_test_neg_root_mean_squared_error': -37870.91670577349, 'std_test_neg_root_mean_squared_error': 6974.905126926411, 'rank_test_neg_root_mean_squared_error': 4, 'split0_train_neg_root_mean_squared_error': -28235.039293883878, 'split1_train_neg_root_mean_squared_error': -28579.81305788699, 'split2_train_neg_root_mean_squared_error': -27147.141670058794, 'split3_train_neg_root_mean_squared_error': -29915.829681107996, 'split4_train_neg_root_mean_squared_error': -28477.16632904403, 'mean_train_neg_root_mean_squared_error': -28470.998006396334, 'std_train_neg_root_mean_squared_error': 884.0463161121023, 'split0_test_neg_mean_absolute_error': -21145.134193868467, 'split1_test_neg_mean_absolute_error': -20902.342536779168, 'split2_test_neg_mean_absolute_error': -20237.992181949667, 'split3_test_neg_mean_absolute_error': -18964.52627461413, 'split4_test_neg_mean_absolute_error': -21345.47402683422, 'mean_test_neg_mean_absolute_error': -20519.09384280913, 'std_test_neg_mean_absolute_error': 862.2538789654986, 'rank_test_neg_mean_absolute_error': 23, 'split0_train_neg_mean_absolute_error': -17190.482054853426, 'split1_train_neg_mean_absolute_error': -17633.20719651349, 'split2_train_neg_mean_absolute_error': -17004.4252676972, 'split3_train_neg_mean_absolute_error': -18124.287003721503, 'split4_train_neg_mean_absolute_error': -17730.674649298286, 'mean_train_neg_mean_absolute_error': -17536.615234416782, 'std_train_neg_mean_absolute_error': 398.84370642025027, 'split0_test_r2': 0.8096970553955437, 'split1_test_r2': 0.7910965629994854, 'split2_test_r2': 0.4552365136403369, 'split3_test_r2': 0.8780386627021837, 'split4_test_r2': 0.846920268192987, 'mean_test_r2': 0.7561978125861073, 'std_test_r2': 0.15344937401832184, 'rank_test_r2': 2, 'split0_train_r2': 0.8816098123310914, 'split1_train_r2': 0.8800529207538041, 'split2_train_r2': 0.8990702835623599, 'split3_train_r2': 0.86845746548182, 'split4_train_r2': 0.870458216483391, 'mean_train_r2': 0.8799297397224933, 'std_train_r2': 0.010867576222364962}
Logging parameters (RIDGE__alpha_25.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_25.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_25.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_25.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 20:13:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_25.0__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/b6256459debf423f94523dcb2dcd1605
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.29763994216918943, 'std_fit_time': 0.010171504795747232, 'mean_score_time': 0.14486842155456542, 'std_score_time': 0.003778480052400126, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 50.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 50, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.19072996705500384, 'split1_test_neg_root_mean_squared_log_error': -0.17285292650156675, 'split2_test_neg_root_mean_squared_log_error': -0.1857217742672619, 'split3_test_neg_root_mean_squared_log_error': -0.1414964769530604, 'split4_test_neg_root_mean_squared_log_error': -0.2980046082045457, 'mean_test_neg_root_mean_squared_log_error': -0.19776115059628774, 'std_test_neg_root_mean_squared_log_error': 0.05297030875004122, 'rank_test_neg_root_mean_squared_log_error': 25, 'split0_train_neg_root_mean_squared_log_error': -0.17866205462414927, 'split1_train_neg_root_mean_squared_log_error': -0.1553348269905323, 'split2_train_neg_root_mean_squared_log_error': -0.14863243920735889, 'split3_train_neg_root_mean_squared_log_error': -0.3782486886134442, 'split4_train_neg_root_mean_squared_log_error': -0.14876872148803497, 'mean_train_neg_root_mean_squared_log_error': -0.2019293461847039, 'std_train_neg_root_mean_squared_log_error': 0.08884541507753241, 'split0_test_neg_root_mean_squared_error': -36363.11619807779, 'split1_test_neg_root_mean_squared_error': -37502.21355593555, 'split2_test_neg_root_mean_squared_error': -50161.967957403125, 'split3_test_neg_root_mean_squared_error': -28876.54815245797, 'split4_test_neg_root_mean_squared_error': -37142.027528839884, 'mean_test_neg_root_mean_squared_error': -38009.17467854287, 'std_test_neg_root_mean_squared_error': 6852.936801457385, 'rank_test_neg_root_mean_squared_error': 6, 'split0_train_neg_root_mean_squared_error': -29446.49825042096, 'split1_train_neg_root_mean_squared_error': -29822.726900560145, 'split2_train_neg_root_mean_squared_error': -28137.58774996353, 'split3_train_neg_root_mean_squared_error': -31168.74021738775, 'split4_train_neg_root_mean_squared_error': -29753.995817064715, 'mean_train_neg_root_mean_squared_error': -29665.909787079425, 'std_train_neg_root_mean_squared_error': 966.9291317953555, 'split0_test_neg_mean_absolute_error': -20574.473730374484, 'split1_test_neg_mean_absolute_error': -20462.884395330013, 'split2_test_neg_mean_absolute_error': -20180.41738310777, 'split3_test_neg_mean_absolute_error': -18979.74559532093, 'split4_test_neg_mean_absolute_error': -21310.651192281548, 'mean_test_neg_mean_absolute_error': -20301.63445928295, 'std_test_neg_mean_absolute_error': 759.0311357802616, 'rank_test_neg_mean_absolute_error': 22, 'split0_train_neg_mean_absolute_error': -17475.273647926908, 'split1_train_neg_mean_absolute_error': -18001.695416462786, 'split2_train_neg_mean_absolute_error': -17335.05431926098, 'split3_train_neg_mean_absolute_error': -18393.5098117504, 'split4_train_neg_mean_absolute_error': -18019.68709135026, 'mean_train_neg_mean_absolute_error': -17845.044057350264, 'std_train_neg_mean_absolute_error': 387.98819828126875, 'split0_test_r2': 0.810549407858466, 'split1_test_r2': 0.7893264180325237, 'split2_test_r2': 0.45690530076834845, 'split3_test_r2': 0.8752916416407815, 'split4_test_r2': 0.8438045666923459, 'mean_test_r2': 0.7551754669984931, 'std_test_r2': 0.15197411988170242, 'rank_test_r2': 5, 'split0_train_r2': 0.8712325104811666, 'split1_train_r2': 0.8693932529676633, 'split2_train_r2': 0.8915712230132009, 'split3_train_r2': 0.857208419728525, 'split4_train_r2': 0.8585812729974265, 'mean_train_r2': 0.8695973358375964, 'std_train_r2': 0.012332121037316754}
Logging parameters (RIDGE__alpha_50.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_50.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_50.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_50.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 20:15:55 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_50.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/645c1047ee8047fa9d0df55706da7da2
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.30796380043029786, 'std_fit_time': 0.01261996221823026, 'mean_score_time': 0.14619407653808594, 'std_score_time': 0.008749769626553607, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 50.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 50, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.1907294347089284, 'split1_test_neg_root_mean_squared_log_error': -0.17290155162241289, 'split2_test_neg_root_mean_squared_log_error': -0.18575065639778274, 'split3_test_neg_root_mean_squared_log_error': -0.1414994483328657, 'split4_test_neg_root_mean_squared_log_error': -0.30197457885940465, 'mean_test_neg_root_mean_squared_log_error': -0.1985711339842789, 'std_test_neg_root_mean_squared_log_error': 0.054468769155985884, 'rank_test_neg_root_mean_squared_log_error': 26, 'split0_train_neg_root_mean_squared_log_error': -0.1782534532027369, 'split1_train_neg_root_mean_squared_log_error': -0.15552394215025134, 'split2_train_neg_root_mean_squared_log_error': -0.14855649570603746, 'split3_train_neg_root_mean_squared_log_error': -0.37822768323426903, 'split4_train_neg_root_mean_squared_log_error': -0.14874155758887048, 'mean_train_neg_root_mean_squared_log_error': -0.20186062637643304, 'std_train_neg_root_mean_squared_log_error': 0.08885121438720948, 'split0_test_neg_root_mean_squared_error': -36450.606825380215, 'split1_test_neg_root_mean_squared_error': -37457.4521232279, 'split2_test_neg_root_mean_squared_error': -50178.05755612174, 'split3_test_neg_root_mean_squared_error': -28879.18570251458, 'split4_test_neg_root_mean_squared_error': -37177.679917378206, 'mean_test_neg_root_mean_squared_error': -38028.59642492453, 'std_test_neg_root_mean_squared_error': 6853.633171366372, 'rank_test_neg_root_mean_squared_error': 8, 'split0_train_neg_root_mean_squared_error': -29431.12338870627, 'split1_train_neg_root_mean_squared_error': -29836.946037414444, 'split2_train_neg_root_mean_squared_error': -28138.078816924284, 'split3_train_neg_root_mean_squared_error': -31171.99793449562, 'split4_train_neg_root_mean_squared_error': -29754.80058024193, 'mean_train_neg_root_mean_squared_error': -29666.589351556508, 'std_train_neg_root_mean_squared_error': 969.0042618081831, 'split0_test_neg_mean_absolute_error': -20612.118826409078, 'split1_test_neg_mean_absolute_error': -20397.435982634248, 'split2_test_neg_mean_absolute_error': -20158.750758773775, 'split3_test_neg_mean_absolute_error': -19002.76985720448, 'split4_test_neg_mean_absolute_error': -21317.0875231198, 'mean_test_neg_mean_absolute_error': -20297.632589628276, 'std_test_neg_mean_absolute_error': 754.2026691230658, 'rank_test_neg_mean_absolute_error': 21, 'split0_train_neg_mean_absolute_error': -17453.186403784683, 'split1_train_neg_mean_absolute_error': -18007.3501325852, 'split2_train_neg_mean_absolute_error': -17322.593640633448, 'split3_train_neg_mean_absolute_error': -18378.311285447784, 'split4_train_neg_mean_absolute_error': -18020.891714739162, 'mean_train_neg_mean_absolute_error': -17836.466635438053, 'std_train_neg_mean_absolute_error': 391.86186213571307, 'split0_test_r2': 0.8096366647818425, 'split1_test_r2': 0.7898290242931306, 'split2_test_r2': 0.4565568464500469, 'split3_test_r2': 0.8752688591698502, 'split4_test_r2': 0.8435045608313035, 'mean_test_r2': 0.7549591911052347, 'std_test_r2': 0.15202906920695494, 'rank_test_r2': 6, 'split0_train_r2': 0.8713669417793999, 'split1_train_r2': 0.8692686796553675, 'split2_train_r2': 0.8915674383067734, 'split3_train_r2': 0.8571785693797209, 'split4_train_r2': 0.8585736229242151, 'mean_train_r2': 0.8695910504090953, 'std_train_r2': 0.01234238819499992}
Logging parameters (RIDGE__alpha_50.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_50.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_50.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_50.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 20:18:23 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_50.0__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/a7d279e82d4b44b8b65a72e61a9dd83c
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.2905411720275879, 'std_fit_time': 0.0023217009919452277, 'mean_score_time': 0.15196237564086915, 'std_score_time': 0.020306178897479165, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 100.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 100, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.17871210568065343, 'split1_test_neg_root_mean_squared_log_error': -0.16413377218958575, 'split2_test_neg_root_mean_squared_log_error': -0.18445728815123802, 'split3_test_neg_root_mean_squared_log_error': -0.14061448159963313, 'split4_test_neg_root_mean_squared_log_error': -0.7108147212987928, 'mean_test_neg_root_mean_squared_log_error': -0.27574647378398065, 'std_test_neg_root_mean_squared_log_error': 0.21806045697063975, 'rank_test_neg_root_mean_squared_log_error': 30, 'split0_train_neg_root_mean_squared_log_error': -0.3744388401637872, 'split1_train_neg_root_mean_squared_log_error': -0.3763278917422275, 'split2_train_neg_root_mean_squared_log_error': -0.3725352924342655, 'split3_train_neg_root_mean_squared_log_error': -0.37837146799771626, 'split4_train_neg_root_mean_squared_log_error': -0.14981427179477796, 'mean_train_neg_root_mean_squared_log_error': -0.3302975528265549, 'std_train_neg_root_mean_squared_log_error': 0.09026249281681506, 'split0_test_neg_root_mean_squared_error': -36385.065901331945, 'split1_test_neg_root_mean_squared_error': -37754.86066946259, 'split2_test_neg_root_mean_squared_error': -49757.49278327379, 'split3_test_neg_root_mean_squared_error': -29499.947029054023, 'split4_test_neg_root_mean_squared_error': -37916.58102753914, 'mean_test_neg_root_mean_squared_error': -38262.7894821323, 'std_test_neg_root_mean_squared_error': 6524.098553170537, 'rank_test_neg_root_mean_squared_error': 9, 'split0_train_neg_root_mean_squared_error': -30816.59525762064, 'split1_train_neg_root_mean_squared_error': -31216.76308152527, 'split2_train_neg_root_mean_squared_error': -29206.67088171456, 'split3_train_neg_root_mean_squared_error': -32525.410537542535, 'split4_train_neg_root_mean_squared_error': -31110.37172661209, 'mean_train_neg_root_mean_squared_error': -30975.16229700302, 'std_train_neg_root_mean_squared_error': 1061.3790584103604, 'split0_test_neg_mean_absolute_error': -20253.30427983044, 'split1_test_neg_mean_absolute_error': -20125.818551111162, 'split2_test_neg_mean_absolute_error': -20192.629846470136, 'split3_test_neg_mean_absolute_error': -19254.496412212004, 'split4_test_neg_mean_absolute_error': -21382.577249740345, 'mean_test_neg_mean_absolute_error': -20241.765267872815, 'std_test_neg_mean_absolute_error': 677.0735338043445, 'rank_test_neg_mean_absolute_error': 20, 'split0_train_neg_mean_absolute_error': -17886.6033801154, 'split1_train_neg_mean_absolute_error': -18546.38311295943, 'split2_train_neg_mean_absolute_error': -17721.665099727987, 'split3_train_neg_mean_absolute_error': -18659.125411173674, 'split4_train_neg_mean_absolute_error': -18413.416457076277, 'mean_train_neg_mean_absolute_error': -18245.438692210555, 'std_train_neg_mean_absolute_error': 372.29620806668237, 'split0_test_r2': 0.8103206244225517, 'split1_test_r2': 0.786478300250616, 'split2_test_r2': 0.46562835119905555, 'split3_test_r2': 0.8698490087700805, 'split4_test_r2': 0.8372220942998005, 'mean_test_r2': 0.7538996757884209, 'std_test_r2': 0.1467868659264912, 'rank_test_r2': 8, 'split0_train_r2': 0.858971065452028, 'split1_train_r2': 0.8568976893022775, 'split2_train_r2': 0.8831752264141126, 'split3_train_r2': 0.8445074179465041, 'split4_train_r2': 0.8453938629719471, 'mean_train_r2': 0.8577890524173739, 'std_train_r2': 0.013976351804498606}
Logging parameters (RIDGE__alpha_100.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_100.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_100.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_100.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 20:20:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_100.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/3c8ecf8152b5481ba9c4145bf10c7a27
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.30811328887939454, 'std_fit_time': 0.010570547129199928, 'mean_score_time': 0.1484532356262207, 'std_score_time': 0.009437222919704148, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 100.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 100, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.17872618697691708, 'split1_test_neg_root_mean_squared_log_error': -0.16407206409860184, 'split2_test_neg_root_mean_squared_log_error': -0.18449534802242082, 'split3_test_neg_root_mean_squared_log_error': -0.1406017853480366, 'split4_test_neg_root_mean_squared_log_error': -0.7108214879830429, 'mean_test_neg_root_mean_squared_log_error': -0.2757433744858038, 'std_test_neg_root_mean_squared_log_error': 0.21806661024934057, 'rank_test_neg_root_mean_squared_log_error': 29, 'split0_train_neg_root_mean_squared_log_error': -0.37440548917971916, 'split1_train_neg_root_mean_squared_log_error': -0.3763290614128937, 'split2_train_neg_root_mean_squared_log_error': -0.3725245656397738, 'split3_train_neg_root_mean_squared_log_error': -0.3783507238460419, 'split4_train_neg_root_mean_squared_log_error': -0.14980060648176827, 'mean_train_neg_root_mean_squared_log_error': -0.3302820893120394, 'std_train_neg_root_mean_squared_log_error': 0.09026160217104079, 'split0_test_neg_root_mean_squared_error': -36463.22970337721, 'split1_test_neg_root_mean_squared_error': -37713.01891048619, 'split2_test_neg_root_mean_squared_error': -49774.76831167576, 'split3_test_neg_root_mean_squared_error': -29503.291049384443, 'split4_test_neg_root_mean_squared_error': -37952.68202151961, 'mean_test_neg_root_mean_squared_error': -38281.397999288645, 'std_test_neg_root_mean_squared_error': 6525.175364639696, 'rank_test_neg_root_mean_squared_error': 10, 'split0_train_neg_root_mean_squared_error': -30803.859855616396, 'split1_train_neg_root_mean_squared_error': -31233.153207515585, 'split2_train_neg_root_mean_squared_error': -29207.821033293167, 'split3_train_neg_root_mean_squared_error': -32530.578138998015, 'split4_train_neg_root_mean_squared_error': -31112.155124194727, 'mean_train_neg_root_mean_squared_error': -30977.513471923576, 'std_train_neg_root_mean_squared_error': 1063.7158281098484, 'split0_test_neg_mean_absolute_error': -20282.519053675183, 'split1_test_neg_mean_absolute_error': -20062.499095611114, 'split2_test_neg_mean_absolute_error': -20190.768752225933, 'split3_test_neg_mean_absolute_error': -19275.771363990025, 'split4_test_neg_mean_absolute_error': -21386.877892721397, 'mean_test_neg_mean_absolute_error': -20239.68723164473, 'std_test_neg_mean_absolute_error': 675.3966880191531, 'rank_test_neg_mean_absolute_error': 19, 'split0_train_neg_mean_absolute_error': -17869.254706782503, 'split1_train_neg_mean_absolute_error': -18550.78784917319, 'split2_train_neg_mean_absolute_error': -17709.823709997425, 'split3_train_neg_mean_absolute_error': -18647.26939940904, 'split4_train_neg_mean_absolute_error': -18415.00110640388, 'mean_train_neg_mean_absolute_error': -18238.427354353207, 'std_train_neg_mean_absolute_error': 377.25573368298876, 'split0_test_r2': 0.8095047959635245, 'split1_test_r2': 0.7869513081084317, 'split2_test_r2': 0.4652572249765796, 'split3_test_r2': 0.8698195000914192, 'split4_test_r2': 0.8369119797502502, 'mean_test_r2': 0.753688961778041, 'std_test_r2': 0.14685164655044858, 'rank_test_r2': 10, 'split0_train_r2': 0.8590876058444246, 'split1_train_r2': 0.8567473802756792, 'split2_train_r2': 0.8831660251707419, 'split3_train_r2': 0.844458005040623, 'split4_train_r2': 0.8453761369147732, 'mean_train_r2': 0.8577670306492484, 'std_train_r2': 0.013989688621433988}
Logging parameters (RIDGE__alpha_100.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_100.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_100.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_100.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 20:23:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_100.0__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/85808fce989f447ca5aa1cae10056993
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.3453166961669922, 'std_fit_time': 0.06666541227651375, 'mean_score_time': 0.14213061332702637, 'std_score_time': 0.010784083944068776, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 1000.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'mean', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 1000, 'regressor__preprocessor__num_impute__impute__strategy': 'mean'}, 'split0_test_neg_root_mean_squared_log_error': -0.16145967881978746, 'split1_test_neg_root_mean_squared_log_error': -0.1650825767281046, 'split2_test_neg_root_mean_squared_log_error': -0.17983837721431295, 'split3_test_neg_root_mean_squared_log_error': -0.15272267830705263, 'split4_test_neg_root_mean_squared_log_error': -0.7126796680256858, 'mean_test_neg_root_mean_squared_log_error': -0.2743565958189887, 'std_test_neg_root_mean_squared_log_error': 0.21933633729157537, 'rank_test_neg_root_mean_squared_log_error': 27, 'split0_train_neg_root_mean_squared_log_error': -0.3803199031866285, 'split1_train_neg_root_mean_squared_log_error': -0.3811953573161852, 'split2_train_neg_root_mean_squared_log_error': -0.3778070777864434, 'split3_train_neg_root_mean_squared_log_error': -0.3819885692014263, 'split4_train_neg_root_mean_squared_log_error': -0.15852211596100232, 'mean_train_neg_root_mean_squared_log_error': -0.3359666046903371, 'std_train_neg_root_mean_squared_log_error': 0.08873336254010918, 'split0_test_neg_root_mean_squared_error': -37809.58094605417, 'split1_test_neg_root_mean_squared_error': -39734.523622063294, 'split2_test_neg_root_mean_squared_error': -43464.33145675409, 'split3_test_neg_root_mean_squared_error': -35088.186698084966, 'split4_test_neg_root_mean_squared_error': -44068.09728725746, 'mean_test_neg_root_mean_squared_error': -40032.9440020428, 'std_test_neg_root_mean_squared_error': 3392.341512775363, 'rank_test_neg_root_mean_squared_error': 13, 'split0_train_neg_root_mean_squared_error': -36849.43313065405, 'split1_train_neg_root_mean_squared_error': -37122.7794927122, 'split2_train_neg_root_mean_squared_error': -35173.403322033526, 'split3_train_neg_root_mean_squared_error': -38054.39331676445, 'split4_train_neg_root_mean_squared_error': -36476.36811654383, 'mean_train_neg_root_mean_squared_error': -36735.27547574161, 'std_train_neg_root_mean_squared_error': 939.1209567487786, 'split0_test_neg_mean_absolute_error': -22361.619855836663, 'split1_test_neg_mean_absolute_error': -21602.49605417125, 'split2_test_neg_mean_absolute_error': -20869.373842451256, 'split3_test_neg_mean_absolute_error': -21543.85049580862, 'split4_test_neg_mean_absolute_error': -24081.930121624922, 'mean_test_neg_mean_absolute_error': -22091.854073978542, 'std_test_neg_mean_absolute_error': 1101.581895474787, 'rank_test_neg_mean_absolute_error': 36, 'split0_train_neg_mean_absolute_error': -20964.377037632978, 'split1_train_neg_mean_absolute_error': -21811.01440577472, 'split2_train_neg_mean_absolute_error': -20823.9621634136, 'split3_train_neg_mean_absolute_error': -21582.70313179087, 'split4_train_neg_mean_absolute_error': -21274.29421562188, 'mean_train_neg_mean_absolute_error': -21291.270190846808, 'std_train_neg_mean_absolute_error': 368.94208702038105, 'split0_test_r2': 0.7951775731827795, 'split1_test_r2': 0.7634993735321901, 'split2_test_r2': 0.5922514371418472, 'split3_test_r2': 0.8158690227861818, 'split4_test_r2': 0.780120006117773, 'mean_test_r2': 0.7493834825521544, 'std_test_r2': 0.08043866949519153, 'rank_test_r2': 11, 'split0_train_r2': 0.798348926331015, 'split1_train_r2': 0.7976273208893192, 'split2_train_r2': 0.8305663688381966, 'split3_train_r2': 0.7871499744707573, 'split4_train_r2': 0.7874605716396658, 'mean_train_r2': 0.8002306324337909, 'std_train_r2': 0.015904420879012938}
Logging parameters (RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)
Logging final model (RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe)

2026/04/10 20:25:47 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/049e8a2d4dd248e881aa55b6e857f0ad
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
{'mean_fit_time': 0.3234294891357422, 'std_fit_time': 0.013042760239952173, 'mean_score_time': 0.13174376487731934, 'std_score_time': 0.019831393015287548, 'param_func': None, 'param_inverse_func': None, 'param_regressor__model__alpha': 1000.0, 'param_regressor__preprocessor__num_impute__impute__strategy': 'median', 'params': {'func': None, 'inverse_func': None, 'regressor__model__alpha': 1000, 'regressor__preprocessor__num_impute__impute__strategy': 'median'}, 'split0_test_neg_root_mean_squared_log_error': -0.161501542536962, 'split1_test_neg_root_mean_squared_log_error': -0.1649819337984061, 'split2_test_neg_root_mean_squared_log_error': -0.1799165133553077, 'split3_test_neg_root_mean_squared_log_error': -0.1527321110114574, 'split4_test_neg_root_mean_squared_log_error': -0.7126732575953024, 'mean_test_neg_root_mean_squared_log_error': -0.2743610716594871, 'std_test_neg_root_mean_squared_log_error': 0.21933172142415502, 'rank_test_neg_root_mean_squared_log_error': 28, 'split0_train_neg_root_mean_squared_log_error': -0.3803103847023186, 'split1_train_neg_root_mean_squared_log_error': -0.3812006211689097, 'split2_train_neg_root_mean_squared_log_error': -0.3777996922138384, 'split3_train_neg_root_mean_squared_log_error': -0.38197846994812135, 'split4_train_neg_root_mean_squared_log_error': -0.1585180457332226, 'mean_train_neg_root_mean_squared_log_error': -0.3359614427532821, 'std_train_neg_root_mean_squared_log_error': 0.08873283154674236, 'split0_test_neg_root_mean_squared_error': -37853.82673553024, 'split1_test_neg_root_mean_squared_error': -39706.85101419985, 'split2_test_neg_root_mean_squared_error': -43475.15391938863, 'split3_test_neg_root_mean_squared_error': -35093.3073283191, 'split4_test_neg_root_mean_squared_error': -44085.273190933316, 'mean_test_neg_root_mean_squared_error': -40042.88243767423, 'std_test_neg_root_mean_squared_error': 3391.889923745278, 'rank_test_neg_root_mean_squared_error': 14, 'split0_train_neg_root_mean_squared_error': -36844.41909792427, 'split1_train_neg_root_mean_squared_error': -37136.78210060302, 'split2_train_neg_root_mean_squared_error': -35176.764984035755, 'split3_train_neg_root_mean_squared_error': -38059.2143459181, 'split4_train_neg_root_mean_squared_error': -36479.44114914107, 'mean_train_neg_root_mean_squared_error': -36739.32433552444, 'std_train_neg_root_mean_squared_error': 940.2402055997851, 'split0_test_neg_mean_absolute_error': -22371.46398357773, 'split1_test_neg_mean_absolute_error': -21560.85782281699, 'split2_test_neg_mean_absolute_error': -20885.90330776721, 'split3_test_neg_mean_absolute_error': -21554.548013234526, 'split4_test_neg_mean_absolute_error': -24077.28150977259, 'mean_test_neg_mean_absolute_error': -22090.01092743381, 'std_test_neg_mean_absolute_error': 1099.5507164828227, 'rank_test_neg_mean_absolute_error': 35, 'split0_train_neg_mean_absolute_error': -20958.26981130697, 'split1_train_neg_mean_absolute_error': -21813.99098012665, 'split2_train_neg_mean_absolute_error': -20817.396870283053, 'split3_train_neg_mean_absolute_error': -21573.49379126107, 'split4_train_neg_mean_absolute_error': -21272.430491485244, 'mean_train_neg_mean_absolute_error': -21287.1163888926, 'std_train_neg_mean_absolute_error': 371.10672987985157, 'split0_test_r2': 0.7946979152570202, 'split1_test_r2': 0.7638286745808027, 'split2_test_r2': 0.5920483560024847, 'split3_test_r2': 0.8158152761815951, 'split4_test_r2': 0.7799485726402465, 'mean_test_r2': 0.7492677589324298, 'std_test_r2': 0.08045339571161168, 'rank_test_r2': 12, 'split0_train_r2': 0.7984037991585868, 'split1_train_r2': 0.797474623286796, 'split2_train_r2': 0.8305339803989542, 'split3_train_r2': 0.7870960400316691, 'split4_train_r2': 0.7874247584193307, 'mean_train_r2': 0.8001866402590674, 'std_train_r2': 0.015910525160524387}
Logging parameters (RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging preprocessing parameters (RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging train and validation metrics (RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)
Logging final model (RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_median__ord_imp__ohe)

2026/04/10 20:28:15 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RIDGE__alpha_1000.0__prep_v1__rawY__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/bf9695052586490a8dc05359c9a3f147
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1

### Full Pipeline (Lasso) ###

In [123]:
# from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV, KFold

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Lasso(max_iter=10000))
])

param_grid = {
    'preprocessor__num_impute__impute__strategy': ['mean', 'median'],
    # 'model__alpha': [.0005, .0006, .0007, .0008, .0009, .001, .005, .01, .05, .1, .5, 1, 5, 10],
    'model__alpha': np.logspace(-4, 1, 300),
}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring={
        'neg_root_mean_squared_log_error': safe_rmsle_scorer,
        'neg_root_mean_squared_error': 'neg_root_mean_squared_error',
        'neg_mean_absolute_error': 'neg_mean_absolute_error',
        'r2': 'r2',
    },
    refit='neg_root_mean_squared_log_error',
    return_train_score=True,
    verbose=1,
    n_jobs=-1
)

search.fit(X_train, y_train)
cv_results_df = pd.DataFrame(search.cv_results_)

cv_results_df

Fitting 5 folds for each of 600 candidates, totalling 3000 fits

     mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_model__alpha param_preprocessor__preprocessor__num_impute__impute__strategy                                             params  split0_test_score  split1_test_score  split2_test_score  split3_test_score  split4_test_score  mean_test_score  std_test_score  rank_test_score  split0_train_score  split1_train_score  split2_train_score  split3_train_score  split4_train_score  mean_train_score  std_train_score
0         0.798562      0.288849         0.192542        0.053236            0.000100                                               mean              {'model__alpha': 0.0001, 'preprocessor__prepro...          -0.156672          -0.126751          -0.205040          -0.131516          -0.151069        -0.154210        0.027816              184           -0.091772           -0.092366           -0.093926           -0.093994           -0.088841         -0.092180         0.001881
1         0.494709      0.080717         0.153101        0.040209            0.000100                                             median              {'model__alpha': 0.0001, 'preprocessor__prepro...          -0.156628          -0.126733          -0.205042          -0.131520          -0.151075        -0.154200        0.027819              183           -0.091784           -0.092372           -0.093927           -0.093998           -0.088841         -0.092184         0.001882
2         0.605070      0.101625         0.159681        0.027988            0.000104                                               mean              {'model__alpha': 0.00010392556829367131, 'prep...          -0.156585          -0.126356          -0.205113          -0.130929          -0.150560        -0.153909        0.028027              178           -0.091921           -0.092515           -0.094042           -0.094112           -0.089000         -0.092318         0.001865
3         0.627594      0.091575         0.162277        0.035550            0.000104                                             median              {'model__alpha': 0.00010392556829367131, 'prep...          -0.156541          -0.126338          -0.205119          -0.130930          -0.150566        -0.153899        0.028031              177           -0.091933           -0.092521           -0.094042           -0.094116           -0.089000         -0.092322         0.001866
4         0.411241      0.058485         0.140560        0.040918            0.000108                                               mean              {'model__alpha': 0.00010800523745162529, 'prep...          -0.156482          -0.125957          -0.205170          -0.130335          -0.150103        -0.153609        0.028232              172           -0.092078           -0.092674           -0.094143           -0.094230           -0.089164         -0.092458         0.001845
5         0.460329      0.098281         0.147776        0.047190            0.000108                                             median              {'model__alpha': 0.00010800523745162529, 'prep...          -0.156440          -0.125939          -0.205177          -0.130338          -0.150107        -0.153600        0.028237              171           -0.092090           -0.092680           -0.094143           -0.094234           -0.089163         -0.092462         0.001846
6         0.462331      0.079025         0.160286        0.045095            0.000112                                               mean              {'model__alpha': 0.0001122450568085307, 'prepr...          -0.156337          -0.125553          -0.205220          -0.129715          -0.149639        -0.153293        0.028441              168           -0.092240           -0.092846           -0.094238           -0.094355           -0.089328         -0.092601         0.001825
7         0.455558      0.073185         0.119823        0.008281            0.000112                                             median              {'model__alpha': 0.0001122450568085307, 'prepr...          -0.156304          -0.125536          -0.205228          -0.129724          -0.149644        -0.153287        0.028445              167           -0.092252           -0.092852           -0.094238           -0.094359           -0.089328         -0.092606         0.001826
8         0.471180      0.173373         0.122983        0.003217            0.000117                                               mean              {'model__alpha': 0.00011665131316981962, 'prep...          -0.156127          -0.125137          -0.205257          -0.129080          -0.149141        -0.152949        0.028650              164           -0.092409           -0.093030           -0.094335           -0.094490           -0.089469         -0.092747         0.001817
9         0.557206      0.164909         0.121148        0.003691            0.000117                                             median              {'model__alpha': 0.00011665131316981962, 'prep...          -0.156096          -0.125121          -0.205262          -0.129090          -0.149147        -0.152943        0.028652              163           -0.092422           -0.093036           -0.094336           -0.094495           -0.089469         -0.092751         0.001817
10        0.506062      0.182624         0.130083        0.020510            0.000121                                               mean              {'model__alpha': 0.00012123054013376529, 'prep...          -0.155935          -0.124693          -0.205287          -0.128442          -0.148599        -0.152591        0.028863              160           -0.092588           -0.093222           -0.094436           -0.094634           -0.089623         -0.092901         0.001806
11        0.471784      0.181746         0.122868        0.004736            0.000121                                             median              {'model__alpha': 0.00012123054013376529, 'prep...          -0.155904          -0.124678          -0.205293          -0.128452          -0.148606        -0.152587        0.028866              159           -0.092600           -0.093228           -0.094437           -0.094639           -0.089623         -0.092905         0.001807
12        0.456206      0.139479         0.122834        0.004421            0.000126                                               mean              {'model__alpha': 0.0001259895277795027, 'prepr...          -0.155743          -0.124259          -0.205293          -0.127792          -0.148046        -0.152227        0.029069              156           -0.092775           -0.093427           -0.094542           -0.094788           -0.089790         -0.093064         0.001794
13        0.472820      0.149264         0.122400        0.010735            0.000126                                             median              {'model__alpha': 0.0001259895277795027, 'prepr...          -0.155712          -0.124247          -0.205300          -0.127804          -0.148053        -0.152223        0.029071              155           -0.092787           -0.093433           -0.094543           -0.094793           -0.089790         -0.093069         0.001795
14        0.424198      0.133802         0.131020        0.018263            0.000131                                               mean              {'model__alpha': 0.0001309353327353611, 'prepr...          -0.155543          -0.123830          -0.205303          -0.127144          -0.147483        -0.151861        0.029276              152           -0.092972           -0.093631           -0.094652           -0.094947           -0.089969         -0.093234         0.001779
15        0.419453      0.148578         0.128027        0.014980            0.000131                                             median              {'model__alpha': 0.0001309353327353611, 'prepr...          -0.155514          -0.123819          -0.205310          -0.127155          -0.147491        -0.151858        0.029278              151           -0.092984           -0.093637           -0.094653           -0.094952           -0.089969         -0.093239         0.001780
16        0.444983      0.122436         0.124310        0.011946            0.000136                                               mean              {'model__alpha': 0.00013607528864243332, 'prep...          -0.155334          -0.123407          -0.205317          -0.126487          -0.146917        -0.151493        0.029485              148           -0.093174           -0.093839           -0.094764           -0.095118           -0.090158         -0.093411         0.001765
17        0.441054      0.151183         0.127658        0.023160            0.000136                                             median              {'model__alpha': 0.00013607528864243332, 'prep...          -0.155306          -0.123399          -0.205323          -0.126498          -0.146924        -0.151490        0.029486              147           -0.093186           -0.093846           -0.094765           -0.095124           -0.090158         -0.093416         0.001766
18        0.408862      0.113941         0.118584        0.009555            0.000141                                               mean              {'model__alpha': 0.0001414170170289024, 'prepr...          -0.155154          -0.122997          -0.205336          -0.125829          -0.146335        -0.151130        0.029695              144           -0.093371           -0.094063           -0.094879           -0.095297           -0.090363         -0.093595         0.001747
19        0.430125      0.117938         0.120112        0.010757            0.000141                                             median              {'model__alpha': 0.0001414170170289024, 'prepr...          -0.155129          -0.122989          -0.205343          -0.125840          -0.146343        -0.151129        0.029697              143           -0.093384           -0.094069           -0.094880           -0.095301           -0.090363         -0.093600         0.001748
20        0.421790      0.129994         0.115376        0.004646            0.000147                                               mean              {'model__alpha': 0.0001469684386112446, 'prepr...          -0.154954          -0.122584          -0.205361          -0.125162          -0.145735        -0.150759        0.029911              140           -0.093521           -0.094307           -0.094999           -0.095479           -0.090587         -0.093779         0.001727
21        0.415445      0.119703         0.119123        0.007433            0.000147                                             median              {'model__alpha': 0.0001469684386112446, 'prepr...          -0.154931          -0.122577          -0.205362          -0.125170          -0.145742        -0.150756        0.029910              139           -0.093536           -0.094313           -0.095000           -0.095485           -0.090587         -0.093784         0.001728
22        0.412573      0.099684         0.121131        0.016838            0.000153                                               mean              {'model__alpha': 0.0001527377850390714, 'prepr...          -0.154773          -0.122180          -0.205403          -0.124493          -0.145190        -0.150408        0.030130              136           -0.093671           -0.094567           -0.095126           -0.095653           -0.090791         -0.093962         0.001716
23        0.396842      0.130912         0.123152        0.011172            0.000153                                             median              {'model__alpha': 0.0001527377850390714, 'prepr...          -0.154750          -0.122173          -0.205404          -0.124502          -0.145197        -0.150405        0.030129              135           -0.093686           -0.094574           -0.095127           -0.095658           -0.090792         -0.093967         0.001717
24        0.397260      0.137172         0.121772        0.008670            0.000159                                               mean              {'model__alpha': 0.00015873361110102087, 'prep...          -0.154596          -0.121822          -0.205463          -0.123775          -0.144668        -0.150065        0.030356              134           -0.093832           -0.094767           -0.095255           -0.095831           -0.090992         -0.094136         0.001703
25        0.391953      0.144786         0.117569        0.005957            0.000159                                             median              {'model__alpha': 0.00015873361110102087, 'prep...          -0.154572          -0.121815          -0.205464          -0.123786          -0.144675        -0.150062        0.030355              132           -0.093848           -0.094776           -0.095256           -0.095837           -0.090992         -0.094142         0.001704
26        0.389148      0.142955         0.112398        0.005796            0.000165                                               mean              {'model__alpha': 0.00016496480740980208, 'prep...          -0.154435          -0.121476          -0.205527          -0.123037          -0.144143        -0.149724        0.030586              130           -0.094003           -0.094969           -0.095385           -0.096020           -0.091203         -0.094316         0.001689
27        0.403131      0.135126         0.115876        0.003062            0.000165                                             median              {'model__alpha': 0.00016496480740980208, 'prep...          -0.154409          -0.121469          -0.205523          -0.123043          -0.144150        -0.149719        0.030584              129           -0.094018           -0.094977           -0.095385           -0.096026           -0.091204         -0.094322         0.001690
28        0.391223      0.083371         0.122516        0.010694            0.000171                                               mean              {'model__alpha': 0.00017144061358519703, 'prep...          -0.154270          -0.121145          -0.205606          -0.122287          -0.143613        -0.149384        0.030821              126           -0.094174           -0.095181           -0.095527           -0.096221           -0.091421         -0.094505         0.001677
29        0.379854      0.087899         0.109714        0.003746            0.000171                                             median              {'model__alpha': 0.00017144061358519703, 'prep...          -0.154245          -0.121138          -0.205602          -0.122293          -0.143621        -0.149380        0.030819              125           -0.094189           -0.095191           -0.095527           -0.096227           -0.091421         -0.094511         0.001679
30        0.372562      0.084070         0.122283        0.010318            0.000178                                               mean              {'model__alpha': 0.00017817063195457307, 'prep...          -0.154119          -0.120826          -0.205720          -0.121524          -0.143077        -0.149053        0.031071              122           -0.094346           -0.095406           -0.095664           -0.096434           -0.091649         -0.094700         0.001666
31        0.411029      0.108799         0.117109        0.001599            0.000178                                             median              {'model__alpha': 0.00017817063195457307, 'prep...          -0.154098          -0.120821          -0.205716          -0.121523          -0.143086        -0.149049        0.031070              121           -0.094361           -0.095414           -0.095664           -0.096439           -0.091649         -0.094706         0.001667
32        0.398995      0.081959         0.129339        0.015376            0.000185                                               mean              {'model__alpha': 0.0001851648417912154, 'prepr...          -0.153984          -0.120537          -0.205845          -0.120747          -0.142574        -0.148737        0.031323              120           -0.094523           -0.095636           -0.095801           -0.096659           -0.091881         -0.094900         0.001655
33        0.380287      0.105719         0.145281        0.042125            0.000185                                             median              {'model__alpha': 0.0001851648417912154, 'prepr...          -0.153964          -0.120531          -0.205836          -0.120745          -0.142583        -0.148732        0.031320              119           -0.094538           -0.095643           -0.095802           -0.096665           -0.091882         -0.094906         0.001656
34        0.423945      0.140360         0.156485        0.063890            0.000192                                               mean              {'model__alpha': 0.000192433614111598, 'prepro...          -0.153769          -0.120265          -0.205949          -0.119982          -0.142092        -0.148411        0.031558              116           -0.094679           -0.095851           -0.095934           -0.096898           -0.092117         -0.095096         0.001647
35        0.390899      0.079016         0.126208        0.009297            0.000192                                             median              {'model__alpha': 0.000192433614111598, 'prepro...          -0.153748          -0.120261          -0.205938          -0.119980          -0.142099        -0.148405        0.031554              115           -0.094693           -0.095859           -0.095935           -0.096903           -0.092117         -0.095102         0.001649
36        0.415315      0.118127         0.176473        0.055391            0.000200                                               mean              {'model__alpha': 0.0001999877270535285, 'prepr...          -0.153540          -0.120006          -0.206047          -0.119233          -0.141592        -0.148084        0.031788              112           -0.094837           -0.096083           -0.096071           -0.097153           -0.092363         -0.095301         0.001642
37        0.421689      0.066269         0.138373        0.023925            0.000200                                             median              {'model__alpha': 0.0001999877270535285, 'prepr...          -0.153520          -0.120002          -0.206036          -0.119230          -0.141599        -0.148077        0.031784              111           -0.094851           -0.096091           -0.096072           -0.097158           -0.092363         -0.095307         0.001643
38        0.435836      0.200727         0.154536        0.071317            0.000208                                               mean              {'model__alpha': 0.00020783838185797573, 'prep...          -0.153312          -0.119824          -0.206114          -0.118486          -0.141080        -0.147763        0.031994              108           -0.095005           -0.096305           -0.096216           -0.097424           -0.092614         -0.095513         0.001639
39        0.463465      0.106848         0.117112        0.005532            0.000208                                             median              {'model__alpha': 0.00020783838185797573, 'prep...          -0.153293          -0.119818          -0.206102          -0.118483          -0.141088        -0.147757        0.031990              107           -0.095018           -0.096314           -0.096217           -0.097429           -0.092614         -0.095518         0.001640

### Final Pipeline (ElasticNet) ###

In [81]:
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import GridSearchCV, cross_validate
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', ElasticNet(max_iter=10000))
])

param_grid = {
    'preprocessor__num_impute__impute__strategy':
        ['mean', 'median'],
    # 'model__alpha':
    #     [.0005, .001, .002, .005, .1, .5, 1],
    # 'model__l1_ratio':
    #     [.1, .2, .3, .4, .5, .6, .7, .8, .9],

    'model__alpha':
        np.logspace(-4, 1, 30),
    'model__l1_ratio':
        np.linspace(.05, .95, 20)
}

# {\'model__alpha\': 0.0007278953843983154, \'model__l1_ratio\': 0.7131578947368421, \'preprocessor__preprocessor__num_impute__impute__strategy\': \'mean\'}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
    verbose=1,
    n_jobs=-1,
)

search.fit(X_train, y_train_t)
cv_results_df = pd.DataFrame(search.cv_results_)
cv_results_df

Fitting 5 folds for each of 1200 candidates, totalling 6000 fits

      mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_model__alpha  param_model__l1_ratio param_preprocessor__preprocessor__num_impute__impute__strategy                                             params  split0_test_score  split1_test_score  split2_test_score  split3_test_score  split4_test_score  mean_test_score  std_test_score  rank_test_score  split0_train_score  split1_train_score  split2_train_score  split3_train_score  split4_train_score  mean_train_score  std_train_score
0          3.314577      3.392029         0.261353        0.102276            0.000100               0.050000                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.142375          -0.137402          -0.130484          -0.106842          -0.124139        -0.128248        0.012357              569           -0.081123           -0.083706           -0.085303           -0.089008           -0.085955         -0.085019         0.002599
1          3.442399      2.941844         0.192308        0.057177            0.000100               0.050000                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.142391          -0.137390          -0.130474          -0.106837          -0.124179        -0.128254        0.012358              570           -0.081118           -0.083703           -0.085311           -0.089008           -0.085951         -0.085018         0.002601
2          2.970581      2.475001         0.202630        0.048384            0.000100               0.097368                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.142077          -0.136683          -0.129734          -0.106614          -0.123047        -0.127631        0.012311              557           -0.081194           -0.083776           -0.085358           -0.089078           -0.086018         -0.085085         0.002598
3          2.901912      2.743442         0.165322        0.021030            0.000100               0.097368                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.142090          -0.136672          -0.129723          -0.106611          -0.123089        -0.127637        0.012310              558           -0.081189           -0.083773           -0.085365           -0.089079           -0.086013         -0.085084         0.002600
4          2.308816      2.204081         0.221125        0.096675            0.000100               0.144737                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.141703          -0.135960          -0.129092          -0.106259          -0.122393        -0.127081        0.012265              547           -0.081276           -0.083859           -0.085419           -0.089161           -0.086085         -0.085160         0.002596
5          2.324319      1.797121         0.164558        0.032120            0.000100               0.144737                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.141714          -0.135950          -0.129075          -0.106256          -0.122427        -0.127085        0.012265              548           -0.081271           -0.083857           -0.085426           -0.089162           -0.086081         -0.085159         0.002598
6          0.782089      0.147618         0.160000        0.036521            0.000100               0.192105                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.141331          -0.135335          -0.128693          -0.105867          -0.121816        -0.126608        0.012251              541           -0.081369           -0.083954           -0.085487           -0.089250           -0.086162         -0.085245         0.002593
7          0.700925      0.133491         0.168572        0.035241            0.000100               0.192105                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.141340          -0.135326          -0.128675          -0.105863          -0.121848        -0.126610        0.012250              542           -0.081364           -0.083952           -0.085495           -0.089251           -0.086159         -0.085244         0.002595
8          0.659668      0.188697         0.134308        0.012748            0.000100               0.239474                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140978          -0.134776          -0.128283          -0.105502          -0.121283        -0.126164        0.012238              525           -0.081472           -0.084059           -0.085558           -0.089341           -0.086237         -0.085334         0.002587
9          0.550341      0.162798         0.135884        0.024841            0.000100               0.239474                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140987          -0.134767          -0.128265          -0.105499          -0.121315        -0.126167        0.012237              526           -0.081467           -0.084056           -0.085566           -0.089342           -0.086234         -0.085333         0.002589
10         0.432101      0.042047         0.128121        0.018436            0.000100               0.286842                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140682          -0.134239          -0.127883          -0.105214          -0.120781        -0.125760        0.012215              515           -0.081584           -0.084178           -0.085635           -0.089440           -0.086318         -0.085431         0.002579
11         0.517599      0.109086         0.177276        0.098828            0.000100               0.286842                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140688          -0.134233          -0.127864          -0.105208          -0.120812        -0.125761        0.012214              516           -0.081579           -0.084175           -0.085643           -0.089440           -0.086315         -0.085431         0.002581
12         0.631517      0.216063         0.153084        0.041715            0.000100               0.334211                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140441          -0.133776          -0.127484          -0.105039          -0.120279        -0.125404        0.012178              505           -0.081704           -0.084308           -0.085718           -0.089548           -0.086405         -0.085536         0.002572
13         0.529106      0.186814         0.145191        0.027696            0.000100               0.334211                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140447          -0.133769          -0.127470          -0.105034          -0.120312        -0.125406        0.012177              506           -0.081699           -0.084305           -0.085725           -0.089549           -0.086401         -0.085536         0.002574
14         0.552189      0.217138         0.141491        0.036974            0.000100               0.381579                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140206          -0.133307          -0.127042          -0.104932          -0.119774        -0.125052        0.012120              495           -0.081828           -0.084444           -0.085806           -0.089668           -0.086498         -0.085649         0.002567
15         0.574494      0.199253         0.147601        0.027059            0.000100               0.381579                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140211          -0.133296          -0.127027          -0.104928          -0.119808        -0.125054        0.012117              498           -0.081823           -0.084442           -0.085814           -0.089669           -0.086495         -0.085649         0.002569
16         0.468821      0.066591         0.137916        0.027045            0.000100               0.428947                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139981          -0.132855          -0.126592          -0.104873          -0.119280        -0.124716        0.012051              483           -0.081962           -0.084583           -0.085900           -0.089799           -0.086602         -0.085769         0.002563
17         0.588219      0.196457         0.132082        0.003334            0.000100               0.428947                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139985          -0.132846          -0.126579          -0.104869          -0.119313        -0.124718        0.012048              484           -0.081957           -0.084581           -0.085908           -0.089800           -0.086599         -0.085769         0.002565
18         1.348194      1.520391         0.177076        0.069603            0.000100               0.476316                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139788          -0.132442          -0.126166          -0.104730          -0.118795        -0.124384        0.012024              473           -0.082105           -0.084730           -0.086001           -0.089925           -0.086715         -0.085895         0.002555
19         1.427645      1.696000         0.136566        0.012096            0.000100               0.476316                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139794          -0.132435          -0.126152          -0.104728          -0.118828        -0.124387        0.012022              474           -0.082101           -0.084728           -0.086009           -0.089926           -0.086712         -0.085895         0.002557
20         1.439845      1.434461         0.148225        0.009856            0.000100               0.523684                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139624          -0.132020          -0.125749          -0.104583          -0.118344        -0.124064        0.012004              461           -0.082257           -0.084888           -0.086109           -0.090061           -0.086832         -0.086030         0.002547
21         1.436998      1.346259         0.203399        0.088045            0.000100               0.523684                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139630          -0.132008          -0.125735          -0.104581          -0.118378        -0.124066        0.012001              462           -0.082254           -0.084885           -0.086117           -0.090062           -0.086829         -0.086029         0.002548
22         1.421560      1.192956         0.166564        0.056754            0.000100               0.571053                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139503          -0.131551          -0.125320          -0.104441          -0.117911        -0.123745        0.011987              453           -0.082417           -0.085037           -0.086220           -0.090198           -0.086955         -0.086165         0.002538
23         1.185331      1.059183         0.157103        0.025159            0.000100               0.571053                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139511          -0.131538          -0.125308          -0.104440          -0.117945        -0.123748        0.011984              454           -0.082413           -0.085033           -0.086229           -0.090200           -0.086952         -0.086165         0.002540
24         1.094799      0.966757         0.136741        0.006086            0.000100               0.618421                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139386          -0.131120          -0.124891          -0.104291          -0.117516        -0.123441        0.011976              445           -0.082569           -0.085171           -0.086340           -0.090324           -0.087075         -0.086296         0.002530
25         1.178187      0.876217         0.142532        0.018147            0.000100               0.618421                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139393          -0.131108          -0.124880          -0.104290          -0.117551        -0.123444        0.011973              446           -0.082565           -0.085168           -0.086348           -0.090326           -0.087072         -0.086296         0.002531
26         1.064172      0.924308         0.136546        0.009779            0.000100               0.665789                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139233          -0.130679          -0.124454          -0.104144          -0.117118        -0.123125        0.011955              433           -0.082709           -0.085311           -0.086465           -0.090451           -0.087202         -0.086428         0.002524
27         1.101287      1.022222         0.136148        0.011207            0.000100               0.665789                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139240          -0.130666          -0.124441          -0.104144          -0.117157        -0.123130        0.011952              434           -0.082706           -0.085308           -0.086472           -0.090453           -0.087199         -0.086428         0.002526
28         0.971108      0.800472         0.131575        0.004788            0.000100               0.713158                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139086          -0.130231          -0.124002          -0.103963          -0.116717        -0.122800        0.011948              425           -0.082859           -0.085455           -0.086594           -0.090577           -0.087333         -0.086564         0.002516
29         0.990733      0.765067         0.163613        0.035198            0.000100               0.713158                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139093          -0.130219          -0.123986          -0.103964          -0.116754        -0.122803        0.011944              426           -0.082856           -0.085451           -0.086602           -0.090579           -0.087330         -0.086564         0.002518
30         0.922026      0.719146         0.132476        0.005127            0.000100               0.760526                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138946          -0.129803          -0.123563          -0.103782          -0.116333        -0.122486        0.011944              409           -0.083016           -0.085591           -0.086726           -0.090711           -0.087470         -0.086703         0.002509
31         0.873040      0.679692         0.132822        0.002887            0.000100               0.760526                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138954          -0.129798          -0.123548          -0.103784          -0.116368        -0.122491        0.011941              410           -0.083013           -0.085587           -0.086733           -0.090712           -0.087467         -0.086702         0.002511
32         1.011190      0.573338         0.151838        0.038907            0.000100               0.807895                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138822          -0.129405          -0.123153          -0.103561          -0.115998        -0.122188        0.011958              403           -0.083181           -0.085723           -0.086849           -0.090831           -0.087606         -0.086838         0.002496
33         1.078210      0.585978         0.136909        0.011702            0.000100               0.807895                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138824          -0.129393          -0.123137          -0.103563          -0.116035        -0.122190        0.011953              404           -0.083177           -0.085720           -0.086857           -0.090832           -0.087603         -0.086838         0.002497
34         1.164032      0.472055         0.129932        0.007629            0.000100               0.855263                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138713          -0.129009          -0.122715          -0.103310          -0.115663        -0.121882        0.011987              389           -0.083338           -0.085863           -0.086965           -0.090946           -0.087748         -0.086972         0.002483
35         1.187087      0.517978         0.127646        0.004046            0.000100               0.855263                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138722          -0.128997          -0.122698          -0.103308          -0.115698        -0.121885        0.011984              390           -0.083335           -0.085860           -0.086972           -0.090947           -0.087744         -0.086972         0.002484
36         1.241549      0.415314         0.128762        0.012856            0.000100               0.902632                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138616          -0.128617          -0.122269          -0.103056          -0.115336        -0.121579        0.012020              381           -0.083494           -0.086011           -0.087084           -0.091061           -0.087879         -0.087106         0.002469
37         1.218247      0.386542         0.127331        0.004989            0.000100               0.902632                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138624          -0.128604          -0.122252          -0.103054          -0.115369        -0.121581        0.012017              382           -0.083491           -0.086008           -0.087091           -0.091062           -0.087875         -0.087105         0.002471

In [121]:
from sklearn.metrics import root_mean_squared_error
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', ElasticNet(alpha=0.0007278953843983154, l1_ratio=0.7131578947368421))
])
final_pipeline.fit(X_train, y_train_t)
y_pred = final_pipeline.predict(X_test)
print(root_mean_squared_error(y_test_t, y_pred))

y_pred = final_pipeline.predict(X_train)
print(root_mean_squared_error(y_train_t, y_pred))



# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', Lasso(alpha=.0007934096665797492))
# ])
# final_pipeline.fit(X_train, y_train_t)
# y_pred = final_pipeline.predict(X_test)
# print(root_mean_squared_error(y_test_t, y_pred))
#
# y_pred = final_pipeline.predict(X_train)
# print(root_mean_squared_error(y_train_t, y_pred))
#
#
# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', LinearRegression())
# ])
# final_pipeline.fit(X_train, y_train_t)
# y_pred = final_pipeline.predict(X_test)
# print(root_mean_squared_error(y_test_t, y_pred))
#
# y_pred = final_pipeline.predict(X_train)
# print(root_mean_squared_error(y_train_t, y_pred))

0.11544915376776345
0.10881045553882318
0.1156369745205326
0.11243910374712052
0.12966410509994647
0.09419088615888568

In [189]:
final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Ridge(alpha=400))
])

cv_results = cross_validate(
    final_pipeline, X_train, y_train_t,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
)

cv_results_df = pd.DataFrame(cv_results)

train_root_mean_squared_error = -cv_results_df.mean()['train_score']
validation_root_mean_squared_error = -cv_results_df.mean()['test_score']

print(f'train_rmse: {train_root_mean_squared_error}')
print(f'validation_rmse: {validation_root_mean_squared_error}')

train_rmse: 0.10310912196089887
validation_rmse: 0.13957445547139208

In [124]:
# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', ElasticNet(alpha=0.0007278953843983154, l1_ratio=0.7131578947368421))
# ])

# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', Ridge(alpha=9.846791241561434))
# ])

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Lasso(alpha=0.0006348565216305217))
])

test = pd.read_csv(PATH + '/test.csv')
test_ids = test['Id']

# final_pipeline.fit(pd.concat([X_train, X_test], axis=0, ignore_index=True), pd.concat([y_train_t, y_test_t], axis=0, ignore_index=True))
final_pipeline.fit(X_train, y_train_t)
prices_log = final_pipeline.predict(test)
prices = np.expm1(prices_log)

submission = pd.DataFrame({
    'Id': test_ids,
    'SalePrice': prices,
})

submission.to_csv('submission.csv', index=False)

### Final Test scores ###

In [61]:
from sklearn.metrics import root_mean_squared_error

runs_df = mlflow.search_runs(experiment_names=["linear_regression"])

for run_id in runs_df["run_id"]:
    models = mlflow.search_logged_models(
        filter_string=f"source_run_id = '{run_id}'",
        output_format="list",
    )

    model_id = models[0].model_id
    model = mlflow.sklearn.load_model(f"models:/{model_id}")
    y_pred = model.predict(X_test)

    test_rmse = root_mean_squared_error(y_test_t, y_pred)

    with mlflow.start_run(run_id=run_id):
        mlflow.log_metric('test_rmse', test_rmse)

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

🏃 View run LR__prep_v1__num_imp_median__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/f7155e7f2be3435e919d5aab2e1b0bf5
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

🏃 View run LR__prep_v1__num_imp_mean__ord_imp__ohe at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/339189ffc2fd4096a73dc763dce0fffb
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1