In [1]:
import pandas as pd
import numpy as np

### Dagshub/Mlflow initialization ###

In [52]:
import dagshub
import mlflow
import mlflow.sklearn

dagshub.init(repo_owner='sbolk23', repo_name='House-Prices-Kaggle-Competition', mlflow=True)

Initialized MLflow to track repo "sbolk23/House-Prices-Kaggle-Competition"

Repository sbolk23/House-Prices-Kaggle-Competition initialized!

In [5]:
PATH = './data'
TARGET = 'SalePrice'

In [6]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)

### Split Train/Test Data ###

In [70]:
df = pd.read_csv(PATH + '/train.csv')
df = df.drop([523, 1298], axis=0)

In [71]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold

X = df.drop(columns=[TARGET])
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=.2, shuffle=True, random_state=1337
)

train_ids = X_train['Id']
test_ids = X_test['Id']

print(f'X_train shape {X_train.shape}')
print(f'X_test shape {X_test.shape}')

X_train shape (1166, 80)
X_test shape (292, 80)

### Data Cleaning ###

### Categorical Imputing ###

In [72]:
# we first impute all missing values in categorical and numeric features.

# These categorical columns may have 'NaN' values in them which means missing.
# data_description.txt did not mention 'Nan' was intended.

cat_impute_cols = [
    'MSZoning',
    'Street',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'Foundation',
    'ExterQual',
    'ExterCond',
    'Heating',
    'HeatingQC',
    'CentralAir',
    'Electrical',
    'KitchenQual',
    'Functional',
    'PavedDrive',
    'SaleType',
    'SaleCondition',
]

### Numeric Imputing ###

In [73]:
# We impute all numeric columns because data_description.txt did not mention any numeric feature with intended 'NaN' value.

# num_impute_cols = [
#     'LotFrontage',
#     'GarageYrBlt',
#     'MasVnrArea',
# ]

num_impute_cols = list(X_train.select_dtypes(exclude='object').columns)
num_impute_cols.remove('Id')
num_impute_cols.remove('MSSubClass')

### Categorical One-Hot-Encoded Columns ###

In [74]:
# Here we list features to be one-hot-encoded including 'NaN's because 'NaN' here does not mean missing.
# 'MasVnrType' was interesting column here.

cat_ohe_cols = [
    'MSZoning',
    'Street',
    'Alley',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'MasVnrType',
    'Foundation',
    'Heating',
    'CentralAir',
    'Electrical',
    'GarageType',
    'PavedDrive',
    'MiscFeature',
    'SaleType',
    'SaleCondition',
]

cat_ohe_missing_cols = [
    'MSZoning',
    'Street',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'Foundation',
    'Heating',
    'CentralAir',
    'Electrical',
    'PavedDrive',
    'SaleType',
    'SaleCondition'
]

cat_ohe_absent_cols = [
    'Alley',
    'MasVnrType',
    'GarageType',
    'MiscFeature'
]

### Ordinal Columns ###

In [75]:
# Some categorical columns can may be ordered, replace them with numbers.

cat_ord_cols = [
    'ExterQual',
    'ExterCond',
    'BsmtQual',
    'BsmtCond',
    'BsmtExposure',
    'BsmtFinType1',
    'BsmtFinType2',
    'HeatingQC',
    'KitchenQual',
    'Functional',
    'FireplaceQu',
    'GarageFinish',
    'GarageQual',
    'GarageCond',
    'PoolQC',
    'Fence',
]

cat_ord_missing_cols = [
    'ExterQual',
    'ExterCond',
    'HeatingQC',
    'KitchenQual',
    'Functional',
]

cat_ord_absent_cols = [
    'BsmtQual',
    'BsmtCond',
    'BsmtExposure',
    'BsmtFinType1',
    'BsmtFinType2',
    'FireplaceQu',
    'GarageFinish',
    'GarageQual',
    'GarageCond',
    'PoolQC',
    'Fence',
]

exter_qual_order        = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
exter_cond_order        = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
bsmt_qual_order         = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
bsmt_cond_order         = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
bsmt_exposure_order     = ['NA', 'No', 'Mn', 'Av', 'Gd']
bsmt_fin_type_1_order   = ['NA', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ']
bsmt_fin_type_2_order   = ['NA', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ']
heating_qc_order        = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
kitchen_qual_order      = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
functional_order        = ['Sal', 'Sev', 'Maj2', 'Maj1', 'Mod', 'Min2', 'Min1', 'Typ']
fireplace_qu_order      = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
garage_finish_order     = ['NA', 'Unf', 'RFn', 'Fin']
garage_qual_order       = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
garage_cond_order       = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
pool_qc_order           = ['NA', 'Fa', 'TA', 'Gd', 'Ex']
fence_order             = ['NA', 'MnWw', 'GdWo', 'MnPrv', 'GdPrv']

cat_ord_missing_categories = [
    exter_qual_order,
    exter_cond_order,
    heating_qc_order,
    kitchen_qual_order,
    functional_order,
]

cat_ord_absent_categories = [
    bsmt_qual_order,
    bsmt_cond_order,
    bsmt_exposure_order,
    bsmt_fin_type_1_order,
    bsmt_fin_type_2_order,
    fireplace_qu_order,
    garage_finish_order,
    garage_qual_order,
    garage_cond_order,
    pool_qc_order,
    fence_order,
]

### Numeric One-Hot-Encoded Columns ###

In [76]:
# This feature has numeric type which is misleading.

num_ohe_cols = [
    'MSSubClass',
]

### Data Cleanup Pipeline ###

In [77]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

num_impute_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='median')),
    ('scale',   StandardScaler())
])

num_ohe_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='most_frequent')),
    ('ohe',     OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

cat_ord_missing_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='most_frequent')),
    ('ordinal', OrdinalEncoder(categories=cat_ord_missing_categories)),
])

cat_ord_absent_pipeline = Pipeline([
    ('nan_impute',  SimpleImputer(strategy='constant', missing_values=np.nan, fill_value='NA')),
    ('ordinal',     OrdinalEncoder(categories=cat_ord_absent_categories)),
])

cat_ohe_missing_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='most_frequent')),
    ('ohe',     OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
])

cat_ohe_absent_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='constant', missing_values=np.nan, fill_value='Missing')),
    ('ohe',     OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num_impute',       num_impute_pipeline,       num_impute_cols),
        ('num_ohe',          num_ohe_pipeline,          num_ohe_cols),
        ('cat_ord_absent',   cat_ord_absent_pipeline,   cat_ord_absent_cols),
        ('cat_ord_missing',  cat_ord_missing_pipeline,  cat_ord_missing_cols),
        ('cat_ohe_absent',   cat_ohe_absent_pipeline,   cat_ohe_absent_cols),
        ('cat_ohe_missing',  cat_ohe_missing_pipeline,  cat_ohe_missing_cols),
        ('drop',    'drop',                             ['Id']),
    ],
    remainder='passthrough',
    verbose_feature_names_out=False,
)

preprocessor.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('num_impute',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='median')),
                                                 ('scale', StandardScaler())]),
                                 ['LotFrontage', 'LotArea', 'OverallQual',
                                  'OverallCond', 'YearBuilt', 'YearRemodAdd',
                                  'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
                                  'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF',
                                  '2ndFlrSF', 'LowQualFinSF', 'GrLivAre...
                                                                sparse_output=False))]),
                                 ['MSZoning', 'Street', 'LotShape',
                                  'LandContour', 'Utilities', 'LotConfig',
                                  'LandSlope', 'Neighborhood', 'Condition1',
                                  'Condition2', 'BldgType', 'HouseStyle',
                                  'RoofStyle', 'RoofMatl', 'Exterior1st',
                                  'Exterior2nd', 'Foundation', 'Heating',
                                  'CentralAir', 'Electrical', 'PavedDrive',
                                  'SaleType', 'SaleCondition']),
                                ('drop', 'drop', ['Id'])],
                  verbose_feature_names_out=False)

In [78]:
# scaling every column after preprocessing decreased accuracy.
# scaling only numeric columns is sufficient.

preprocessor_pipeline = Pipeline([
    ('preprocessor', preprocessor),
])

preprocessor_pipeline.set_output(transform='pandas')

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num_impute',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['LotFrontage', 'LotArea',
                                                   'OverallQual', 'OverallCond',
                                                   'YearBuilt', 'YearRemodAdd',
                                                   'MasVnrArea', 'BsmtFinSF1',
                                                   'BsmtFinSF2', 'BsmtUnfSF',
                                                   'TotalBsmtSF', '1stFlrSF',
                                                   '2n...
                                                                                 sparse_output=False))]),
                                                  ['MSZoning', 'Street',
                                                   'LotShape', 'LandContour',
                                                   'Utilities', 'LotConfig',
                                                   'LandSlope', 'Neighborhood',
                                                   'Condition1', 'Condition2',
                                                   'BldgType', 'HouseStyle',
                                                   'RoofStyle', 'RoofMatl',
                                                   'Exterior1st', 'Exterior2nd',
                                                   'Foundation', 'Heating',
                                                   'CentralAir', 'Electrical',
                                                   'PavedDrive', 'SaleType',
                                                   'SaleCondition']),
                                                 ('drop', 'drop', ['Id'])],
                                   verbose_feature_names_out=False))])

In [79]:
y_train_t = np.log1p(y_train)
y_test_t = np.log1p(y_test)

preprocessor_pipeline.fit(X_train, y_train_t)

X_train_t = preprocessor_pipeline.transform(X_train)
X_test_t = preprocessor_pipeline.transform(X_test)

X = X_train.copy()
X['SalePrice'] = y_train

kf = KFold(n_splits=5, shuffle=True, random_state=1337)
folds = list(kf.split(X))

train_idx, val_idx = folds[4]
vals = X.iloc[train_idx, :]
outliers_in_fold = vals[(vals['GrLivArea'] > 4000) & (vals['SalePrice'] < 300000)]
outliers_in_fold[['GrLivArea', 'SalePrice']]

Empty DataFrame
Columns: [GrLivArea, SalePrice]
Index: []

### Full Pipeline (Linear Regression) ###

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV, KFold, ParameterGrid

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', LinearRegression())
])

param_grid = {
    'preprocessor__preprocessor__num_impute__impute__strategy': ['mean', 'median'],
}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring=['neg_root_mean_squared_error'],
    refit='neg_root_mean_squared_error',
    return_train_score=True,
)

search.fit(X_train, y_train_t)
cv_results_df = pd.DataFrame(search.cv_results_)

### MLFlow Log (Linear Regression) ###

In [59]:
mlflow.set_experiment('linear_regression')

for i, row in cv_results_df.iterrows():
    row_dict = row.to_dict()

    with mlflow.start_run(run_name=f'LR_{i}'):
        mlflow.set_tag('model_type', 'LinearRegression')
        mlflow.set_tag('data_version', 'v1_with_outliers')

        # Here we log preprocessing hyperparameters



        # Here we log model parameters
        for key, value in row_dict.items():
            if 'mean' in key or 'std' in key or 'split' in key:
                mlflow.log_metric(key, value)
            elif 'param_' in key:
                mlflow.log_param(key.replace('param_', ''), value)


#  preprocessing_spec = {
#     'num_impute_cols': num_impute_cols,
#     'num_ohe_cols': num_ohe_cols,
#     'cat_ord_absent_cols': cat_ord_absent_cols,
#     'cat_ord_missing_cols': cat_ord_missing_cols,
#     'cat_ohe_absent_cols': cat_ohe_absent_cols,
#     'cat_ohe_missing_cols': cat_ohe_missing_cols,
#     'cat_ord_absent_categories': cat_ord_absent_categories,
#     'cat_ord_missing_categories': cat_ord_missing_categories,
# }

🏃 View run LR_0 at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/06cd80b588d84324b574e6083617929d
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1
🏃 View run LR_1 at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1/runs/2186e82c9ae24867ba522d650331e363
🧪 View experiment at: https://dagshub.com/sbolk23/House-Prices-Kaggle-Competition.mlflow/#/experiments/1

### Full Pipeline (Ridge) ###

In [80]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Ridge())
])

param_grid = {
    'preprocessor__preprocessor__num_impute__impute__strategy': ['mean', 'median'],
    # 'model__alpha': [.001, .01, .05, .1, .5, 1, 5, 9, 9.1, 9.2, 9.3, 9.4],
    # 'model__alpha': np.linspace(.01, 50, 300),
    'model__alpha': np.logspace(np.log10(9), np.log10(10), 300),
}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
    verbose=1,
    n_jobs=-1
)

search.fit(X_train, y_train_t)
cv_results_df = pd.DataFrame(search.cv_results_)

cv_results_df

Fitting 5 folds for each of 600 candidates, totalling 3000 fits

     mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_model__alpha param_preprocessor__preprocessor__num_impute__impute__strategy                                             params  split0_test_score  split1_test_score  split2_test_score  split3_test_score  split4_test_score  mean_test_score  std_test_score  rank_test_score  split0_train_score  split1_train_score  split2_train_score  split3_train_score  split4_train_score  mean_train_score  std_train_score
0         0.362533      0.100524         0.129788        0.024883            9.000000                                               mean              {'model__alpha': 9.0, 'preprocessor__preproces...          -0.136602          -0.122212          -0.108522          -0.098003          -0.113638        -0.115795        0.013025              600           -0.088444           -0.093136           -0.094647           -0.097346           -0.093460         -0.093407         0.002890
1         0.319033      0.091877         0.149912        0.059834            9.000000                                             median              {'model__alpha': 9.0, 'preprocessor__preproces...          -0.136611          -0.122184          -0.108517          -0.097999          -0.113644        -0.115791        0.013026              588           -0.088441           -0.093135           -0.094652           -0.097348           -0.093460         -0.093407         0.002892
2         0.376756      0.090122         0.142200        0.032727            9.003172                                               mean              {'model__alpha': 9.003171945585345, 'preproces...          -0.136601          -0.122211          -0.108521          -0.098004          -0.113638        -0.115795        0.013024              599           -0.088445           -0.093138           -0.094649           -0.097347           -0.093461         -0.093408         0.002890
3         0.309720      0.040450         0.133818        0.051803            9.003172                                             median              {'model__alpha': 9.003171945585345, 'preproces...          -0.136610          -0.122183          -0.108516          -0.097999          -0.113644        -0.115791        0.013026              586           -0.088443           -0.093137           -0.094654           -0.097350           -0.093462         -0.093409         0.002892
4         0.334137      0.089902         0.141364        0.049566            9.006345                                               mean              {'model__alpha': 9.006345009086111, 'preproces...          -0.136601          -0.122210          -0.108520          -0.098004          -0.113638        -0.115795        0.013024              598           -0.088446           -0.093139           -0.094651           -0.097349           -0.093462         -0.093409         0.002890
5         0.281448      0.067110         0.139147        0.043728            9.006345                                             median              {'model__alpha': 9.006345009086111, 'preproces...          -0.136610          -0.122182          -0.108515          -0.098000          -0.113644        -0.115790        0.013026              584           -0.088444           -0.093138           -0.094655           -0.097351           -0.093463         -0.093410         0.002892
6         0.321296      0.075895         0.117328        0.020946            9.009519                                               mean              {'model__alpha': 9.009519190896297, 'preproces...          -0.136600          -0.122209          -0.108520          -0.098004          -0.113638        -0.115794        0.013024              597           -0.088448           -0.093141           -0.094652           -0.097350           -0.093464         -0.093411         0.002890
7         0.279010      0.031564         0.110830        0.011148            9.009519                                             median              {'model__alpha': 9.009519190896297, 'preproces...          -0.136609          -0.122181          -0.108515          -0.098000          -0.113644        -0.115790        0.013025              582           -0.088445           -0.093140           -0.094657           -0.097353           -0.093464         -0.093412         0.002892
8         0.258029      0.022542         0.108355        0.006749            9.012694                                               mean              {'model__alpha': 9.012694491410032, 'preproces...          -0.136600          -0.122208          -0.108519          -0.098004          -0.113638        -0.115794        0.013024              596           -0.088449           -0.093142           -0.094654           -0.097351           -0.093465         -0.093412         0.002890
9         0.282638      0.031193         0.113219        0.003744            9.012694                                             median              {'model__alpha': 9.012694491410032, 'preproces...          -0.136609          -0.122180          -0.108514          -0.098000          -0.113644        -0.115789        0.013025              580           -0.088447           -0.093141           -0.094658           -0.097354           -0.093465         -0.093413         0.002892
10        0.277081      0.037475         0.109543        0.011603            9.015871                                               mean              {'model__alpha': 9.015870911021599, 'preproces...          -0.136599          -0.122207          -0.108518          -0.098005          -0.113638        -0.115793        0.013023              595           -0.088450           -0.093144           -0.094655           -0.097353           -0.093466         -0.093414         0.002890
11        0.255182      0.015032         0.111692        0.008019            9.015871                                             median              {'model__alpha': 9.015870911021599, 'preproces...          -0.136608          -0.122180          -0.108513          -0.098000          -0.113644        -0.115789        0.013025              578           -0.088448           -0.093143           -0.094660           -0.097355           -0.093467         -0.093415         0.002892
12        0.233195      0.009639         0.112648        0.008444            9.019048                                               mean              {'model__alpha': 9.019048450125407, 'preproces...          -0.136599          -0.122207          -0.108517          -0.098005          -0.113638        -0.115793        0.013023              594           -0.088452           -0.093145           -0.094657           -0.097354           -0.093467         -0.093415         0.002890
13        0.233411      0.006225         0.108966        0.007395            9.019048                                             median              {'model__alpha': 9.019048450125407, 'preproces...          -0.136608          -0.122179          -0.108513          -0.098001          -0.113644        -0.115789        0.013025              576           -0.088449           -0.093144           -0.094662           -0.097357           -0.093468         -0.093416         0.002892
14        0.243126      0.017976         0.110516        0.007039            9.022227                                               mean              {'model__alpha': 9.022227109116002, 'preproces...          -0.136598          -0.122206          -0.108517          -0.098005          -0.113638        -0.115793        0.013023              593           -0.088453           -0.093147           -0.094659           -0.097355           -0.093469         -0.093417         0.002890
15        0.233848      0.006494         0.108575        0.005551            9.022227                                             median              {'model__alpha': 9.022227109116002, 'preproces...          -0.136607          -0.122178          -0.108512          -0.098001          -0.113644        -0.115788        0.013025              574           -0.088451           -0.093146           -0.094663           -0.097358           -0.093469         -0.093417         0.002892
16        0.238215      0.019348         0.127095        0.039532            9.025407                                               mean              {'model__alpha': 9.025406888388087, 'preproces...          -0.136598          -0.122205          -0.108516          -0.098005          -0.113637        -0.115792        0.013023              592           -0.088454           -0.093148           -0.094660           -0.097357           -0.093470         -0.093418         0.002890
17        0.255486      0.043024         0.113826        0.015430            9.025407                                             median              {'model__alpha': 9.025406888388087, 'preproces...          -0.136607          -0.122177          -0.108511          -0.098001          -0.113644        -0.115788        0.013024              572           -0.088452           -0.093147           -0.094665           -0.097359           -0.093471         -0.093419         0.002892
18        0.253199      0.034910         0.119009        0.025682            9.028588                                               mean              {'model__alpha': 9.02858778833648, 'preprocess...          -0.136597          -0.122204          -0.108515          -0.098005          -0.113637        -0.115792        0.013022              591           -0.088456           -0.093150           -0.094662           -0.097358           -0.093471         -0.093419         0.002890
19        0.231044      0.010867         0.106008        0.001074            9.028588                                             median              {'model__alpha': 9.02858778833648, 'preprocess...          -0.136606          -0.122176          -0.108511          -0.098001          -0.113644        -0.115788        0.013024              570           -0.088453           -0.093149           -0.094667           -0.097361           -0.093472         -0.093420         0.002892
20        0.251583      0.020472         0.107944        0.011942            9.031770                                               mean              {'model__alpha': 9.031769809356161, 'preproces...          -0.136597          -0.122203          -0.108515          -0.098006          -0.113637        -0.115792        0.013022              590           -0.088457           -0.093151           -0.094664           -0.097359           -0.093473         -0.093421         0.002890
21        0.226281      0.007015         0.103764        0.002362            9.031770                                             median              {'model__alpha': 9.031769809356161, 'preproces...          -0.136606          -0.122175          -0.108510          -0.098002          -0.113644        -0.115787        0.013024              568           -0.088455           -0.093150           -0.094668           -0.097362           -0.093473         -0.093422         0.002892
22        0.254154      0.025054         0.110576        0.010234            9.034953                                               mean              {'model__alpha': 9.034952951842232, 'preproces...          -0.136596          -0.122202          -0.108514          -0.098006          -0.113637        -0.115791        0.013022              589           -0.088458           -0.093153           -0.094665           -0.097361           -0.093474         -0.093422         0.002890
23        0.232175      0.004737         0.108242        0.006060            9.034953                                             median              {'model__alpha': 9.034952951842232, 'preproces...          -0.136605          -0.122174          -0.108509          -0.098002          -0.113644        -0.115787        0.013024              566           -0.088456           -0.093152           -0.094670           -0.097363           -0.093474         -0.093423         0.002892
24        0.236982      0.016211         0.122103        0.020861            9.038137                                               mean              {'model__alpha': 9.038137216189941, 'preproces...          -0.136596          -0.122201          -0.108513          -0.098006          -0.113637        -0.115791        0.013022              587           -0.088460           -0.093154           -0.094667           -0.097362           -0.093475         -0.093424         0.002890
25        0.234589      0.005623         0.125374        0.032048            9.038137                                             median              {'model__alpha': 9.038137216189941, 'preproces...          -0.136605          -0.122173          -0.108509          -0.098002          -0.113644        -0.115786        0.013023              564           -0.088457           -0.093153           -0.094672           -0.097365           -0.093476         -0.093424         0.002892
26        0.249625      0.022427         0.110940        0.006237            9.041323                                               mean              {'model__alpha': 9.04132260279468, 'preprocess...          -0.136595          -0.122200          -0.108513          -0.098006          -0.113637        -0.115790        0.013022              585           -0.088461           -0.093156           -0.094668           -0.097364           -0.093476         -0.093425         0.002891
27        0.256547      0.030229         0.111872        0.006214            9.041323                                             median              {'model__alpha': 9.04132260279468, 'preprocess...          -0.136604          -0.122172          -0.108508          -0.098002          -0.113643        -0.115786        0.013023              562           -0.088459           -0.093155           -0.094673           -0.097366           -0.093477         -0.093426         0.002892
28        0.304177      0.067437         0.113572        0.005747            9.044509                                               mean              {'model__alpha': 9.044509112051967, 'preproces...          -0.136595          -0.122199          -0.108512          -0.098007          -0.113637        -0.115790        0.013021              583           -0.088462           -0.093157           -0.094670           -0.097365           -0.093478         -0.093426         0.002891
29        0.289310      0.054484         0.143085        0.035049            9.044509                                             median              {'model__alpha': 9.044509112051967, 'preproces...          -0.136604          -0.122171          -0.108507          -0.098002          -0.113643        -0.115786        0.013023              560           -0.088460           -0.093156           -0.094675           -0.097368           -0.093478         -0.093427         0.002893
30        0.297357      0.049617         0.120957        0.000767            9.047697                                               mean              {'model__alpha': 9.047696744357479, 'preproces...          -0.136594          -0.122199          -0.108511          -0.098007          -0.113637        -0.115790        0.013021              581           -0.088464           -0.093159           -0.094672           -0.097366           -0.093479         -0.093428         0.002891
31        0.283832      0.040805         0.136830        0.057511            9.047697                                             median              {'model__alpha': 9.047696744357479, 'preproces...          -0.136604          -0.122171          -0.108507          -0.098003          -0.113643        -0.115785        0.013023              558           -0.088461           -0.093158           -0.094676           -0.097369           -0.093480         -0.093429         0.002893
32        0.265270      0.031186         0.119425        0.008516            9.050886                                               mean              {'model__alpha': 9.050885500107013, 'preproces...          -0.136594          -0.122198          -0.108511          -0.098007          -0.113637        -0.115789        0.013021              579           -0.088465           -0.093160           -0.094673           -0.097368           -0.093480         -0.093429         0.002891
33        0.299346      0.038182         0.111066        0.009989            9.050886                                             median              {'model__alpha': 9.050885500107013, 'preproces...          -0.136603          -0.122170          -0.108506          -0.098003          -0.113643        -0.115785        0.013023              556           -0.088463           -0.093159           -0.094678           -0.097370           -0.093481         -0.093430         0.002893
34        0.236007      0.014161         0.111771        0.004482            9.054075                                               mean              {'model__alpha': 9.054075379696513, 'preproces...          -0.136593          -0.122197          -0.108510          -0.098007          -0.113637        -0.115789        0.013021              577           -0.088466           -0.093162           -0.094675           -0.097369           -0.093482         -0.093431         0.002891
35        0.281253      0.067879         0.127168        0.019263            9.054075                                             median              {'model__alpha': 9.054075379696513, 'preproces...          -0.136603          -0.122169          -0.108505          -0.098003          -0.113643        -0.115785        0.013022              554           -0.088464           -0.093161           -0.094680           -0.097372           -0.093482         -0.093432         0.002893
36        0.321013      0.062613         0.109979        0.006899            9.057266                                               mean              {'model__alpha': 9.057266383522071, 'preproces...          -0.136593          -0.122196          -0.108509          -0.098008          -0.113637        -0.115789        0.013020              575           -0.088468           -0.093163           -0.094677           -0.097370           -0.093483         -0.093432         0.002891
37        0.245997      0.014952         0.113833        0.016012            9.057266                                             median              {'model__alpha': 9.057266383522071, 'preproces...          -0.136602          -0.122168          -0.108504          -0.098003          -0.113643        -0.115784        0.013022              552           -0.088465           -0.093162           -0.094681           -0.097373           -0.093484         -0.093433         0.002893
38        0.256318      0.036833         0.115857        0.011529            9.060459                                               mean              {'model__alpha': 9.060458511979904, 'preproces...          -0.136593          -0.122195          -0.108509          -0.098008          -0.113637        -0.115788        0.013020              573           -0.088469           -0.093165           -0.094678           -0.097372           -0.093484         -0.093434         0.002891
39        0.284697      0.049210         0.116260        0.007661            9.060459                                             median              {'model__alpha': 9.060458511979904, 'preproces...          -0.136602          -0.122167          -0.108504          -0.098004          -0.113643        -0.115784        0.013022              550           -0.088467           -0.093164           -0.094683           -0.097374           -0.093485         -0.093434         0.002893

### Full Pipeline (Lasso) ###

In [123]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV, KFold

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Lasso(max_iter=10000))
])

param_grid = {
    'preprocessor__preprocessor__num_impute__impute__strategy': ['mean', 'median'],
    # 'model__alpha': [.0005, .0006, .0007, .0008, .0009, .001, .005, .01, .05, .1, .5, 1, 5, 10],
    'model__alpha': np.logspace(-4, 1, 300),
}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
    verbose=1,
    n_jobs=-1
)

search.fit(X_train, y_train_t)
cv_results_df = pd.DataFrame(search.cv_results_)

cv_results_df

Fitting 5 folds for each of 600 candidates, totalling 3000 fits

     mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_model__alpha param_preprocessor__preprocessor__num_impute__impute__strategy                                             params  split0_test_score  split1_test_score  split2_test_score  split3_test_score  split4_test_score  mean_test_score  std_test_score  rank_test_score  split0_train_score  split1_train_score  split2_train_score  split3_train_score  split4_train_score  mean_train_score  std_train_score
0         0.798562      0.288849         0.192542        0.053236            0.000100                                               mean              {'model__alpha': 0.0001, 'preprocessor__prepro...          -0.156672          -0.126751          -0.205040          -0.131516          -0.151069        -0.154210        0.027816              184           -0.091772           -0.092366           -0.093926           -0.093994           -0.088841         -0.092180         0.001881
1         0.494709      0.080717         0.153101        0.040209            0.000100                                             median              {'model__alpha': 0.0001, 'preprocessor__prepro...          -0.156628          -0.126733          -0.205042          -0.131520          -0.151075        -0.154200        0.027819              183           -0.091784           -0.092372           -0.093927           -0.093998           -0.088841         -0.092184         0.001882
2         0.605070      0.101625         0.159681        0.027988            0.000104                                               mean              {'model__alpha': 0.00010392556829367131, 'prep...          -0.156585          -0.126356          -0.205113          -0.130929          -0.150560        -0.153909        0.028027              178           -0.091921           -0.092515           -0.094042           -0.094112           -0.089000         -0.092318         0.001865
3         0.627594      0.091575         0.162277        0.035550            0.000104                                             median              {'model__alpha': 0.00010392556829367131, 'prep...          -0.156541          -0.126338          -0.205119          -0.130930          -0.150566        -0.153899        0.028031              177           -0.091933           -0.092521           -0.094042           -0.094116           -0.089000         -0.092322         0.001866
4         0.411241      0.058485         0.140560        0.040918            0.000108                                               mean              {'model__alpha': 0.00010800523745162529, 'prep...          -0.156482          -0.125957          -0.205170          -0.130335          -0.150103        -0.153609        0.028232              172           -0.092078           -0.092674           -0.094143           -0.094230           -0.089164         -0.092458         0.001845
5         0.460329      0.098281         0.147776        0.047190            0.000108                                             median              {'model__alpha': 0.00010800523745162529, 'prep...          -0.156440          -0.125939          -0.205177          -0.130338          -0.150107        -0.153600        0.028237              171           -0.092090           -0.092680           -0.094143           -0.094234           -0.089163         -0.092462         0.001846
6         0.462331      0.079025         0.160286        0.045095            0.000112                                               mean              {'model__alpha': 0.0001122450568085307, 'prepr...          -0.156337          -0.125553          -0.205220          -0.129715          -0.149639        -0.153293        0.028441              168           -0.092240           -0.092846           -0.094238           -0.094355           -0.089328         -0.092601         0.001825
7         0.455558      0.073185         0.119823        0.008281            0.000112                                             median              {'model__alpha': 0.0001122450568085307, 'prepr...          -0.156304          -0.125536          -0.205228          -0.129724          -0.149644        -0.153287        0.028445              167           -0.092252           -0.092852           -0.094238           -0.094359           -0.089328         -0.092606         0.001826
8         0.471180      0.173373         0.122983        0.003217            0.000117                                               mean              {'model__alpha': 0.00011665131316981962, 'prep...          -0.156127          -0.125137          -0.205257          -0.129080          -0.149141        -0.152949        0.028650              164           -0.092409           -0.093030           -0.094335           -0.094490           -0.089469         -0.092747         0.001817
9         0.557206      0.164909         0.121148        0.003691            0.000117                                             median              {'model__alpha': 0.00011665131316981962, 'prep...          -0.156096          -0.125121          -0.205262          -0.129090          -0.149147        -0.152943        0.028652              163           -0.092422           -0.093036           -0.094336           -0.094495           -0.089469         -0.092751         0.001817
10        0.506062      0.182624         0.130083        0.020510            0.000121                                               mean              {'model__alpha': 0.00012123054013376529, 'prep...          -0.155935          -0.124693          -0.205287          -0.128442          -0.148599        -0.152591        0.028863              160           -0.092588           -0.093222           -0.094436           -0.094634           -0.089623         -0.092901         0.001806
11        0.471784      0.181746         0.122868        0.004736            0.000121                                             median              {'model__alpha': 0.00012123054013376529, 'prep...          -0.155904          -0.124678          -0.205293          -0.128452          -0.148606        -0.152587        0.028866              159           -0.092600           -0.093228           -0.094437           -0.094639           -0.089623         -0.092905         0.001807
12        0.456206      0.139479         0.122834        0.004421            0.000126                                               mean              {'model__alpha': 0.0001259895277795027, 'prepr...          -0.155743          -0.124259          -0.205293          -0.127792          -0.148046        -0.152227        0.029069              156           -0.092775           -0.093427           -0.094542           -0.094788           -0.089790         -0.093064         0.001794
13        0.472820      0.149264         0.122400        0.010735            0.000126                                             median              {'model__alpha': 0.0001259895277795027, 'prepr...          -0.155712          -0.124247          -0.205300          -0.127804          -0.148053        -0.152223        0.029071              155           -0.092787           -0.093433           -0.094543           -0.094793           -0.089790         -0.093069         0.001795
14        0.424198      0.133802         0.131020        0.018263            0.000131                                               mean              {'model__alpha': 0.0001309353327353611, 'prepr...          -0.155543          -0.123830          -0.205303          -0.127144          -0.147483        -0.151861        0.029276              152           -0.092972           -0.093631           -0.094652           -0.094947           -0.089969         -0.093234         0.001779
15        0.419453      0.148578         0.128027        0.014980            0.000131                                             median              {'model__alpha': 0.0001309353327353611, 'prepr...          -0.155514          -0.123819          -0.205310          -0.127155          -0.147491        -0.151858        0.029278              151           -0.092984           -0.093637           -0.094653           -0.094952           -0.089969         -0.093239         0.001780
16        0.444983      0.122436         0.124310        0.011946            0.000136                                               mean              {'model__alpha': 0.00013607528864243332, 'prep...          -0.155334          -0.123407          -0.205317          -0.126487          -0.146917        -0.151493        0.029485              148           -0.093174           -0.093839           -0.094764           -0.095118           -0.090158         -0.093411         0.001765
17        0.441054      0.151183         0.127658        0.023160            0.000136                                             median              {'model__alpha': 0.00013607528864243332, 'prep...          -0.155306          -0.123399          -0.205323          -0.126498          -0.146924        -0.151490        0.029486              147           -0.093186           -0.093846           -0.094765           -0.095124           -0.090158         -0.093416         0.001766
18        0.408862      0.113941         0.118584        0.009555            0.000141                                               mean              {'model__alpha': 0.0001414170170289024, 'prepr...          -0.155154          -0.122997          -0.205336          -0.125829          -0.146335        -0.151130        0.029695              144           -0.093371           -0.094063           -0.094879           -0.095297           -0.090363         -0.093595         0.001747
19        0.430125      0.117938         0.120112        0.010757            0.000141                                             median              {'model__alpha': 0.0001414170170289024, 'prepr...          -0.155129          -0.122989          -0.205343          -0.125840          -0.146343        -0.151129        0.029697              143           -0.093384           -0.094069           -0.094880           -0.095301           -0.090363         -0.093600         0.001748
20        0.421790      0.129994         0.115376        0.004646            0.000147                                               mean              {'model__alpha': 0.0001469684386112446, 'prepr...          -0.154954          -0.122584          -0.205361          -0.125162          -0.145735        -0.150759        0.029911              140           -0.093521           -0.094307           -0.094999           -0.095479           -0.090587         -0.093779         0.001727
21        0.415445      0.119703         0.119123        0.007433            0.000147                                             median              {'model__alpha': 0.0001469684386112446, 'prepr...          -0.154931          -0.122577          -0.205362          -0.125170          -0.145742        -0.150756        0.029910              139           -0.093536           -0.094313           -0.095000           -0.095485           -0.090587         -0.093784         0.001728
22        0.412573      0.099684         0.121131        0.016838            0.000153                                               mean              {'model__alpha': 0.0001527377850390714, 'prepr...          -0.154773          -0.122180          -0.205403          -0.124493          -0.145190        -0.150408        0.030130              136           -0.093671           -0.094567           -0.095126           -0.095653           -0.090791         -0.093962         0.001716
23        0.396842      0.130912         0.123152        0.011172            0.000153                                             median              {'model__alpha': 0.0001527377850390714, 'prepr...          -0.154750          -0.122173          -0.205404          -0.124502          -0.145197        -0.150405        0.030129              135           -0.093686           -0.094574           -0.095127           -0.095658           -0.090792         -0.093967         0.001717
24        0.397260      0.137172         0.121772        0.008670            0.000159                                               mean              {'model__alpha': 0.00015873361110102087, 'prep...          -0.154596          -0.121822          -0.205463          -0.123775          -0.144668        -0.150065        0.030356              134           -0.093832           -0.094767           -0.095255           -0.095831           -0.090992         -0.094136         0.001703
25        0.391953      0.144786         0.117569        0.005957            0.000159                                             median              {'model__alpha': 0.00015873361110102087, 'prep...          -0.154572          -0.121815          -0.205464          -0.123786          -0.144675        -0.150062        0.030355              132           -0.093848           -0.094776           -0.095256           -0.095837           -0.090992         -0.094142         0.001704
26        0.389148      0.142955         0.112398        0.005796            0.000165                                               mean              {'model__alpha': 0.00016496480740980208, 'prep...          -0.154435          -0.121476          -0.205527          -0.123037          -0.144143        -0.149724        0.030586              130           -0.094003           -0.094969           -0.095385           -0.096020           -0.091203         -0.094316         0.001689
27        0.403131      0.135126         0.115876        0.003062            0.000165                                             median              {'model__alpha': 0.00016496480740980208, 'prep...          -0.154409          -0.121469          -0.205523          -0.123043          -0.144150        -0.149719        0.030584              129           -0.094018           -0.094977           -0.095385           -0.096026           -0.091204         -0.094322         0.001690
28        0.391223      0.083371         0.122516        0.010694            0.000171                                               mean              {'model__alpha': 0.00017144061358519703, 'prep...          -0.154270          -0.121145          -0.205606          -0.122287          -0.143613        -0.149384        0.030821              126           -0.094174           -0.095181           -0.095527           -0.096221           -0.091421         -0.094505         0.001677
29        0.379854      0.087899         0.109714        0.003746            0.000171                                             median              {'model__alpha': 0.00017144061358519703, 'prep...          -0.154245          -0.121138          -0.205602          -0.122293          -0.143621        -0.149380        0.030819              125           -0.094189           -0.095191           -0.095527           -0.096227           -0.091421         -0.094511         0.001679
30        0.372562      0.084070         0.122283        0.010318            0.000178                                               mean              {'model__alpha': 0.00017817063195457307, 'prep...          -0.154119          -0.120826          -0.205720          -0.121524          -0.143077        -0.149053        0.031071              122           -0.094346           -0.095406           -0.095664           -0.096434           -0.091649         -0.094700         0.001666
31        0.411029      0.108799         0.117109        0.001599            0.000178                                             median              {'model__alpha': 0.00017817063195457307, 'prep...          -0.154098          -0.120821          -0.205716          -0.121523          -0.143086        -0.149049        0.031070              121           -0.094361           -0.095414           -0.095664           -0.096439           -0.091649         -0.094706         0.001667
32        0.398995      0.081959         0.129339        0.015376            0.000185                                               mean              {'model__alpha': 0.0001851648417912154, 'prepr...          -0.153984          -0.120537          -0.205845          -0.120747          -0.142574        -0.148737        0.031323              120           -0.094523           -0.095636           -0.095801           -0.096659           -0.091881         -0.094900         0.001655
33        0.380287      0.105719         0.145281        0.042125            0.000185                                             median              {'model__alpha': 0.0001851648417912154, 'prepr...          -0.153964          -0.120531          -0.205836          -0.120745          -0.142583        -0.148732        0.031320              119           -0.094538           -0.095643           -0.095802           -0.096665           -0.091882         -0.094906         0.001656
34        0.423945      0.140360         0.156485        0.063890            0.000192                                               mean              {'model__alpha': 0.000192433614111598, 'prepro...          -0.153769          -0.120265          -0.205949          -0.119982          -0.142092        -0.148411        0.031558              116           -0.094679           -0.095851           -0.095934           -0.096898           -0.092117         -0.095096         0.001647
35        0.390899      0.079016         0.126208        0.009297            0.000192                                             median              {'model__alpha': 0.000192433614111598, 'prepro...          -0.153748          -0.120261          -0.205938          -0.119980          -0.142099        -0.148405        0.031554              115           -0.094693           -0.095859           -0.095935           -0.096903           -0.092117         -0.095102         0.001649
36        0.415315      0.118127         0.176473        0.055391            0.000200                                               mean              {'model__alpha': 0.0001999877270535285, 'prepr...          -0.153540          -0.120006          -0.206047          -0.119233          -0.141592        -0.148084        0.031788              112           -0.094837           -0.096083           -0.096071           -0.097153           -0.092363         -0.095301         0.001642
37        0.421689      0.066269         0.138373        0.023925            0.000200                                             median              {'model__alpha': 0.0001999877270535285, 'prepr...          -0.153520          -0.120002          -0.206036          -0.119230          -0.141599        -0.148077        0.031784              111           -0.094851           -0.096091           -0.096072           -0.097158           -0.092363         -0.095307         0.001643
38        0.435836      0.200727         0.154536        0.071317            0.000208                                               mean              {'model__alpha': 0.00020783838185797573, 'prep...          -0.153312          -0.119824          -0.206114          -0.118486          -0.141080        -0.147763        0.031994              108           -0.095005           -0.096305           -0.096216           -0.097424           -0.092614         -0.095513         0.001639
39        0.463465      0.106848         0.117112        0.005532            0.000208                                             median              {'model__alpha': 0.00020783838185797573, 'prep...          -0.153293          -0.119818          -0.206102          -0.118483          -0.141088        -0.147757        0.031990              107           -0.095018           -0.096314           -0.096217           -0.097429           -0.092614         -0.095518         0.001640

### Final Pipeline (ElasticNet) ###

In [81]:
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import GridSearchCV, cross_validate
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', ElasticNet(max_iter=10000))
])

param_grid = {
    'preprocessor__preprocessor__num_impute__impute__strategy':
        ['mean', 'median'],
    # 'model__alpha':
    #     [.0005, .001, .002, .005, .1, .5, 1],
    # 'model__l1_ratio':
    #     [.1, .2, .3, .4, .5, .6, .7, .8, .9],

    'model__alpha':
        np.logspace(-4, 1, 30),
    'model__l1_ratio':
        np.linspace(.05, .95, 20)
}

# {\'model__alpha\': 0.0007278953843983154, \'model__l1_ratio\': 0.7131578947368421, \'preprocessor__preprocessor__num_impute__impute__strategy\': \'mean\'}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
    verbose=1,
    n_jobs=-1,
)

search.fit(X_train, y_train_t)
cv_results_df = pd.DataFrame(search.cv_results_)
cv_results_df

Fitting 5 folds for each of 1200 candidates, totalling 6000 fits

      mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_model__alpha  param_model__l1_ratio param_preprocessor__preprocessor__num_impute__impute__strategy                                             params  split0_test_score  split1_test_score  split2_test_score  split3_test_score  split4_test_score  mean_test_score  std_test_score  rank_test_score  split0_train_score  split1_train_score  split2_train_score  split3_train_score  split4_train_score  mean_train_score  std_train_score
0          3.314577      3.392029         0.261353        0.102276            0.000100               0.050000                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.142375          -0.137402          -0.130484          -0.106842          -0.124139        -0.128248        0.012357              569           -0.081123           -0.083706           -0.085303           -0.089008           -0.085955         -0.085019         0.002599
1          3.442399      2.941844         0.192308        0.057177            0.000100               0.050000                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.142391          -0.137390          -0.130474          -0.106837          -0.124179        -0.128254        0.012358              570           -0.081118           -0.083703           -0.085311           -0.089008           -0.085951         -0.085018         0.002601
2          2.970581      2.475001         0.202630        0.048384            0.000100               0.097368                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.142077          -0.136683          -0.129734          -0.106614          -0.123047        -0.127631        0.012311              557           -0.081194           -0.083776           -0.085358           -0.089078           -0.086018         -0.085085         0.002598
3          2.901912      2.743442         0.165322        0.021030            0.000100               0.097368                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.142090          -0.136672          -0.129723          -0.106611          -0.123089        -0.127637        0.012310              558           -0.081189           -0.083773           -0.085365           -0.089079           -0.086013         -0.085084         0.002600
4          2.308816      2.204081         0.221125        0.096675            0.000100               0.144737                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.141703          -0.135960          -0.129092          -0.106259          -0.122393        -0.127081        0.012265              547           -0.081276           -0.083859           -0.085419           -0.089161           -0.086085         -0.085160         0.002596
5          2.324319      1.797121         0.164558        0.032120            0.000100               0.144737                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.141714          -0.135950          -0.129075          -0.106256          -0.122427        -0.127085        0.012265              548           -0.081271           -0.083857           -0.085426           -0.089162           -0.086081         -0.085159         0.002598
6          0.782089      0.147618         0.160000        0.036521            0.000100               0.192105                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.141331          -0.135335          -0.128693          -0.105867          -0.121816        -0.126608        0.012251              541           -0.081369           -0.083954           -0.085487           -0.089250           -0.086162         -0.085245         0.002593
7          0.700925      0.133491         0.168572        0.035241            0.000100               0.192105                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.141340          -0.135326          -0.128675          -0.105863          -0.121848        -0.126610        0.012250              542           -0.081364           -0.083952           -0.085495           -0.089251           -0.086159         -0.085244         0.002595
8          0.659668      0.188697         0.134308        0.012748            0.000100               0.239474                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140978          -0.134776          -0.128283          -0.105502          -0.121283        -0.126164        0.012238              525           -0.081472           -0.084059           -0.085558           -0.089341           -0.086237         -0.085334         0.002587
9          0.550341      0.162798         0.135884        0.024841            0.000100               0.239474                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140987          -0.134767          -0.128265          -0.105499          -0.121315        -0.126167        0.012237              526           -0.081467           -0.084056           -0.085566           -0.089342           -0.086234         -0.085333         0.002589
10         0.432101      0.042047         0.128121        0.018436            0.000100               0.286842                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140682          -0.134239          -0.127883          -0.105214          -0.120781        -0.125760        0.012215              515           -0.081584           -0.084178           -0.085635           -0.089440           -0.086318         -0.085431         0.002579
11         0.517599      0.109086         0.177276        0.098828            0.000100               0.286842                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140688          -0.134233          -0.127864          -0.105208          -0.120812        -0.125761        0.012214              516           -0.081579           -0.084175           -0.085643           -0.089440           -0.086315         -0.085431         0.002581
12         0.631517      0.216063         0.153084        0.041715            0.000100               0.334211                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140441          -0.133776          -0.127484          -0.105039          -0.120279        -0.125404        0.012178              505           -0.081704           -0.084308           -0.085718           -0.089548           -0.086405         -0.085536         0.002572
13         0.529106      0.186814         0.145191        0.027696            0.000100               0.334211                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140447          -0.133769          -0.127470          -0.105034          -0.120312        -0.125406        0.012177              506           -0.081699           -0.084305           -0.085725           -0.089549           -0.086401         -0.085536         0.002574
14         0.552189      0.217138         0.141491        0.036974            0.000100               0.381579                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140206          -0.133307          -0.127042          -0.104932          -0.119774        -0.125052        0.012120              495           -0.081828           -0.084444           -0.085806           -0.089668           -0.086498         -0.085649         0.002567
15         0.574494      0.199253         0.147601        0.027059            0.000100               0.381579                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.140211          -0.133296          -0.127027          -0.104928          -0.119808        -0.125054        0.012117              498           -0.081823           -0.084442           -0.085814           -0.089669           -0.086495         -0.085649         0.002569
16         0.468821      0.066591         0.137916        0.027045            0.000100               0.428947                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139981          -0.132855          -0.126592          -0.104873          -0.119280        -0.124716        0.012051              483           -0.081962           -0.084583           -0.085900           -0.089799           -0.086602         -0.085769         0.002563
17         0.588219      0.196457         0.132082        0.003334            0.000100               0.428947                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139985          -0.132846          -0.126579          -0.104869          -0.119313        -0.124718        0.012048              484           -0.081957           -0.084581           -0.085908           -0.089800           -0.086599         -0.085769         0.002565
18         1.348194      1.520391         0.177076        0.069603            0.000100               0.476316                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139788          -0.132442          -0.126166          -0.104730          -0.118795        -0.124384        0.012024              473           -0.082105           -0.084730           -0.086001           -0.089925           -0.086715         -0.085895         0.002555
19         1.427645      1.696000         0.136566        0.012096            0.000100               0.476316                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139794          -0.132435          -0.126152          -0.104728          -0.118828        -0.124387        0.012022              474           -0.082101           -0.084728           -0.086009           -0.089926           -0.086712         -0.085895         0.002557
20         1.439845      1.434461         0.148225        0.009856            0.000100               0.523684                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139624          -0.132020          -0.125749          -0.104583          -0.118344        -0.124064        0.012004              461           -0.082257           -0.084888           -0.086109           -0.090061           -0.086832         -0.086030         0.002547
21         1.436998      1.346259         0.203399        0.088045            0.000100               0.523684                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139630          -0.132008          -0.125735          -0.104581          -0.118378        -0.124066        0.012001              462           -0.082254           -0.084885           -0.086117           -0.090062           -0.086829         -0.086029         0.002548
22         1.421560      1.192956         0.166564        0.056754            0.000100               0.571053                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139503          -0.131551          -0.125320          -0.104441          -0.117911        -0.123745        0.011987              453           -0.082417           -0.085037           -0.086220           -0.090198           -0.086955         -0.086165         0.002538
23         1.185331      1.059183         0.157103        0.025159            0.000100               0.571053                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139511          -0.131538          -0.125308          -0.104440          -0.117945        -0.123748        0.011984              454           -0.082413           -0.085033           -0.086229           -0.090200           -0.086952         -0.086165         0.002540
24         1.094799      0.966757         0.136741        0.006086            0.000100               0.618421                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139386          -0.131120          -0.124891          -0.104291          -0.117516        -0.123441        0.011976              445           -0.082569           -0.085171           -0.086340           -0.090324           -0.087075         -0.086296         0.002530
25         1.178187      0.876217         0.142532        0.018147            0.000100               0.618421                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139393          -0.131108          -0.124880          -0.104290          -0.117551        -0.123444        0.011973              446           -0.082565           -0.085168           -0.086348           -0.090326           -0.087072         -0.086296         0.002531
26         1.064172      0.924308         0.136546        0.009779            0.000100               0.665789                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139233          -0.130679          -0.124454          -0.104144          -0.117118        -0.123125        0.011955              433           -0.082709           -0.085311           -0.086465           -0.090451           -0.087202         -0.086428         0.002524
27         1.101287      1.022222         0.136148        0.011207            0.000100               0.665789                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139240          -0.130666          -0.124441          -0.104144          -0.117157        -0.123130        0.011952              434           -0.082706           -0.085308           -0.086472           -0.090453           -0.087199         -0.086428         0.002526
28         0.971108      0.800472         0.131575        0.004788            0.000100               0.713158                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139086          -0.130231          -0.124002          -0.103963          -0.116717        -0.122800        0.011948              425           -0.082859           -0.085455           -0.086594           -0.090577           -0.087333         -0.086564         0.002516
29         0.990733      0.765067         0.163613        0.035198            0.000100               0.713158                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.139093          -0.130219          -0.123986          -0.103964          -0.116754        -0.122803        0.011944              426           -0.082856           -0.085451           -0.086602           -0.090579           -0.087330         -0.086564         0.002518
30         0.922026      0.719146         0.132476        0.005127            0.000100               0.760526                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138946          -0.129803          -0.123563          -0.103782          -0.116333        -0.122486        0.011944              409           -0.083016           -0.085591           -0.086726           -0.090711           -0.087470         -0.086703         0.002509
31         0.873040      0.679692         0.132822        0.002887            0.000100               0.760526                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138954          -0.129798          -0.123548          -0.103784          -0.116368        -0.122491        0.011941              410           -0.083013           -0.085587           -0.086733           -0.090712           -0.087467         -0.086702         0.002511
32         1.011190      0.573338         0.151838        0.038907            0.000100               0.807895                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138822          -0.129405          -0.123153          -0.103561          -0.115998        -0.122188        0.011958              403           -0.083181           -0.085723           -0.086849           -0.090831           -0.087606         -0.086838         0.002496
33         1.078210      0.585978         0.136909        0.011702            0.000100               0.807895                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138824          -0.129393          -0.123137          -0.103563          -0.116035        -0.122190        0.011953              404           -0.083177           -0.085720           -0.086857           -0.090832           -0.087603         -0.086838         0.002497
34         1.164032      0.472055         0.129932        0.007629            0.000100               0.855263                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138713          -0.129009          -0.122715          -0.103310          -0.115663        -0.121882        0.011987              389           -0.083338           -0.085863           -0.086965           -0.090946           -0.087748         -0.086972         0.002483
35         1.187087      0.517978         0.127646        0.004046            0.000100               0.855263                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138722          -0.128997          -0.122698          -0.103308          -0.115698        -0.121885        0.011984              390           -0.083335           -0.085860           -0.086972           -0.090947           -0.087744         -0.086972         0.002484
36         1.241549      0.415314         0.128762        0.012856            0.000100               0.902632                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138616          -0.128617          -0.122269          -0.103056          -0.115336        -0.121579        0.012020              381           -0.083494           -0.086011           -0.087084           -0.091061           -0.087879         -0.087106         0.002469
37         1.218247      0.386542         0.127331        0.004989            0.000100               0.902632                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.138624          -0.128604          -0.122252          -0.103054          -0.115369        -0.121581        0.012017              382           -0.083491           -0.086008           -0.087091           -0.091062           -0.087875         -0.087105         0.002471

In [121]:
from sklearn.metrics import root_mean_squared_error
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', ElasticNet(alpha=0.0007278953843983154, l1_ratio=0.7131578947368421))
])
final_pipeline.fit(X_train, y_train_t)
y_pred = final_pipeline.predict(X_test)
print(root_mean_squared_error(y_test_t, y_pred))

y_pred = final_pipeline.predict(X_train)
print(root_mean_squared_error(y_train_t, y_pred))



# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', Lasso(alpha=.0007934096665797492))
# ])
# final_pipeline.fit(X_train, y_train_t)
# y_pred = final_pipeline.predict(X_test)
# print(root_mean_squared_error(y_test_t, y_pred))
#
# y_pred = final_pipeline.predict(X_train)
# print(root_mean_squared_error(y_train_t, y_pred))
#
#
# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', LinearRegression())
# ])
# final_pipeline.fit(X_train, y_train_t)
# y_pred = final_pipeline.predict(X_test)
# print(root_mean_squared_error(y_test_t, y_pred))
#
# y_pred = final_pipeline.predict(X_train)
# print(root_mean_squared_error(y_train_t, y_pred))

0.11544915376776345
0.10881045553882318
0.1156369745205326
0.11243910374712052
0.12966410509994647
0.09419088615888568

In [189]:
final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Ridge(alpha=400))
])

cv_results = cross_validate(
    final_pipeline, X_train, y_train_t,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
)

cv_results_df = pd.DataFrame(cv_results)

train_root_mean_squared_error = -cv_results_df.mean()['train_score']
validation_root_mean_squared_error = -cv_results_df.mean()['test_score']

print(f'train_rmse: {train_root_mean_squared_error}')
print(f'validation_rmse: {validation_root_mean_squared_error}')

train_rmse: 0.10310912196089887
validation_rmse: 0.13957445547139208

In [124]:
# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', ElasticNet(alpha=0.0007278953843983154, l1_ratio=0.7131578947368421))
# ])

# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', Ridge(alpha=9.846791241561434))
# ])

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Lasso(alpha=0.0006348565216305217))
])

test = pd.read_csv(PATH + '/test.csv')
test_ids = test['Id']

# final_pipeline.fit(pd.concat([X_train, X_test], axis=0, ignore_index=True), pd.concat([y_train_t, y_test_t], axis=0, ignore_index=True))
final_pipeline.fit(X_train, y_train_t)
prices_log = final_pipeline.predict(test)
prices = np.expm1(prices_log)

submission = pd.DataFrame({
    'Id': test_ids,
    'SalePrice': prices,
})

submission.to_csv('submission.csv', index=False)