In [85]:
import pandas as pd
import numpy as np

In [86]:
PATH = './data'
TARGET = 'SalePrice'

In [87]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)

In [88]:
df = pd.read_csv(PATH + "/train.csv")

In [89]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold

X = df.drop(columns=[TARGET])
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=.2, shuffle=True, random_state=1337
)

train_ids = X_train["Id"]
test_ids = X_test["Id"]

print(f"X_train shape {X_train.shape}")
print(f"X_test shape {X_test.shape}")

X_train shape (1168, 80)
X_test shape (292, 80)

### Data Cleaning ###

### Categorical Imputing ###

In [90]:
# we first impute all missing values in categorical and numeric features.

# These categorical columns may have 'NaN' values in them which means missing.
# data_description.txt did not mention 'Nan' was intended.

cat_impute_cols = [
    'MSZoning',
    'Street',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'Foundation',
    'ExterQual',
    'ExterCond',
    'Heating',
    'HeatingQC',
    'CentralAir',
    'Electrical',
    'KitchenQual',
    'Functional',
    'PavedDrive',
    'SaleType',
    'SaleCondition',
]

### Numeric Imputing ###

In [91]:
# We impute all numeric columns because data_description.txt did not mention any numeric feature with intended 'NaN' value.

# num_impute_cols = [
#     'LotFrontage',
#     'GarageYrBlt',
#     'MasVnrArea',
# ]

num_impute_cols = list(X_train.select_dtypes(exclude='object').columns)
num_impute_cols.remove('Id')
num_impute_cols.remove('MSSubClass')

### Categorical One-Hot-Encoded Columns ###

In [92]:
# Here we list features to be one-hot-encoded including 'NaN's because 'NaN' here does not mean missing.
# 'MasVnrType' was interesting column here.

cat_ohe_cols = [
    'MSZoning',
    'Street',
    'Alley',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'MasVnrType',
    'Foundation',
    'Heating',
    'CentralAir',
    'Electrical',
    'GarageType',
    'PavedDrive',
    'MiscFeature',
    'SaleType',
    'SaleCondition',
]

cat_ohe_missing_cols = [
    'MSZoning',
    'Street',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'Foundation',
    'Heating',
    'CentralAir',
    'Electrical',
    'PavedDrive',
    'SaleType',
    'SaleCondition'
]

cat_ohe_absent_cols = [
    'Alley',
    'MasVnrType',
    'GarageType',
    'MiscFeature'
]

### Ordinal Columns ###

In [93]:
# Some categorical columns can may be ordered, replace them with numbers.

cat_ord_cols = [
    'ExterQual',
    'ExterCond',
    'BsmtQual',
    'BsmtCond',
    'BsmtExposure',
    'BsmtFinType1',
    'BsmtFinType2',
    'HeatingQC',
    'KitchenQual',
    'Functional',
    'FireplaceQu',
    'GarageFinish',
    'GarageQual',
    'GarageCond',
    'PoolQC',
    'Fence',
]

cat_ord_missing_cols = [
    'ExterQual',
    'ExterCond',
    'HeatingQC',
    'KitchenQual',
    'Functional',
]

cat_ord_absent_cols = [
    'BsmtQual',
    'BsmtCond',
    'BsmtExposure',
    'BsmtFinType1',
    'BsmtFinType2',
    'FireplaceQu',
    'GarageFinish',
    'GarageQual',
    'GarageCond',
    'PoolQC',
    'Fence',
]

exter_qual_order        = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
exter_cond_order        = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
bsmt_qual_order         = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
bsmt_cond_order         = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
bsmt_exposure_order     = ['NA', 'No', 'Mn', 'Av', 'Gd']
bsmt_fin_type_1_order   = ['NA', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ']
bsmt_fin_type_2_order   = ['NA', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ']
heating_qc_order        = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
kitchen_qual_order      = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
functional_order        = ['Sal', 'Sev', 'Maj2', 'Maj1', 'Mod', 'Min2', 'Min1', 'Typ']
fireplace_qu_order      = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
garage_finish_order     = ['NA', 'Unf', 'RFn', 'Fin']
garage_qual_order       = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
garage_cond_order       = ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
pool_qc_order           = ['NA', 'Fa', 'TA', 'Gd', 'Ex']
fence_order             = ['NA', 'MnWw', 'GdWo', 'MnPrv', 'GdPrv']

cat_ord_missing_categories = [
    exter_qual_order,
    exter_cond_order,
    heating_qc_order,
    kitchen_qual_order,
    functional_order,
]

cat_ord_absent_categories = [
    bsmt_qual_order,
    bsmt_cond_order,
    bsmt_exposure_order,
    bsmt_fin_type_1_order,
    bsmt_fin_type_2_order,
    fireplace_qu_order,
    garage_finish_order,
    garage_qual_order,
    garage_cond_order,
    pool_qc_order,
    fence_order,
]

### Numeric One-Hot-Encoded Columns ###

In [94]:
# This feature has numeric type which is misleading.

num_ohe_cols = [
    'MSSubClass',
]

### Data Cleanup Pipeline ###

In [99]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

num_impute_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='median')),
    ('scale',   StandardScaler())
])

num_ohe_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='most_frequent')),
    ('ohe',     OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

cat_ord_missing_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='most_frequent')),
    ('ordinal', OrdinalEncoder(categories=cat_ord_missing_categories)),
])

cat_ord_absent_pipeline = Pipeline([
    ('nan_impute',  SimpleImputer(strategy='constant', missing_values=np.nan, fill_value='NA')),
    ('ordinal',     OrdinalEncoder(categories=cat_ord_absent_categories)),
])

cat_ohe_missing_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='most_frequent')),
    ('ohe',     OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
])

cat_ohe_absent_pipeline = Pipeline([
    ('impute',  SimpleImputer(strategy='constant', missing_values=np.nan, fill_value='Missing')),
    ('ohe',     OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num_impute',       num_impute_pipeline,       num_impute_cols),
        ('num_ohe',          num_ohe_pipeline,          num_ohe_cols),
        ('cat_ord_absent',   cat_ord_absent_pipeline,   cat_ord_absent_cols),
        ('cat_ord_missing',  cat_ord_missing_pipeline,  cat_ord_missing_cols),
        ('cat_ohe_absent',   cat_ohe_absent_pipeline,   cat_ohe_absent_cols),
        ('cat_ohe_missing',  cat_ohe_missing_pipeline,  cat_ohe_missing_cols),
        ('drop',    'drop',                             ['Id']),
    ],
    remainder='passthrough',
    verbose_feature_names_out=False,
)

preprocessor.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('num_impute',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='median')),
                                                 ('scale', StandardScaler())]),
                                 ['LotFrontage', 'LotArea', 'OverallQual',
                                  'OverallCond', 'YearBuilt', 'YearRemodAdd',
                                  'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
                                  'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF',
                                  '2ndFlrSF', 'LowQualFinSF', 'GrLivAre...
                                                                sparse_output=False))]),
                                 ['MSZoning', 'Street', 'LotShape',
                                  'LandContour', 'Utilities', 'LotConfig',
                                  'LandSlope', 'Neighborhood', 'Condition1',
                                  'Condition2', 'BldgType', 'HouseStyle',
                                  'RoofStyle', 'RoofMatl', 'Exterior1st',
                                  'Exterior2nd', 'Foundation', 'Heating',
                                  'CentralAir', 'Electrical', 'PavedDrive',
                                  'SaleType', 'SaleCondition']),
                                ('drop', 'drop', ['Id'])],
                  verbose_feature_names_out=False)

In [100]:
# scaling every column after preprocessing decreased accuracy.
# scaling only numeric columns is sufficient.

preprocessor_pipeline = Pipeline([
    ('preprocessor', preprocessor),
])

preprocessor_pipeline.set_output(transform='pandas')

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num_impute',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['LotFrontage', 'LotArea',
                                                   'OverallQual', 'OverallCond',
                                                   'YearBuilt', 'YearRemodAdd',
                                                   'MasVnrArea', 'BsmtFinSF1',
                                                   'BsmtFinSF2', 'BsmtUnfSF',
                                                   'TotalBsmtSF', '1stFlrSF',
                                                   '2n...
                                                                                 sparse_output=False))]),
                                                  ['MSZoning', 'Street',
                                                   'LotShape', 'LandContour',
                                                   'Utilities', 'LotConfig',
                                                   'LandSlope', 'Neighborhood',
                                                   'Condition1', 'Condition2',
                                                   'BldgType', 'HouseStyle',
                                                   'RoofStyle', 'RoofMatl',
                                                   'Exterior1st', 'Exterior2nd',
                                                   'Foundation', 'Heating',
                                                   'CentralAir', 'Electrical',
                                                   'PavedDrive', 'SaleType',
                                                   'SaleCondition']),
                                                 ('drop', 'drop', ['Id'])],
                                   verbose_feature_names_out=False))])

In [101]:
y_train_t = np.log1p(y_train)
y_test_t = np.log1p(y_test)

preprocessor_pipeline.fit(X_train, y_train_t)

X_train_t = preprocessor_pipeline.transform(X_train)
X_test_t = preprocessor_pipeline.transform(X_test)

### Full Pipeline (Linear Regression) ###

In [104]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', LinearRegression())
])

param_grid = {
    'preprocessor__preprocessor__num_impute__impute__strategy': ['mean', 'median'],
}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
)

search.fit(X_train, y_train_t)
cv_results_df = pd.DataFrame(search.cv_results_)

cv_results_df

   mean_fit_time  std_fit_time  mean_score_time  std_score_time param_preprocessor__preprocessor__num_impute__impute__strategy                                             params  split0_test_score  split1_test_score  split2_test_score  split3_test_score  split4_test_score  mean_test_score  std_test_score  rank_test_score  split0_train_score  split1_train_score  split2_train_score  split3_train_score  split4_train_score  mean_train_score  std_train_score
0       0.360777      0.259073         0.083052        0.026285                                               mean              {'preprocessor__preprocessor__num_impute__impu...          -0.163426          -0.142485          -0.203979          -0.172463          -0.182621        -0.172995        0.020373                2           -0.088076           -0.089692           -0.091193           -0.091805           -0.085969         -0.089347         0.002126
1       0.172910      0.045459         0.071261        0.005420                                             median              {'preprocessor__preprocessor__num_impute__impu...          -0.163390          -0.142456          -0.203974          -0.172457          -0.182637        -0.172983        0.020385                1           -0.088084           -0.089698           -0.091192           -0.091808           -0.085969         -0.089350         0.002126

### Full Pipeline (Ridge) ###

In [110]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Ridge())
])

param_grid = {
    'preprocessor__preprocessor__num_impute__impute__strategy': ['mean', 'median'],
    # 'model__alpha': [.001, .01, .05, .1, .5, 1, 5, 9, 9.1, 9.2, 9.3, 9.4],
    # 'model__alpha': np.linspace(.01, 50, 300),
    'model__alpha': np.logspace(np.log10(9.5), np.log10(10), 300),
}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
    verbose=1,
    n_jobs=-1
)

search.fit(X_train, y_train_t)
cv_results_df = pd.DataFrame(search.cv_results_)

cv_results_df

Fitting 5 folds for each of 600 candidates, totalling 3000 fits

     mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_model__alpha param_preprocessor__preprocessor__num_impute__impute__strategy                                             params  split0_test_score  split1_test_score  split2_test_score  split3_test_score  split4_test_score  mean_test_score  std_test_score  rank_test_score  split0_train_score  split1_train_score  split2_train_score  split3_train_score  split4_train_score  mean_train_score  std_train_score
0         0.203488      0.038527         0.122485        0.027955            9.500000                                               mean              {'model__alpha': 9.499999999999998, 'preproces...          -0.134634          -0.134157          -0.202748          -0.115203          -0.139021        -0.145153        0.029945              300           -0.111555           -0.111831           -0.101545           -0.114940           -0.111117         -0.110198         0.004532
1         0.217563      0.035363         0.125340        0.036894            9.500000                                             median              {'model__alpha': 9.499999999999998, 'preproces...          -0.134636          -0.134160          -0.202736          -0.115206          -0.139057        -0.145159        0.029937              600           -0.111558           -0.111825           -0.101547           -0.114934           -0.111112         -0.110195         0.004530
2         0.315310      0.090939         0.141205        0.026769            9.501630                                               mean              {'model__alpha': 9.5016298598526, 'preprocesso...          -0.134634          -0.134157          -0.202749          -0.115203          -0.139020        -0.145153        0.029945              299           -0.111556           -0.111832           -0.101546           -0.114941           -0.111119         -0.110199         0.004532
3         0.395334      0.111604         0.285780        0.109181            9.501630                                             median              {'model__alpha': 9.5016298598526, 'preprocesso...          -0.134636          -0.134161          -0.202736          -0.115206          -0.139057        -0.145159        0.029937              599           -0.111559           -0.111826           -0.101548           -0.114935           -0.111113         -0.110196         0.004530
4         0.457636      0.154157         0.164535        0.046811            9.503260                                               mean              {'model__alpha': 9.503259999330792, 'preproces...          -0.134634          -0.134158          -0.202749          -0.115203          -0.139020        -0.145153        0.029945              298           -0.111557           -0.111833           -0.101547           -0.114942           -0.111120         -0.110200         0.004532
5         0.400911      0.155299         0.185379        0.079468            9.503260                                             median              {'model__alpha': 9.503259999330792, 'preproces...          -0.134636          -0.134161          -0.202736          -0.115206          -0.139056        -0.145159        0.029938              598           -0.111560           -0.111827           -0.101549           -0.114936           -0.111114         -0.110197         0.004530
6         0.366657      0.121878         0.186484        0.061729            9.504890                                               mean              {'model__alpha': 9.504890418482551, 'preproces...          -0.134634          -0.134158          -0.202749          -0.115203          -0.139020        -0.145153        0.029945              297           -0.111558           -0.111834           -0.101548           -0.114944           -0.111121         -0.110201         0.004533
7         0.412411      0.131642         0.141532        0.032443            9.504890                                             median              {'model__alpha': 9.504890418482551, 'preproces...          -0.134636          -0.134161          -0.202737          -0.115206          -0.139056        -0.145159        0.029938              597           -0.111561           -0.111828           -0.101549           -0.114937           -0.111115         -0.110198         0.004530
8         0.267483      0.056481         0.147536        0.061540            9.506521                                               mean              {'model__alpha': 9.506521117355861, 'preproces...          -0.134634          -0.134158          -0.202750          -0.115203          -0.139020        -0.145153        0.029945              296           -0.111559           -0.111835           -0.101549           -0.114945           -0.111122         -0.110202         0.004533
9         0.350318      0.097767         0.137119        0.031487            9.506521                                             median              {'model__alpha': 9.506521117355861, 'preproces...          -0.134636          -0.134161          -0.202737          -0.115206          -0.139056        -0.145159        0.029938              596           -0.111562           -0.111829           -0.101550           -0.114938           -0.111116         -0.110199         0.004530
10        0.380568      0.054507         0.116691        0.009953            9.508152                                               mean              {'model__alpha': 9.50815209599871, 'preprocess...          -0.134634          -0.134158          -0.202750          -0.115203          -0.139019        -0.145153        0.029945              295           -0.111560           -0.111836           -0.101549           -0.114946           -0.111123         -0.110203         0.004533
11        0.407440      0.112275         0.218174        0.052162            9.508152                                             median              {'model__alpha': 9.50815209599871, 'preprocess...          -0.134636          -0.134161          -0.202737          -0.115205          -0.139055        -0.145159        0.029938              595           -0.111563           -0.111830           -0.101551           -0.114940           -0.111118         -0.110200         0.004530
12        0.354375      0.136712         0.137581        0.052169            9.509783                                               mean              {'model__alpha': 9.509783354459097, 'preproces...          -0.134634          -0.134158          -0.202750          -0.115203          -0.139019        -0.145153        0.029945              294           -0.111561           -0.111837           -0.101550           -0.114947           -0.111124         -0.110204         0.004533
13        0.257282      0.012778         0.115779        0.004658            9.509783                                             median              {'model__alpha': 9.509783354459097, 'preproces...          -0.134636          -0.134161          -0.202738          -0.115205          -0.139055        -0.145159        0.029938              594           -0.111565           -0.111831           -0.101552           -0.114941           -0.111119         -0.110201         0.004531
14        0.254461      0.018063         0.115628        0.015689            9.511415                                               mean              {'model__alpha': 9.511414892785028, 'preproces...          -0.134634          -0.134158          -0.202751          -0.115202          -0.139019        -0.145153        0.029946              293           -0.111562           -0.111838           -0.101551           -0.114948           -0.111125         -0.110205         0.004533
15        0.276000      0.048277         0.123909        0.017988            9.511415                                             median              {'model__alpha': 9.511414892785028, 'preproces...          -0.134636          -0.134161          -0.202738          -0.115205          -0.139055        -0.145159        0.029938              593           -0.111566           -0.111833           -0.101553           -0.114942           -0.111120         -0.110202         0.004531
16        0.286349      0.049668         0.136142        0.020234            9.513047                                               mean              {'model__alpha': 9.51304671102452, 'preprocess...          -0.134633          -0.134158          -0.202751          -0.115202          -0.139018        -0.145153        0.029946              292           -0.111563           -0.111839           -0.101552           -0.114949           -0.111127         -0.110206         0.004533
17        0.334864      0.064221         0.141918        0.043728            9.513047                                             median              {'model__alpha': 9.51304671102452, 'preprocess...          -0.134636          -0.134162          -0.202738          -0.115205          -0.139055        -0.145159        0.029938              592           -0.111567           -0.111834           -0.101554           -0.114943           -0.111121         -0.110204         0.004531
18        0.246026      0.035187         0.105959        0.007101            9.514679                                               mean              {'model__alpha': 9.514678809225593, 'preproces...          -0.134633          -0.134159          -0.202751          -0.115202          -0.139018        -0.145153        0.029946              291           -0.111564           -0.111840           -0.101553           -0.114950           -0.111128         -0.110207         0.004533
19        0.243354      0.021742         0.105506        0.002534            9.514679                                             median              {'model__alpha': 9.514678809225593, 'preproces...          -0.134636          -0.134162          -0.202738          -0.115205          -0.139054        -0.145159        0.029939              591           -0.111568           -0.111835           -0.101554           -0.114944           -0.111122         -0.110205         0.004531
20        0.232270      0.016780         0.106811        0.005149            9.516311                                               mean              {'model__alpha': 9.516311187436282, 'preproces...          -0.134633          -0.134159          -0.202751          -0.115202          -0.139018        -0.145153        0.029946              290           -0.111566           -0.111842           -0.101554           -0.114952           -0.111129         -0.110208         0.004533
21        0.226950      0.004517         0.108779        0.004616            9.516311                                             median              {'model__alpha': 9.516311187436282, 'preproces...          -0.134636          -0.134162          -0.202739          -0.115205          -0.139054        -0.145159        0.029939              590           -0.111569           -0.111836           -0.101555           -0.114945           -0.111123         -0.110206         0.004531
22        0.232675      0.012713         0.111174        0.004376            9.517944                                               mean              {'model__alpha': 9.517943845704623, 'preproces...          -0.134633          -0.134159          -0.202752          -0.115202          -0.139017        -0.145153        0.029946              289           -0.111567           -0.111843           -0.101554           -0.114953           -0.111130         -0.110209         0.004534
23        0.299812      0.070899         0.113170        0.011985            9.517944                                             median              {'model__alpha': 9.517943845704623, 'preproces...          -0.134636          -0.134162          -0.202739          -0.115205          -0.139054        -0.145159        0.029939              589           -0.111570           -0.111837           -0.101556           -0.114946           -0.111124         -0.110207         0.004531
24        0.237925      0.018314         0.113583        0.006779            9.519577                                               mean              {'model__alpha': 9.519576784078666, 'preproces...          -0.134633          -0.134159          -0.202752          -0.115202          -0.139017        -0.145153        0.029946              288           -0.111568           -0.111844           -0.101555           -0.114954           -0.111131         -0.110210         0.004534
25        0.228329      0.004516         0.109744        0.008607            9.519577                                             median              {'model__alpha': 9.519576784078666, 'preproces...          -0.134635          -0.134162          -0.202739          -0.115204          -0.139053        -0.145159        0.029939              588           -0.111571           -0.111838           -0.101557           -0.114948           -0.111125         -0.110208         0.004531
26        0.231353      0.013572         0.111950        0.020696            9.521210                                               mean              {'model__alpha': 9.521210002606466, 'preproces...          -0.134633          -0.134159          -0.202752          -0.115202          -0.139017        -0.145153        0.029946              287           -0.111569           -0.111845           -0.101556           -0.114955           -0.111132         -0.110211         0.004534
27        0.262614      0.034454         0.114108        0.018358            9.521210                                             median              {'model__alpha': 9.521210002606466, 'preproces...          -0.134635          -0.134162          -0.202740          -0.115204          -0.139053        -0.145159        0.029939              587           -0.111572           -0.111839           -0.101558           -0.114949           -0.111127         -0.110209         0.004531
28        0.236471      0.059509         0.107837        0.021307            9.522844                                               mean              {'model__alpha': 9.522843501336089, 'preproces...          -0.134633          -0.134159          -0.202753          -0.115201          -0.139016        -0.145153        0.029947              286           -0.111570           -0.111846           -0.101557           -0.114956           -0.111133         -0.110212         0.004534
29        0.259953      0.086864         0.111631        0.025984            9.522844                                             median              {'model__alpha': 9.522843501336089, 'preproces...          -0.134635          -0.134163          -0.202740          -0.115204          -0.139053        -0.145159        0.029939              586           -0.111573           -0.111840           -0.101558           -0.114950           -0.111128         -0.110210         0.004532
30        0.231815      0.028726         0.110705        0.007364            9.524477                                               mean              {'model__alpha': 9.524477280315608, 'preproces...          -0.134633          -0.134159          -0.202753          -0.115201          -0.139016        -0.145153        0.029947              285           -0.111571           -0.111847           -0.101558           -0.114957           -0.111135         -0.110213         0.004534
31        0.229483      0.006199         0.111031        0.009748            9.524477                                             median              {'model__alpha': 9.524477280315608, 'preproces...          -0.134635          -0.134163          -0.202740          -0.115204          -0.139052        -0.145159        0.029939              585           -0.111574           -0.111841           -0.101559           -0.114951           -0.111129         -0.110211         0.004532
32        0.224336      0.013763         0.113837        0.016310            9.526111                                               mean              {'model__alpha': 9.526111339593099, 'preproces...          -0.134633          -0.134160          -0.202753          -0.115201          -0.139016        -0.145153        0.029947              284           -0.111572           -0.111848           -0.101558           -0.114958           -0.111136         -0.110215         0.004534
33        0.273097      0.065283         0.119606        0.011906            9.526111                                             median              {'model__alpha': 9.526111339593099, 'preproces...          -0.134635          -0.134163          -0.202741          -0.115204          -0.139052        -0.145159        0.029940              584           -0.111575           -0.111842           -0.101560           -0.114952           -0.111130         -0.110212         0.004532
34        0.231117      0.017531         0.107672        0.003231            9.527746                                               mean              {'model__alpha': 9.527745679216656, 'preproces...          -0.134633          -0.134160          -0.202754          -0.115201          -0.139016        -0.145153        0.029947              283           -0.111573           -0.111849           -0.101559           -0.114960           -0.111137         -0.110216         0.004534
35        0.252672      0.024328         0.107530        0.002714            9.527746                                             median              {'model__alpha': 9.527745679216656, 'preproces...          -0.134635          -0.134163          -0.202741          -0.115204          -0.139052        -0.145159        0.029940              583           -0.111576           -0.111843           -0.101561           -0.114953           -0.111131         -0.110213         0.004532
36        0.233528      0.019082         0.107319        0.006373            9.529380                                               mean              {'model__alpha': 9.529380299234376, 'preproces...          -0.134633          -0.134160          -0.202754          -0.115201          -0.139015        -0.145153        0.029947              282           -0.111574           -0.111850           -0.101560           -0.114961           -0.111138         -0.110217         0.004534
37        0.237318      0.015845         0.110350        0.005390            9.529380                                             median              {'model__alpha': 9.529380299234376, 'preproces...          -0.134635          -0.134163          -0.202741          -0.115204          -0.139051        -0.145159        0.029940              582           -0.111578           -0.111844           -0.101562           -0.114954           -0.111132         -0.110214         0.004532
38        0.223720      0.012318         0.107085        0.009618            9.531015                                               mean              {'model__alpha': 9.531015199694364, 'preproces...          -0.134633          -0.134160          -0.202754          -0.115201          -0.139015        -0.145153        0.029947              281           -0.111575           -0.111851           -0.101561           -0.114962           -0.111139         -0.110218         0.004535
39        0.252533      0.031541         0.118422        0.013865            9.531015                                             median              {'model__alpha': 9.531015199694364, 'preproces...          -0.134635          -0.134163          -0.202741          -0.115203          -0.139051        -0.145159        0.029940              581           -0.111579           -0.111846           -0.101562           -0.114956           -0.111133         -0.110215         0.004532

### Full Pipeline (Lasso) ###

In [115]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Lasso(max_iter=10000))
])

param_grid = {
    'preprocessor__preprocessor__num_impute__impute__strategy': ['mean', 'median'],
    # 'model__alpha': [.0005, .0006, .0007, .0008, .0009, .001, .005, .01, .05, .1, .5, 1, 5, 10],
    'model__alpha': np.logspace(-5, 1, 300),
}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
    verbose=1,
    n_jobs=-1
)

search.fit(X_train, y_train_t)
cv_results_df = pd.DataFrame(search.cv_results_)

cv_results_df

Fitting 5 folds for each of 600 candidates, totalling 3000 fits

KeyboardInterrupt:

### Final Pipeline (ElasticNet) ###

In [117]:
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import GridSearchCV, cross_validate
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=1337)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', ElasticNet(max_iter=10000))
])

param_grid = {
    'preprocessor__preprocessor__num_impute__impute__strategy':
        ['mean', 'median'],
    # 'model__alpha':
    #     [.0005, .001, .002, .005, .1, .5, 1],
    # 'model__l1_ratio':
    #     [.1, .2, .3, .4, .5, .6, .7, .8, .9],

    'model__alpha':
        np.logspace(-4, 1, 30),
    'model__l1_ratio':
        np.linspace(.05, .95, 20)
}

# {\'model__alpha\': 0.0007278953843983154, \'model__l1_ratio\': 0.7131578947368421, \'preprocessor__preprocessor__num_impute__impute__strategy\': \'mean\'}

search = GridSearchCV(
    final_pipeline,
    param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
    verbose=1,
    n_jobs=-1,
)

search.fit(X_train, y_train_t)
cv_results_df = pd.DataFrame(search.cv_results_)
cv_results_df

Fitting 5 folds for each of 1200 candidates, totalling 6000 fits

      mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_model__alpha  param_model__l1_ratio param_preprocessor__preprocessor__num_impute__impute__strategy                                             params  split0_test_score  split1_test_score  split2_test_score  split3_test_score  split4_test_score  mean_test_score  std_test_score  rank_test_score  split0_train_score  split1_train_score  split2_train_score  split3_train_score  split4_train_score  mean_train_score  std_train_score
0          1.849657      0.451527         0.175588        0.052266            0.000100               0.050000                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.154017          -0.139171          -0.202787          -0.151965          -0.166145        -0.162817        0.021739              634           -0.089031           -0.090365           -0.091417           -0.092494           -0.086947         -0.090051         0.001929
1          2.169421      0.375109         0.270007        0.097461            0.000100               0.050000                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.153982          -0.139145          -0.202781          -0.151953          -0.166152        -0.162803        0.021747              633           -0.089039           -0.090371           -0.091417           -0.092497           -0.086948         -0.090054         0.001929
2          1.911086      0.316967         0.196060        0.090735            0.000100               0.097368                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.153676          -0.138782          -0.201984          -0.150294          -0.164840        -0.161915        0.021689              626           -0.089098           -0.090423           -0.091491           -0.092545           -0.087000         -0.090111         0.001931
3          1.892845      0.449509         0.150945        0.027947            0.000100               0.097368                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.153639          -0.138755          -0.201977          -0.150283          -0.164848        -0.161900        0.021697              625           -0.089106           -0.090428           -0.091491           -0.092548           -0.087000         -0.090115         0.001930
4          1.607182      0.620126         0.172680        0.041286            0.000100               0.144737                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.153315          -0.138304          -0.201901          -0.148549          -0.163493        -0.161113        0.021946              614           -0.089176           -0.090491           -0.091579           -0.092604           -0.087060         -0.090182         0.001932
5          1.665111      0.433308         0.178837        0.065865            0.000100               0.144737                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.153278          -0.138279          -0.201896          -0.148536          -0.163500        -0.161098        0.021954              613           -0.089184           -0.090496           -0.091579           -0.092606           -0.087061         -0.090185         0.001932
6          1.102434      0.269880         0.133943        0.016410            0.000100               0.192105                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152980          -0.137553          -0.201986          -0.146697          -0.162269        -0.160297        0.022350              602           -0.089261           -0.090558           -0.091675           -0.092670           -0.087123         -0.090258         0.001936
7          1.246121      0.200673         0.148065        0.028619            0.000100               0.192105                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152935          -0.137529          -0.201979          -0.146699          -0.162275        -0.160284        0.022355              601           -0.089269           -0.090564           -0.091675           -0.092673           -0.087124         -0.090261         0.001936
8          1.137203      0.347783         0.140208        0.016574            0.000100               0.239474                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152648          -0.136979          -0.202184          -0.144841          -0.161349        -0.159600        0.022778              588           -0.089352           -0.090635           -0.091776           -0.092728           -0.087171         -0.090332         0.001943
9          0.961901      0.221209         0.139955        0.016369            0.000100               0.239474                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152599          -0.136960          -0.202179          -0.144846          -0.161354        -0.159588        0.022783              586           -0.089360           -0.090640           -0.091776           -0.092731           -0.087172         -0.090336         0.001942
10         0.960877      0.207759         0.155021        0.023064            0.000100               0.286842                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152402          -0.136193          -0.202333          -0.142974          -0.160547        -0.158890        0.023241              572           -0.089443           -0.090713           -0.091883           -0.092796           -0.087215         -0.090410         0.001954
11         0.899537      0.328487         0.131412        0.004555            0.000100               0.286842                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152358          -0.136175          -0.202330          -0.142967          -0.160552        -0.158876        0.023247              571           -0.089451           -0.090718           -0.091883           -0.092799           -0.087215         -0.090413         0.001954
12         0.851007      0.286089         0.128752        0.003746            0.000100               0.334211                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152191          -0.135374          -0.202511          -0.141150          -0.159727        -0.158191        0.023722              554           -0.089543           -0.090795           -0.091994           -0.092870           -0.087266         -0.090494         0.001965
13         0.759522      0.215772         0.132047        0.012374            0.000100               0.334211                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152144          -0.135354          -0.202507          -0.141141          -0.159730        -0.158175        0.023728              553           -0.089552           -0.090801           -0.091994           -0.092873           -0.087266         -0.090497         0.001965
14         0.778883      0.245574         0.130787        0.008535            0.000100               0.381579                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152005          -0.134496          -0.202679          -0.139325          -0.158955        -0.157492        0.024220              540           -0.089657           -0.090875           -0.092108           -0.092948           -0.087328         -0.090583         0.001973
15         0.713468      0.223570         0.129361        0.015690            0.000100               0.381579                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.151955          -0.134479          -0.202675          -0.139317          -0.158957        -0.157477        0.024225              539           -0.089665           -0.090881           -0.092108           -0.092951           -0.087329         -0.090587         0.001973
16         0.792999      0.196275         0.144098        0.023416            0.000100               0.428947                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.151818          -0.133725          -0.202871          -0.138184          -0.158189        -0.156957        0.024610              528           -0.089784           -0.090966           -0.092231           -0.093021           -0.087399         -0.090680         0.001977
17         0.711644      0.232891         0.121463        0.013608            0.000100               0.428947                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.151766          -0.133706          -0.202867          -0.138176          -0.158192        -0.156941        0.024615              525           -0.089793           -0.090971           -0.092231           -0.093024           -0.087399         -0.090684         0.001977
18         0.684122      0.236829         0.130219        0.003451            0.000100               0.476316                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.151691          -0.132969          -0.203084          -0.137452          -0.157431        -0.156525        0.024943              506           -0.089925           -0.091068           -0.092366           -0.093091           -0.087481         -0.090786         0.001977
19         0.675021      0.197589         0.135698        0.008200            0.000100               0.476316                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.151635          -0.132948          -0.203081          -0.137440          -0.157434        -0.156508        0.024949              505           -0.089934           -0.091074           -0.092366           -0.093095           -0.087482         -0.090790         0.001977
20         0.650327      0.164958         0.136404        0.028880            0.000100               0.523684                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.151739          -0.132200          -0.203285          -0.136714          -0.156713        -0.156130        0.025270              492           -0.090066           -0.091178           -0.092510           -0.093165           -0.087570         -0.090898         0.001979
21         0.717036      0.208697         0.135112        0.003383            0.000100               0.523684                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.151683          -0.132181          -0.203282          -0.136700          -0.156720        -0.156113        0.025277              491           -0.090075           -0.091184           -0.092510           -0.093169           -0.087570         -0.090901         0.001979
22         0.646124      0.198529         0.126266        0.010311            0.000100               0.571053                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.151900          -0.131446          -0.203495          -0.135990          -0.156041        -0.155774        0.025596              474           -0.090217           -0.091294           -0.092658           -0.093245           -0.087662         -0.091015         0.001981
23         0.729884      0.176379         0.139193        0.020667            0.000100               0.571053                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.151843          -0.131427          -0.203492          -0.135971          -0.156048        -0.155756        0.025603              473           -0.090226           -0.091299           -0.092657           -0.093249           -0.087662         -0.091019         0.001982
24         0.632194      0.246645         0.129625        0.012463            0.000100               0.618421                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152181          -0.130741          -0.203725          -0.135376          -0.155380        -0.155481        0.025902              460           -0.090370           -0.091409           -0.092813           -0.093323           -0.087764         -0.091136         0.001981
25         0.635387      0.250506         0.140193        0.048945            0.000100               0.618421                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152124          -0.130723          -0.203723          -0.135362          -0.155387        -0.155464        0.025909              459           -0.090378           -0.091414           -0.092813           -0.093326           -0.087764         -0.091139         0.001981
26         0.677720      0.287907         0.144181        0.020041            0.000100               0.665789                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152438          -0.130165          -0.203988          -0.134843          -0.154740        -0.155235        0.026189              452           -0.090532           -0.091526           -0.092983           -0.093401           -0.087878         -0.091264         0.001980
27         0.636354      0.287272         0.131706        0.012178            0.000100               0.665789                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152387          -0.130148          -0.203986          -0.134837          -0.154746        -0.155221        0.026193              450           -0.090541           -0.091532           -0.092983           -0.093405           -0.087877         -0.091268         0.001980
28         0.578771      0.223912         0.133756        0.015867            0.000100               0.713158                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152917          -0.129631          -0.204137          -0.134324          -0.154134        -0.155028        0.026422              442           -0.090703           -0.091641           -0.093137           -0.093481           -0.087997         -0.091392         0.001974
29         0.644295      0.301755         0.126404        0.007786            0.000100               0.713158                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.152856          -0.129613          -0.204136          -0.134319          -0.154140        -0.155013        0.026427              441           -0.090712           -0.091647           -0.093137           -0.093485           -0.087997         -0.091395         0.001974
30         0.584987      0.282758         0.125118        0.011638            0.000100               0.760526                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.153526          -0.129116          -0.204338          -0.133807          -0.153569        -0.154871        0.026674              432           -0.090886           -0.091748           -0.093273           -0.093560           -0.088120         -0.091517         0.001962
31         0.566218      0.280754         0.127760        0.012698            0.000100               0.760526                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.153465          -0.129100          -0.204338          -0.133809          -0.153576        -0.154857        0.026677              431           -0.090895           -0.091754           -0.093273           -0.093563           -0.088119         -0.091521         0.001962
32         0.495553      0.173703         0.130158        0.024887            0.000100               0.807895                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.154210          -0.128634          -0.204524          -0.133325          -0.153028        -0.154744        0.026914              430           -0.091089           -0.091857           -0.093402           -0.093639           -0.088252         -0.091648         0.001946
33         0.511179      0.202128         0.130569        0.007392            0.000100               0.807895                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.154147          -0.128616          -0.204524          -0.133327          -0.153033        -0.154729        0.026917              427           -0.091098           -0.091863           -0.093402           -0.093643           -0.088251         -0.091651         0.001946
34         0.433262      0.079636         0.119949        0.007571            0.000100               0.855263                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.154979          -0.128152          -0.204639          -0.132848          -0.152512        -0.154626        0.027133              424           -0.091307           -0.091973           -0.093530           -0.093723           -0.088387         -0.091784         0.001929
35         0.453833      0.090786         0.129038        0.006706            0.000100               0.855263                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.154916          -0.128134          -0.204639          -0.132848          -0.152518        -0.154611        0.027137              423           -0.091316           -0.091978           -0.093530           -0.093727           -0.088387         -0.091788         0.001930
36         0.427428      0.155339         0.113374        0.010619            0.000100               0.902632                                               mean              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.155678          -0.127682          -0.204785          -0.132386          -0.152018        -0.154510        0.027366              418           -0.091500           -0.092098           -0.093662           -0.093809           -0.088529         -0.091919         0.001914
37         0.438588      0.134986         0.112817        0.016798            0.000100               0.902632                                             median              {'model__alpha': 0.0001, 'model__l1_ratio': 0....          -0.155620          -0.127663          -0.204786          -0.132387          -0.152025        -0.154496        0.027369              417           -0.091511           -0.092103           -0.093662           -0.093813           -0.088528         -0.091923         0.001914

In [121]:
from sklearn.metrics import root_mean_squared_error
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet

final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', ElasticNet(alpha=0.0007278953843983154, l1_ratio=0.7131578947368421))
])
final_pipeline.fit(X_train, y_train_t)
y_pred = final_pipeline.predict(X_test)
print(root_mean_squared_error(y_test_t, y_pred))

y_pred = final_pipeline.predict(X_train)
print(root_mean_squared_error(y_train_t, y_pred))



# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', Lasso(alpha=.0007934096665797492))
# ])
# final_pipeline.fit(X_train, y_train_t)
# y_pred = final_pipeline.predict(X_test)
# print(root_mean_squared_error(y_test_t, y_pred))
#
# y_pred = final_pipeline.predict(X_train)
# print(root_mean_squared_error(y_train_t, y_pred))
#
#
# final_pipeline = Pipeline([
#     ('preprocessor', preprocessor_pipeline),
#     ('model', LinearRegression())
# ])
# final_pipeline.fit(X_train, y_train_t)
# y_pred = final_pipeline.predict(X_test)
# print(root_mean_squared_error(y_test_t, y_pred))
#
# y_pred = final_pipeline.predict(X_train)
# print(root_mean_squared_error(y_train_t, y_pred))

0.11544915376776345
0.10881045553882318
0.1156369745205326
0.11243910374712052
0.12966410509994647
0.09419088615888568

In [189]:
final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', Ridge(alpha=400))
])

cv_results = cross_validate(
    final_pipeline, X_train, y_train_t,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
)

cv_results_df = pd.DataFrame(cv_results)

train_root_mean_squared_error = -cv_results_df.mean()['train_score']
validation_root_mean_squared_error = -cv_results_df.mean()['test_score']

print(f'train_rmse: {train_root_mean_squared_error}')
print(f'validation_rmse: {validation_root_mean_squared_error}')

train_rmse: 0.10310912196089887
validation_rmse: 0.13957445547139208

In [118]:
final_pipeline = Pipeline([
    ('preprocessor', preprocessor_pipeline),
    ('model', ElasticNet(alpha=0.0007278953843983154, l1_ratio=0.7131578947368421))
])
test = pd.read_csv(PATH + '/test.csv')
test_ids = test['Id']

# final_pipeline.fit(pd.concat([X_train, X_test], axis=0, ignore_index=True), pd.concat([y_train_t, y_test_t], axis=0, ignore_index=True))
final_pipeline.fit(X_train, y_train_t)
prices_log = final_pipeline.predict(test)
prices = np.expm1(prices_log)

submission = pd.DataFrame({
    "Id": test_ids,
    "SalePrice": prices,
})

submission.to_csv("submission.csv", index=False)